### ISSUE TITLE
WIFI does not switch to better access point

### ISSUE THREAD

**Issue by lldaedalusll** [tbnobody/OpenDTU#1013]
### What happened?

- Installed the OpenDTU fine and put it into my WIFI
- this wifi had a bad connection because the access point was far away
- now I installed a much closer access point (with same WIFI SID - part of my mesh)
- the OpenDTU does not switch to the better access point now, it still takes the bad and far away one

### To Reproduce Bug

- Install the OpenDTU and put it into a WIFI
- now I install a second access point (with same WIFI SID - part of a wifi mesh)
- see that the OpenDTU does not switch to the new access point

### Expected Behavior

OpenDTU should use the best WIFI availabe for the configured SID

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.5.31

### Anything else?

Maybe this issue come from that OpenDTU saves the WIFI with the MAC of the access point.

**Comment by tbnobody** [comment]
This iis a duplicate if #997. Please read the comments in this issue...
