### ISSUE TITLE
Make bssid available via mqtt, webui, json, prometheus

### ISSUE THREAD

**Issue by juergen-weber** [tbnobody/OpenDTU#1014]
### Is your feature request related to a problem? Please describe.

I'm running OpenDTU in an AVM mesh-based, multi-repeater, single ssid WiFi network. In this environment OpenDTU only sporadically finds the AP with the highest field strength. 

### Describe the solution you'd like

To facilitate the analysis of this problem and to complete the already existing set of WiFi parameters, I propose to make also the access point's BSSID available via MQTT, JSON, Prometheus and WebUI.

**Comment by tbnobody** [comment]
Implemented in 91d3cd1da277c1f4590cea04a105f2e691f362a8, b3e41c957bff2b94a7d0a7daceb09842fa5443db and 88cb59d1779166fc1179b09f5923fe6fc5635427
