### ISSUE TITLE
MQTT funkrioniert nach Update auf v23.6.9 nicht mehr

### ISSUE THREAD

**Issue by EvilBlood** [tbnobody/OpenDTU#1017]
### What happened?

Nach dem Update auf die FW. v23.6.9 nciht mehr. 
In der Config ist es aktiviert aber es sendet keine Daten mehr.
MQTT Settings einmal neu Speichern behebt das Problem. 

### To Reproduce Bug

Update auf FW v23.6.9 ausführen

### Expected Behavior

MQTT sollte nach Update einfach weiter daten senden. 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.9

### Anything else?

Githash wird auch nicht mehr im Webui angezeigt.

**Comment by tbnobody** [comment]
Mach doch mal ein paar screenshots. Von der Stelle mit dem  Git Hash und von Info --> MQTT. Klappt hier auf 5 ESPs nämlich ohne Probleme.

**Comment by EvilBlood** [comment]
![grafik](https://github.com/tbnobody/OpenDTU/assets/92166/3255faa9-aa47-428a-b23b-6a6ad530e027)
bei dem Blauen kassten stand mal der hash. nun ist nur noch die Firmware version da.

![grafik](https://github.com/tbnobody/OpenDTU/assets/92166/e73e7b85-d90a-495d-b508-d9e2d8402f01)
![grafik](https://github.com/tbnobody/OpenDTU/assets/92166/f1bec7f1-1b9a-4ac6-a74e-2018243bdd71)

Das sind die Settings diese habe ich nur gespeichert und dann lief MQtt wieder.

**Comment by tbnobody** [comment]
> bei dem Blauen kassten stand mal der hash. nun ist nur noch die Firmware version da.

Das ist korrekt so. Wenn der aktuelle Git-Hash auf einen Git-Tag zeigt wird dort einfachhalber der entsprechende Git-Tag angezeigt. In dem Fall verhält sich der Tag genauso wie ein Git-Hash. 
Du kannst also auf https://github.com/tbnobody/OpenDTU/tree/170978c6f8ca97e2b6dfe9826b76466c65315c59 gehen oder auf https://github.com/tbnobody/OpenDTU/tree/v23.6.9 das macht keinen Unterschied. Ebenfalls sieht man die Tags ja auch wunderbar im Git-Log.


Leider ist es jetzt natürlich nicht mehr nachvollziehbar warum das MQTT nicht verbunden hat. Dafür hätte man im entsprechenden Zustand genauer hinsehen müssen. (Screenshot von Info --> MQTT und Wert der `solar/daniel/dtu/status` Topic)

**Comment by EvilBlood** [comment]
Also die Settings waren genau die gleichen wie auf dem Screenshot ich habe nur auf speichern gedrückt.

Der MQTT wert war Offline und warn mit dem MQTT Explorer für über 2 Minuten keine Aktualisierungen auf dem Pfad solar/daniel zu sehen (zu dem Zeitpunkt hatte ich schon ca. eine Stunde keine Daten mehr erhalten via MDTT.

Im Webinterface war der Wechselrichter ohne Probleme erreichbar und hat seine werte auch aktualisiert.

**Comment by HeinKlocktein** [comment]
Ist bei mir genau so.
Speichern oder den ESP neustarten und die MQTT Übertragung läuft wieder. Der MQTT Server läuft und empfängt von anderen ESPs.

**Comment by tbnobody** [comment]
Und ich frage noch einmal nach folgendem wenn das passiert :)
Screenshot von Info --> MQTT und Wert der `solar/dtu/status` Topic

**Comment by 3joern** [comment]
Salute, sorry wenn ich hier reinkrätsche, mir fällt in letzter Zeit auch öfters auf, dass gewisse Daten per MQTT nicht mehr rausgeschickt werden. Die Betonung auf gewisse Daten, hier zB was beim ioBroker ankommt, einmal die Power, die hat oft Aussetzer (siehe 14:22 - 14:28 kam nichts durch), während die Temperatur zur gleichen Zeit problemlos alle 60sek geliefert wird. Frage, ist das das gleiche Problem hier und 2 was kann das sein?

Power
![Bildschirmfoto 2023-06-19 um 17 34 47](https://github.com/tbnobody/OpenDTU/assets/18442198/f0b01649-51c1-4d4f-83bf-490312ac614c)

Temperatur
![Bildschirmfoto 2023-06-19 um 17 35 45](https://github.com/tbnobody/OpenDTU/assets/18442198/3010bd65-b95f-4047-a4a3-397980d75a89)

**Comment by HeinKlocktein** [comment]
> Und ich frage noch einmal nach folgendem wenn das passiert :) Screenshot von Info --> MQTT und Wert der `solar/dtu/status` Topic

Siehe https://github.com/tbnobody/OpenDTU/issues/965

**Comment by tbnobody** [comment]
please check version [v23.7.12](https://github.com/tbnobody/OpenDTU/releases/tag/v23.7.12) 
It fixes a reconnect error of the mqtt client.

**Comment by tbnobody** [comment]
Going to close this issue asa from my standpoint it should be fixed. Feel free to reopen or open a new one.
