### ISSUE TITLE
Unbekanntes Gerät (HMS-600)

### ISSUE THREAD

**Issue by Jamie-Jameson** [tbnobody/OpenDTU#1019]
### What happened?

Hallo,

in der Wechselrichter-Information wird mein Gerät nicht erkannt und ich wurde aufgefordert, dies als Issue zu melden. Das mache ich hiermit.

Die HW-Teilnummer ist: 270602497
Modell ist ein normaler HMS-600-2T

Grüße

### To Reproduce Bug

Meinen WR mit OpenDTU auslesen

### Expected Behavior

Gerät soll erkannt werden

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.4.28

**Comment by tbnobody** [comment]
This was already implemented in 99ab78d5440a45de5a77e6cfad199cb5aa09d690 which belongs to v23.5.9
