### ISSUE TITLE
default system profile disables CMT2300A and enables Nrf24 even though its not even available

### ISSUE THREAD

**Issue by blitterz** [tbnobody/OpenDTU#1023]
### What happened?

firmware update to v23.6.9, downgrade does not help

### To Reproduce Bug

update firmware I guess

### Expected Behavior

Should leave CMT2300a active not enable a Chip that is not even installed:

![image](https://github.com/tbnobody/OpenDTU/assets/76099106/5d834b36-4b71-4479-a4e6-dac25f447005)
![image](https://github.com/tbnobody/OpenDTU/assets/76099106/4420e7e5-f63b-4099-8ff0-8f598e091d86)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

170978c

**Comment by tbnobody** [comment]
It seems that you either deleted your device profile or did not select it correctly. Just reupload your device profile and enable it again? 
What firmware .bin file did you flash? opendtu-generic.bin or opendtu-generic.factory.bin?

**Comment by blitterz** [comment]
the profile has been modified to work with CMT2300a, now after firmware upgrade the profile has been overwritten with the default installation profile. i did a factory reset, but its even worse now because now the display and led is not working anymore.

[opendtu-generic.bin](https://github.com/tbnobody/OpenDTU/releases/download/v23.6.9/opendtu-generic.bin)

**Comment by tbnobody** [comment]
If you've done a factory profile then you've just deleted all your settings (which is the intention of a factory reset). 
By doing a OTA device update it's not possible to delete the pin_mapping. There is just no code which could ever do this. 
But just re-upload your modified device profile and set it up as previously?

**Comment by blitterz** [comment]
I have reflashed the device, now old Settings are back:

**Comment by blitterz** [comment]
I have reflashed the device, now old settings are back:

![image](https://github.com/tbnobody/OpenDTU/assets/76099106/2f26f766-2389-49d5-9a12-3cdff19cd28e)
![image](https://github.com/tbnobody/OpenDTU/assets/76099106/0ddb4038-c8c4-4b34-934a-6c74bfb19a21)

I will try to update the firmware soon again

**Comment by tbnobody** [comment]
As far as I see it, it will fail again. Because you built the pin config into your current firmware. There is no device profile.
Please see https://github.com/tbnobody/OpenDTU/blob/master/docs/DeviceProfiles.md

**Comment by tbnobody** [comment]
Would close this issue as it is (for now) not really a issue.
