### ISSUE TITLE
Strings are having a strange issue

### ISSUE THREAD

**Issue by nG64** [tbnobody/OpenDTU#1030]
### What happened?

Hallo, ich habe seit kurzem das Problem dass meine Strings auf der openDTU Seite nicht mehr korrekt angeziegt werden. Ich habe String 3, 4, 5 und 6 angeschlossen. Jedoch zeigt er mir die Watt- Werte auf String 1 und 2 an. Die Einstrahlungs - % jedoch auf den richtigen String. Ich habe schon versucht die DTU zurückzusetzen, jedoch ohne Erfolg. Wenn ich String 5 und 6 auf String 1 und 2 mache werden die Watt-Werte nach 5 und 6 getauscht und die Einstrahlungswerte nach 5 und 6

https://ibb.co/c6fvzkk

### To Reproduce Bug

switching the inputs didn't work

### Expected Behavior

was working in the beginning

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.9

**Comment by tbnobody** [comment]
Duplicate of #1025
