### ISSUE TITLE
Thank you / sponsorships?

### ISSUE THREAD

**Issue by suhlig** [tbnobody/OpenDTU#1038]
### Is your feature request related to a problem? Please describe.

Hello, I would like to thank the creators and maintainers of this project. It took less than half an hour to connect to my inverter and get meaningful data.

Do you accept donations or GitHub sponsorships? If not, do you have a preference which org I should donate some money to (e.g. Doctors Without Borders)?

### Describe the solution you'd like

A statement by the maintainers whether they accept donations, and if not, where to send money to instead.

### Describe alternatives you've considered

Looked for Kofi, GH sponsorship, donation statements in the README and discussions.

### Additional context

I am happy with the project and would like to donate some money as a "Thank you" gesture.

**Comment by DcFamas** [comment]
On the mainpage:

![grafik](https://github.com/tbnobody/OpenDTU/assets/35306967/8792fdf1-82f4-4576-b6f8-e9576542fb8d)

https://ko-fi.com/tbnobody

**Comment by suhlig** [comment]
Not sure if I overlooked it, or if it is new, but anyway: Thanks!
