### ISSUE TITLE
Bei Wechselrichter nur Phase 1-änderung?

### ISSUE THREAD

**Issue by Hubert1975** [tbnobody/OpenDTU#1044]
### Is your feature request related to a problem? Please describe.

Bei Wechselrichter nur Phase 1-änderung in diesem Feld möglich? siehe Bild.

### Describe the solution you'd like

Bei Wechselrichter Änderungsmöglichkeit Phase 1, 2, 3 oder Farben schwarz, braun .....
![Lumii_20230616_143051696](https://github.com/tbnobody/OpenDTU/assets/130255575/b0537a97-2f1e-4471-9fb7-b9e39511362b)

**Comment by DPO99** [comment]
Ich glaube du verwechselst den Sinn dieser Anzeige. Die ist an sich nur dafür da, die Phasen des HM anzuzeigen. Du möchtest aber quasi angeben, an welchem Leiter L1,L2,L3 das Ding an Deinem Netz hängt oder?

**Comment by tbnobody** [comment]
Das  was @DPO99 sagst ist korrekt. bei HM/HMS invertern gibt es nur eine Phase. Diese hat auch nur diesen einen Namen. Bei HMT Invertern sieht das anders aus. Diese Zuordnung wird sich aber ggf. in zukunft noch ändern.

**Comment by Hubert1975** [comment]
Ja ich habe 3 Wechselrichter Hm 1500 und jeder auf einer Phase, damit im Haus gut aufgeteilt.... deswegen meine Frage!
