### ISSUE TITLE
Unbekanntes Model: HMS-400

### ISSUE THREAD

**Issue by cl8x** [tbnobody/OpenDTU#1045]
### What happened?

Unbekanntes Modell:  

Modell: HMS-400
Hardware Teilenummer: 270549248  

Gruß,
Christian

### To Reproduce Bug

Wechselrichter Information anzeigen

### Expected Behavior

Erfolgreiche Geräteerkennung in openDTU

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

23.6.14

**Comment by homeautomation2022** [comment]
@tbnobody 
https://github.com/tbnobody/OpenDTU/blob/master/lib/Hoymiles/src/parser/DevInfoParser.cpp#L32
`{ { 0x10, 0x20, 0x41, ALL }, 400, "HMS-400" }, // 00`
