### ISSUE TITLE
Config for AZ-Delivery nodemcu v3 (8266) 

### ISSUE THREAD

**Issue by gd35** [tbnobody/OpenDTU#105]
I tried to use a nodemcu (8266) with OpenDTU but I faced a config problem as this model does not appear in the platformio.ini

After several attempts to add this device, I faced with compilation problems. Should such device work with OpenDTU or should I buy a ESP32 ?

Thanks

**Comment by tbnobody** [comment]
It will only work with a ESP32

**Comment by gd35** [comment]
Thanks for this cristal clear answer ;-) I will thus buy an ESP32.
