### ISSUE TITLE
[Request] Favicon

### ISSUE THREAD

**Issue by nonflammable** [tbnobody/OpenDTU#1060]
### Describe the solution you'd like

Please add favicon for smartphones and browsers
![IMG_20230620_231639](https://github.com/tbnobody/OpenDTU/assets/6041490/da4a5dbb-dfc9-4c1f-a529-fc9a770e3307)

**Comment by NintendoTito** [comment]
Can somebody describe where I can find the configuration for the touch icon? I can't find it.

**Comment by NintendoTito** [comment]
Kann mir bitte jemand sagen, wie ich ein entsprechendes Favicon einstellen kann? Ich bekomme es nicht hin.

**Comment by NintendoTito** [comment]
In der Hoffnung, dass ich hier nochmal ne Antwort bekomme... Wo stelle ich das Favicon ein?

**Comment by stefan123t** [comment]
Das Favicon wurde im Sommer diesen Jahres zum Web Interface hinzugefügt. Es sollte also entsprechend geladen werden wenn es mit dern richtigen webkit/safari headern annonciert wird und auch die entsprechend von iOS erwarteten Bild-Formate vorliegen.
Vielleicht musst Du also die WebApp neu anlegen.

In der Hoffnung dass Du noch beachreibst was Du bereits versucht hast ?

**Comment by NintendoTito** [comment]
> In der Hoffnung dass Du noch beachreibst was Du bereits versucht hast ?

Ich öffne die Weboberfläche der DTU in Chrome Android. Da gehe ich dann auf die 3 Punkte und wähle "zum Startbildschirm hinzufügen". Da erscheint dann aber kein Favicon.

**Comment by NintendoTito** [comment]
@nonflammable Du hast meinen Kommentar geliked... Hast du das Favicon auch noch nicht?

**Comment by nonflammable** [comment]
> @nonflammable Du hast meinen Kommentar geliked... Hast du das Favicon auch noch nicht?

No 🤷‍♂️

**Comment by NintendoTito** [comment]
Mmh, interessant. Favicon soll vorhanden sein, Thema als gelöst markiert, "keiner" weiß wie es funktioniert. Naja, ist ja kein Dealbreaker. Soll auch hier nicht falsch rüberkommen, OpenDTU ist genial und danke an die Entwickler, ich will mich da nicht beschweren!

**Comment by tbnobody** [comment]
@NintendoTito wird mit der nächsten Version behoben. Hatte bis heute kein Android Phone zur Hand um das zu testen. 
Hintergrund: Das Icon benötigt u.a. eine Mindestauflösung von 144x144 damit es dargestellt wird.

**Comment by NintendoTito** [comment]
@tbnobody Nur als Feedback: Habe das aktuelle Update eingespielt (die Version mit Einführung der Grafik). Ein Favicon ist unter Android weiterhin nicht vorhanden. Muss ich was bestimmtes anpassen oder kann ich mit irgend nem Log oder Infos unterstützen?
