### ISSUE TITLE
v23.6.14...HEAD broke nRF24 Chip (connection, identification?)

### ISSUE THREAD

**Issue by GeraldPape** [tbnobody/OpenDTU#1064]
### What happened?

Just updated to v23.6.14...HEAD and compiled with VS Code (as the last three months). Uploaded .bin file.
OTA was succesfull, but nRF24L01+Chip was not detected anymore.

Reverted to previous version, works again.

### To Reproduce Bug

upgrade to newest version

### Expected Behavior

still detect nRF24L01+

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

23.6.21

**Comment by tbnobody** [comment]
If you've selected the generic_esp32 environment you have to upload a device profile. if you used the generic environment in the past you have to manually select it now.
