### ISSUE TITLE
Unbekanntes Model HMS2000

### ISSUE THREAD

**Issue by oggli01** [tbnobody/OpenDTU#1066]
### What happened?

Unbekanntes Model HMS2000 
Hardware Teilenummer  124097

### To Reproduce Bug

Unbekanntes Model HMS2000 
Hardware Teilenummer  124097

### Expected Behavior

Unbekanntes Model HMS2000 
Hardware Teilenummer  124097

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

v23.6.21

### Relevant log/trace output

```Shell
Unbekanntes Model HMS2000 
Hardware Teilenummer  124097
```

### Anything else?

Unbekanntes Model HMS2000 
Hardware Teilenummer  124097

**Comment by homeautomation2022** [comment]
https://github.com/tbnobody/OpenDTU/issues/914#issuecomment-1560642692

**Comment by tbnobody** [comment]
Close due to inactivity...
