### ISSUE TITLE
Grid disconnected after OTA Upgrade to v23.6.21

### ISSUE THREAD

**Issue by Rustimation** [tbnobody/OpenDTU#1067]
### What happened?

Right after flashing the upgrade to v23.6.21 my HMS-1600 inverter showed "Grid disconnected". I checked the cabling, grid is still connected - no issue there. HOW CAN I REVERT TO A PREVIOUS VERSION

### To Reproduce Bug

OTA Upgrade with v23.6.21

### Expected Behavior

normal operation

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.21

**Comment by Rustimation** [comment]
My bad, I could revert to 23.6.14 but no changed behaviour. Grid still disconnected. openDTU connects to inverter w/o problem.

**Comment by DPO99** [comment]
maybe a restart of the inverter could help.

**Comment by Rustimation** [comment]
I tried that several times. No improvement.
![2023-06-22 18_16_29-OpenDTU – Mozilla Firefox](https://github.com/tbnobody/OpenDTU/assets/63803282/7df3cbae-0358-4959-8e03-54d9e054b50b)

**Comment by DPO99** [comment]
Ich mein die DTU liest das ja nur aus....kannst du AC und DC trennen? ggf. muss das Ding mal stromlos....zur Not über Nacht

**Comment by tbnobody** [comment]
Das was @DPO99 sagt. es gibt keinerlei Funktion ob so etwas wie ein Grid Disconnection herbeizuführen.

**Comment by tbnobody** [comment]
Und ggf. kannst du auch prüfen ob es nicht wirklich eine grid disconnection ist? Also wird 
1. wirklich nicht produziert und
2. ist auf der steckdose noch saft drauf?

**Comment by DPO99** [comment]
Also der Zufall wäre natürlich schon ungewöhnlich....aber einen Hardwaredefekt würde ich da erstmal ausschließen könnte mir nur vorstellen, dass der HM sich ggf. aufgehängt hat, weil er ggf. im falschen Moment zu viel abgefragt wurde mit infos befehlen, etc.

**Comment by Rustimation** [comment]
Hallo,Sorry für die ggf. entstandene Aufregung. Es geht wieder! Nachdem ich den Stecker gezogen hatte und wieder eingesteckt habe, ist der WR neu gestartet, weshalb ich dachte, AC seitig wäre alles okay. War wohl ein loses Kabel in der Steckdose, dass zwar für die AC Erkennung gereicht hat aber nicht für den Stromtransport. Dass das quasi zeitgleich mit dem Upgrade passiert ist, kann ich momentan nur einer Störung im Raum-Zeitkontinuum zuschreiben. Nochmal sorry und danke für eure Vorschläge. OpenDTU ist wirklich genial. VG aus Italien.Chris (www.rustimation.eu)Von meinem iPhone gesendetAm 22.06.2023 um 18:36 schrieb DPO99 ***@***.***>:﻿
Also der Zufall wäre natürlich schon ungewöhnlich....aber einen Hardwaredefekt würde ich da erstmal ausschließen könnte mir nur vorstellen, dass der HM sich ggf. aufgehängt hat, weil er ggf. im falschen Moment zu viel abgefragt wurde mit infos befehlen, etc.

**Comment by Rustimation** [comment]
Case closed
