### ISSUE TITLE
Event Log: ID 12, Unknown

### ISSUE THREAD

**Issue by Hermarcel** [tbnobody/OpenDTU#1068]
### What happened?

OpenDTU v23.6.21 with four HMS-2000-4T v01.00.20. Every inverter shows below message in it's event log:
![afbeelding](https://github.com/tbnobody/OpenDTU/assets/7933070/f4a62a48-0a85-457b-9529-d424529ef6cd)
Also with older versions.

### To Reproduce Bug

Just running the system

### Expected Behavior

Please, add explanation for ID 12?

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.21

### Anything else?

Used this link to download the firmware: https://discord.com/channels/984173303147155506/1060347063281401876/1121509260291997807

**Comment by tbnobody** [comment]
If there would be an explanation for the ID 12 it would be mentioned there. So it's just not possible as it is not explained in any documentation.

**Comment by stefan123t** [comment]
@Hermarcel Danke für die Meldung, ja es gibt noch ein paar Unbekannte / unknown Fehlermeldungen.
U.a. 
* 12 (https://github.com/tbnobody/OpenDTU/issues/1068),
* 14 (https://github.com/tbnobody/OpenDTU/issues/131),
* 12, 13, 14, 36,  (https://github.com/tbnobody/OpenDTU/issues/121),
* 12, 14, 36, 46, 47, 73 https://github.com/tbnobody/OpenDTU/discussions/590

Ich bin in den `assets/warn_code.json` der Hoymiles S-Miles Installer App fündig geworden. 🥳 

Hier mal die bisher aufgetretenen Fehler oder Warnings aus dem in #121 angehängten warn_code.json (GitHub versteht nur ZIP ?).

11: Grid voltage surge
12: Grid voltage sharp drop
13: Grid frequency mutation
14: Grid phase mutation
36: INV overvoltage or overcurrent
46: FB overvoltage
47: FB overcurrent
71: VW function enable
72: FW function enable
73: TW function enable

Es wird von @tbnobody im Rahmen von #121 in OpenDTU implementiert und daher kann dieses Issue als Duplicate geschlossen werden.
