### ISSUE TITLE
MQTT no cmd topics

### ISSUE THREAD

**Issue by mrstackit** [tbnobody/OpenDTU#1079]
### What happened?

Wechselrichter und OpenDTU komplett neu eingerichtet. Verbindung mit ioBorker MQTT hergestellt und keine cmd topics vorhanden.

### To Reproduce Bug

OpenDTU nach Neuinstallation mit mqtt Verbinden

### Expected Behavior

-

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.21

**Comment by tbnobody** [comment]
Klar gibt es keine CMD Topics. Da musst du ja auch Werte hinschicken. Suche mal bei den Discussions nach ioBroker. Dort findet man genug Topics die beschreiben wie das geht. Es ist nunmal nicht die Funktionsweise von MQTT das man dort Topics anlegen kann. Man published Werte na topics. Aber die Topics existieren dann nicht. Sondern alle Geräte die zu diesem Zeitpunkt auf eine Topic lauschen bekommen den entsprechenden Wert.
