### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by RemyRoland** [tbnobody/OpenDTU#1115]
### Is your feature request related to a problem? Please describe.

Hello,  when i shut down or stop the inverter ,the value of KWH is not save any where. So the production of these inverter is lost.
Is it possible to save this value in the total production of the day?.
Thank you.

Rémy Gross

### Describe the solution you'd like

Save the value of the KWH before it shuts down.

**Comment by tbnobody** [comment]
You are free to save it somewhere in any external software (home automation etc) which supports MQTT. But it is not forseen to save any data on the esp itself as it would destroy the internal flash over time.
