### ISSUE TITLE
Unknown HMS-500

### ISSUE THREAD

**Issue by t-diy** [tbnobody/OpenDTU#1148]
### What happened?

Hi, looks like I have a Serial Number in a different range and a newer Hardware Part Number for the HMS-500.

Inverter was first wrongly reconized as HM-300, I changed lib/Hoymiles/src/inverters/HMS_1CH.cpp to include Serial 0x1125.
Changed lib/Hoymiles/src/parser/DevInfoParser.cpp too (0x10, 0x20, 0x71, ALL) and with that the inverter can be controlled but I have wrong vaules in Live Data.

### To Reproduce Bug

![HMS-500](https://github.com/tbnobody/OpenDTU/assets/139644858/5d8cc92d-e2ee-4719-8bb9-010b4ab0eee8)

![OpenDTU](https://github.com/tbnobody/OpenDTU/assets/139644858/6be5a630-fc49-46bc-a1bf-12e9b17b2e95)

### Expected Behavior

Please include new Hardware Part Number 270561539 and Serial Number <1126xxxxxxxx.

What can be done to get the right vaules from the inverter?

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

9b0d2ff

### Relevant log/trace output

```Shell
18:00:00.805 > Fetch inverter: 1125837xxxxx
18:00:00.863 > TX RealTimeRunData 868.00 MHz --> 15 83 79 51 40 80 15 16 12 80 0B 00 64 B2 CC D7 00 00 00 00 00 00 00 00 09 F3 D3 
18:00:00.914 > Interrupt received
18:00:00.970 > RX 868.00 MHz --> 95 83 79 51 40 80 15 16 12 01 00 01 01 7D 00 00 00 DD 00 00 03 4D 00 00 00 00 00 | -56 dBm
18:00:01.017 > Interrupt received
18:00:01.064 > RX 868.00 MHz --> 95 83 79 51 40 80 15 16 12 02 33 B1 00 00 00 00 03 79 00 00 09 19 13 83 03 20 B6 | -56 dBm
18:00:01.119 > Interrupt received
18:00:01.216 > RX 868.00 MHz --> 95 83 79 51 40 80 15 16 12 83 00 00 00 22 03 E7 01 9D 00 59 00 37 58 | -57 dBm
18:00:01.352 > RX Period End
18:00:01.352 > Success
```

**Comment by tbnobody** [comment]
hm it seems that the inverters with 1125 are using a different byte assignment if your output is wrong. i didn't have a detailed look at your received data but it seems as we would need another class (is the cleanest method) to handle this kind of inverters.

**Comment by tbnobody** [comment]
> How did you guys found out what is Q and what is LOG ?

Log is easy. Just unplug your inverter. Log should increase.

**Comment by apibim-xyz** [comment]
I just implemented opendtu with blinkyparts solution.
No problem with an HMS1000, but like you, the HMS500 is recognized as an HM300.
Did you solve your problem and could you help me?

Here are the opendtu logs :

`17:44:16.898 > Fetch inverter: 11448500XXXX
17:44:16.942 > TX RealTimeRunData 865.00 MHz --> 15 85 00 17 25 80 14 19 44 80 0B 00 64 FF 35 D0 00 00 00 00 00 00 00 00 B8 6E 48 
17:44:17.011 > Interrupt received
17:44:17.021 > RX 865.00 MHz --> 95 85 00 17 25 80 14 19 44 01 00 01 01 5D 01 5F 00 99 00 9E 02 18 02 2D 00 00 DB | -67 dBm
17:44:17.054 > Interrupt received
17:44:17.071 > RX 865.00 MHz --> 95 85 00 17 25 80 14 19 44 02 00 DE 00 00 00 E8 00 DE 00 E8 09 47 13 85 04 0A 3F | -67 dBm
17:44:17.084 > Interrupt received
17:44:17.103 > RX 865.00 MHz --> 95 85 00 17 25 80 14 19 44 83 00 00 00 2B 03 E8 01 20 00 16 3F B6 16 | -67 dBm
17:44:17.510 > RX Period End
17:44:17.510 > Success`

No logs for serial 11258512XXXX in opendtu console.

Here are the MQTT broker logs :

` Message reçu sans prise en charge par un plugin : {"solar":{"11258512XXXX":{"name":"HMS500-1","status":{"reachable":1,"producing":0,"last_update":0}},"114485001725":{"name":"HMS1000-1","device":{"bootloaderversion":1,"fwbuildversion":10002}}}}
Message reçu sans prise en charge par un plugin : {"solar":{"11448500XXXX":{"0":{"powerdc":88.6,"yieldday":457,"yieldtotal":0.457,"voltage":237.6,"current":0.35,"power":83.8,"frequency":49.97,"powerfactor":0.999,"efficiency":94.582,"reactivepower":0,"temperature":28.9},"1":{"name":"","voltage":34.6,"current":1.25,"power":43.3,"yieldday":224,"yieldtotal":0.224,"irradiation":0},"2":{"name":"","voltage":34.6,"current":1.3,"power":45.3,"yieldday":233,"yieldtotal":0.233,"irradiation":0},"device":{"fwbuilddatetime":"2021-11-18 11:31:00","hwpartnumber":270627077,"hwversion":"01.00"},"status":{"limit_relative":100,"limit_absolute":1000,"reachable":1,"producing":1,"last_update":1694447175}},"ac":{"power":83.8,"yieldtotal":0.457,"yieldday":457,"is_valid":1},"dc":{"power":88.6,"irradiation":0,"is_valid":1}}}`

**Comment by tbnobody** [comment]
Does the event log work properly?

**Comment by tbnobody** [comment]
Could you please doublecheck if this patch works as expected?
[hms_1chv2.patch](https://github.com/tbnobody/OpenDTU/files/12601798/hms_1chv2.patch)

**Comment by apibim-xyz** [comment]
Thank you very much for your help which works :)
