### ISSUE TITLE
Firmware upgrade

### ISSUE THREAD

**Issue by gd35** [tbnobody/OpenDTU#119]
I have had to change the pin assignment due to a different ESP32 module (Joy-It). I generated a new firmware and tried to upload it with the "firmware Upgrade" item in the "Settings" menu. The upload stopped at 3-4%. Herewith is the log:

```
13:04:37.290 > Fetch inverter: 112182053057
13:04:47.319 > [ 90135][E][WiFiClient.cpp:421] write(): fail on fd 49, errno: 11, "No more processes"
13:04:47.757 > [ 90573][E][WiFiClient.cpp:421] write(): fail on fd 49, errno: 11, "No more processes"
13:04:48.758 > [ 91575][E][WiFiClient.cpp:421] write(): fail on fd 49, errno: 11, "No more processes"
13:04:49.725 > [ 92541][E][WiFiClient.cpp:421] write(): fail on fd 49, errno: 113, "Software caused connection abort"
13:04:49.735 > Disconnected from MQTT.
13:04:49.737 > Disconnect reason:TCP_DISCONNECTED
13:04:49.742 > WiFi disconnected
13:04:49.742 > Try reconnecting
13:04:49.744 > Network lost connection
13:04:49.776 > WiFi connected
13:04:49.826 > WiFi got ip: 192.168.1.20
13:04:49.829 > Network connected
13:04:49.830 > Connecting to MQTT...
13:04:49.860 > Connected to MQTT.
13:04:52.313 > Fetch inverter: 112182053057
13:05:03.878 > Websocket: [/livedata][2] connect

```

Any idea why the upload stopped ? Thanks.

**Comment by FWallenwein** [comment]
Same here. Tried to upload, and it stopped after 9%.

And a second question. 
When selection the firmware file, the browser points to ".bin" files. 
(     <input class="form-control" type="file" ref="file" accept=".bin,.bin.gz" @change="uploadOTA" />   ) 
In the readme file, it says choose the ".elf " file. 
Shouldn't it be     accept=".elf"     ?

**Comment by madmartin** [comment]
@FWallenwein I am sorry that I made a mistake in my pull request #116 . Please pick the *.bin file !!!!
PR is fixed in the meantime.

**Comment by gd35** [comment]
I did not questioned myself about the file type... Thanks to have pointed this. Now the upgrade ran fine !

**Comment by tbnobody** [comment]
> @tbnobody It will be fixed with https://github.com/tbnobody/OpenDTU/pull/116.

Thank you, just merged it.
