### ISSUE TITLE
Home assistant auto discovery is not working (nothing is published in the homeassistant topic) 

### ISSUE THREAD

**Issue by simonCor** [tbnobody/OpenDTU#1192]
### What happened?

It seems that the homeassistant mqtt auto discovery does not publish anything under the configured prefix.

The auto discovery did not work for me so i poked around and found the following:

This the opendtu config:
<img width="680" alt="image" src="https://github.com/tbnobody/OpenDTU/assets/1113780/28eebfde-bfb3-4a1d-b959-6d74c178a23e">

This is the state of the mqtt server:
<img width="454" alt="257607710-b1fd4ed1-8b7c-4a40-8293-b807588a20a3" src="https://github.com/tbnobody/OpenDTU/assets/1113780/a031f55b-7c72-4c0e-afc8-97caa5cd3bfb">

The solar topic is published but I would expect a "homeassistanttest" topic for auto discovery.

### To Reproduce Bug

- Configure opendtu for autodiscovery
- Start the device

(I do not know if this is important: Currently the device is not connected to the inverter - because it is not yet here)

### Expected Behavior

A working auto discovery in home assistant.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.7.22

### Relevant log/trace output

```Shell
none
```

### Anything else?

- I use Home Assistant 2023.4.2 but I don't think this is important
- The device is not connected to an inverter

**Comment by tbnobody** [comment]
Currently only inverter specific sensors and buttons are published. If you don't add any inverters nothing has to be published into the auto discovery topic. Therefor everything works absolutly as expected.
There is a open feature request (#1050) but its not implemented at the moment.
