### ISSUE TITLE
Missing Model HMS-1600

### ISSUE THREAD

**Issue by codebomber** [tbnobody/OpenDTU#1204]
### What happened?

while opening the inverter info, it tells me, that my model is unknown.
And It tells me to open a new bug report with the Hardware Number

My Inverter is the Hoymiles HMS-1600-4T
Hardware ID 124097

### To Reproduce Bug

opening inverter Info

### Expected Behavior

It tells me the exact information of my inverter 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.7.10

**Comment by tbnobody** [comment]
First of all, please upgrade to the latest version and doublecheck if the error still exists... if so, please provide a screenshot of the whole inverter info dialogue.

**Comment by tbnobody** [comment]
Closed due to inactivity
