### ISSUE TITLE
Related Project: dynamic-limit-managment-opendtu-shelly

### ISSUE THREAD

**Issue by gf78** [tbnobody/OpenDTU#1208]
### Is your feature request related to a problem? Please describe.

Thank you so much for your time and commitment that you put into this project. Thank you! 

Ro achieve zero injection ("Nulleinspeisung"), i wrote a small add on script that runs directly on a shelly 2nd generation device like the Shelly 3EM Pro and automatically adjusts the limit of the OpenDTU.

If you want, and the quality of the extension is sufficient for you, you are welcome to link the project as related one: 
https://github.com/gf78/dynamic-limit-managment-opendtu-shelly/

### Describe the solution you'd like

Add related project link: https://github.com/gf78/dynamic-limit-managment-opendtu-shelly/

**Comment by tbnobody** [comment]
I've just created a new page in the Wiki: https://github.com/tbnobody/OpenDTU/wiki/Related-Software
