### ISSUE TITLE
Yarn linter: Getting a value from the `props` in root scope of `setup()` will cause the value to lose reactivity

### ISSUE THREAD

**Issue by helgeerbe** [tbnobody/OpenDTU#1226]
### What happened?

Actual Yarn Linter throws error:

Getting a value from the `props` in root scope of `setup()` will cause the value to lose reactivity

### To Reproduce Bug

check action logs

### Expected Behavior

no error

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

ec67fe1

### Relevant log/trace output

```Shell
see action logfiles from yarn linter
```

### Anything else?

I'm not a vue expert.

But does this solve the issue?

Change code in line 55 from

````typescript
const countDown = ref(parseCountDown(props.modelValue));
````

to something like

````typescript
...
  import { computed, defineComponent, onBeforeUnmount, ref, toRefs, watch } from "vue";
...
  let { modelValue } = toRefs(props)
  const countDown = parseCountDown(modelValue.value);
````

**Comment by tbnobody** [comment]
Fixed by ac4ddbe23dd9597ebf974d4c6a8f623ec5ce2adf
