### ISSUE TITLE
Enhancement request: Support for Hoymiles HMT series.

### ISSUE THREAD

**Issue by thomasleitner** [tbnobody/OpenDTU#123]
Hoymiles have a new series of 3-phase inverters HMT-1800-6t and HMT-2250-6t.  
They support 6 panels with 3 MPPT. 

Any chance to see support for these soon?

**Comment by tbnobody** [comment]
Unfortunatly, HMT and HMS seems to be using a completly different RF module. Therefor suppoprt for these models is very unlikly.
