### ISSUE TITLE
[Request] Reduce MQTT data

### ISSUE THREAD

**Issue by Vikingfr** [tbnobody/OpenDTU#1248]
### Is your feature request related to a problem? Please describe.

Actually, with lot of solar equipement, MQTT become very verbose. 
But some users only need production data, not all data (like panel temperature).
I'm using mosquitto and it's time consuming to deal with useless data

(sorry if bad english, not my natural language)

### Describe the solution you'd like

can you add options in MQTT section to select type of data we want to send : global output, individual outputs, panels info, system info. 

### Describe alternatives you've considered

actuality, alternative are using API to only pull data I need, but MQTT is better as data can be send to multiple machines.

**Comment by tbnobody** [comment]
Not publishing any data does not make any sense. The load on the broker ist just minimal. If you don't need specific information on a specific device, just don't subscribe to this topic. In this case the broker will not send the data to the device.
