### ISSUE TITLE
Missing Model HMS-1600

### ISSUE THREAD

**Issue by ismail-38** [tbnobody/OpenDTU#1254]
### What happened?

While opening the inverter info, it tells me, that my model is unknown.
And It tells me to open a new bug report with the Hardware Number

My Inverter is the Hoymiles HMS-1600-4T
Hardware ID 124097
Firmware-Version 0.2.56

### To Reproduce Bug

Open inverter Info

### Expected Behavior

It tells me the exact information of my inverter

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.8.8

**Comment by tbnobody** [comment]
Could you please post the whole info screen?

**Comment by Mashup39** [comment]
![Screenshot_20230826-121941](https://github.com/tbnobody/OpenDTU/assets/131386616/a6c77ecf-ab9c-42f7-8014-125278a56f20)
![Screenshot_20230826-121930](https://github.com/tbnobody/OpenDTU/assets/131386616/05f0f1b7-b5ee-4516-a787-e81cbc452cd3)


Ich habe das gleiche Problem. Habe 2x den HMS 1600 verbaut. Hat auch immer alles gut funktioniert

**Comment by tbnobody** [comment]
I am going to close this issue. One of the next versions will contain a more robust dev info handling.
