### ISSUE TITLE
YieldTotal calculation invalid at end of day or when inverter restarts.

### ISSUE THREAD

**Issue by broth-itk** [tbnobody/OpenDTU#1258]
### What happened?

The YieldTotal value calculation is returning bad results when the inverter restarts, usually at end of day.

Synopsis: When I go to OpenDTU Live View in the evening, I often see only very low YieldTotal values.

Looking to the inverters, the 4-channel unit has often restarted due to low voltage. This causes the "last received value" of YieldTotal to be zero.

Not only the live dashboard is affected but the wrong values are getting published to MQTT as well.
Grafana will show disappointing values :)

### To Reproduce Bug

Just restart your inverter and observe the values.
YieldTotal will decrement.

### Expected Behavior

If inverter resurrects after shutdown for whatever reason, check if the last known value of YieldTotal is greater than the "new" value.
If smaller, do not update statistics.

At midnight, all daily stats values should be reset anyway.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.8.8

**Comment by broth-itk** [comment]
Proposed fix with https://github.com/tbnobody/OpenDTU/pull/1267

**Comment by OneCreek** [comment]
I think I have the same/similar issue...

thats the values I get via MQTT:
![Screenshot 2023-08-31 104522](https://github.com/tbnobody/OpenDTU/assets/107502675/f97af9ef-603a-4b08-b13d-ba6b4412766c)
![Screenshot 2023-08-31 104537](https://github.com/tbnobody/OpenDTU/assets/107502675/5abe5bea-d108-40a9-8b01-1ed985ac17bc)
![Screenshot 2023-08-31 104641](https://github.com/tbnobody/OpenDTU/assets/107502675/ba1611d1-ebb2-42e4-b685-db7bbccd8a63)
![Screenshot 2023-08-31 104652](https://github.com/tbnobody/OpenDTU/assets/107502675/cc155bba-a914-441e-b248-900737875955)
![Screenshot 2023-08-31 104733](https://github.com/tbnobody/OpenDTU/assets/107502675/4945c06b-14ca-4392-98f8-55a18a494192)

**Comment by broth-itk** [comment]
The fix currently only addresses the AC YieldTotal value for each inverter.

If the proposed fix has been checked and validated by others, it can be extended to work the same way for each individual inputs (channel/string/module) as well.
