### ISSUE TITLE
Live data disappeared 

### ISSUE THREAD

**Issue by gd35** [tbnobody/OpenDTU#129]
Today, I am not able to display the live data. However, data are still transmitted via MQTT. 

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/6339942/189528371-7a6e6d1c-e7c3-4ace-9cf5-ee9ac8d4aa24.png">

I will reboot the device this evening to see if live data can be displayed again for the next day.

Anyway, I am a happy user of OpenDTU. You did a very nice piece of software/hardware !

**Comment by tbnobody** [comment]
I am also facing this problem sometimes. There seems to be a issue with the WebSocket implementation of the ESPAsyncWebserver library. Are you able to see the output of the serial console without rebooting the ESP? Or can you maybe take a screenshot of the Info --> System view? The most interessting part would be the Memory Information and the Git Hash.

**Comment by gd35** [comment]
The device is connected to my Synology NAS through a USB hub. I am not sure I can connect to the serial console with the NAS. Herewith is the screenshot:

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/6339942/189532835-d3bf2809-a4e9-4d5e-ad6b-7b9455263a95.png">

Thanks for your help

**Comment by gd35** [comment]
This morning Live Data appeared again. Without doing anything.

**Comment by tbnobody** [comment]
Could you please double check what the Heap usage is now displaying? I would guess a value in the range of 110-120kbyte (instead of the 170).

**Comment by gd35** [comment]
This morning, the heap usage is:

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/6339942/189829392-ef62020a-29b6-4b27-a982-c3b9f81ee6e7.png">

**Comment by tbnobody** [comment]
@gd35 what browser are you using? A Chromium based on? (Chrome, Vivaldi etc?)

**Comment by gd35** [comment]
I use Firefox on a Mac. If it will happen again I will try another web browser. So far, it works.

**Comment by S-Przybylski** [comment]
From time to time i have the same issue. I use Android browser (samsung and chrome) and on PC Firefox.

**Comment by tbnobody** [comment]
I've changed the WebServer yesterday (using another fork). Let's see if this fixes the WebSocket issue.

**Comment by S-Przybylski** [comment]
I just tried to compile the todays version and got an error. Any hint?

````
Compiling .pio\build\d1 mini esp32\src\main.cpp.o
src/WebApi_ws_live.cpp: In member function 'void WebApiWsLiveClass::loop()':
src/WebApi_ws_live.cpp:60:9: error: 'AsyncWebSocketMessageBuffer' was not declared in this scope
         AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/WebApi_ws_live.cpp:60:9: note: suggested alternative: 'AsyncWebSocketMessage'
         AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         AsyncWebSocketMessage
src/WebApi_ws_live.cpp:60:38: error: 'buffer' was not declared in this scope
         AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
                                      ^~~~~~
src/WebApi_ws_live.cpp:60:38: note: suggested alternative: 'setbuffer'
         AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
                                      ^~~~~~
                                      setbuffer
src/WebApi_ws_live.cpp:60:51: error: 'class AsyncWebSocket' has no member named 'makeBuffer'
         AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
                                                   ^~~~~~~~~~
*** [.pio\build\d1 mini esp32\src\WebApi_ws_live.cpp.o] Error 1
````

**Comment by S-Przybylski** [comment]
Sorry my fault - again cloned / now works (Danke).

**Comment by tbnobody** [comment]
(Hint: `git pull` should load the current version of the code without the need of a complete clone)

**Comment by tbnobody** [comment]
I am closing this issue  as (at least for me) this issue didn't occour any more... feel free to open it again
