### ISSUE TITLE
Limit nonpersistent über MQTT überschreibt Limit persistent

### ISSUE THREAD

**Issue by sholvatealc** [tbnobody/OpenDTU#1304]
### What happened?

Unter Homeassistant ändere ich die Limits des Hoymiles HM-1500 um eine zu hohe Netzeinspeisung zu vermeiden.
Eine Änderung des Limit "nonpersistent" entweder als absolute oder relativ ändert aber auch das Limit "persistent".
Dies ist auch in den Logs von HA zu sehen.
![Screenshot 2023-09-03 143711](https://github.com/tbnobody/OpenDTU/assets/80471769/912394c6-43f1-440f-ac89-1102f224950c)

Das Limit nach unten setzen geht. Aber nicht mehr nach oben.

### To Reproduce Bug

In HA unter MQTT das Limit nonpersistant ändern sieht man wie sich der persistant mit ändert.
![Screenshot 2023-09-03 123834](https://github.com/tbnobody/OpenDTU/assets/80471769/f6d924f4-37f6-46c9-a857-75bedc444ff3)

### Expected Behavior

...............

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

e1c2817 von Lenhard wegen der Namensrichtlinie

**Comment by tbnobody** [comment]
> In HA unter MQTT das Limit nonpersistant ändern sieht man wie sich der persistant mit ändert.

Das ist exakt wie es funktionieren soll. Beim Auslesen des Wechselrichters kann nicht zwischen einem permanenten Limit oder einem nicht-permanenten Limit unterschieden werden. Der Wechselrichter gibt einfach nur ein Limit zurück.

**Comment by sholvatealc** [comment]
Danke für die Antwort.
Eine Frage noch.
Wenn ich von HA aus den nonperistant Wert ändere landet dieser aber im
flüchtigem Speicher?
Will nicht den Wechselrichter auf Dauer kaputt machen.

Grüße Markus

tbnobody ***@***.***> schrieb am So., 3. Sept. 2023, 19:51:

**Comment by tbnobody** [comment]
> Wenn ich von HA aus den nonperistant Wert ändere landet dieser aber im flüchtigem Speicher?

Korrekt

**Comment by sholvatealc** [comment]
Danke für die Info. Kann ich das als geschlossen markieren ? Oder Sie ? Weiß nicht wie das geht. .-))
