### ISSUE TITLE
new Events not viewable

### ISSUE THREAD

**Issue by locke981** [tbnobody/OpenDTU#131]
I have two HM-1500 (West, Ost) connected to the OpenDTU. I can see the red numbers for both of the inverters in case of new events.
If the numbers exceed a certain number of events they are not listed when trying to open them, it's just an empty list.  If there are only small number of events it works without any problem. I do not exactly know what is the breaking number. I must be someting greater than 3 or so. My impression is also it works more stable for the first inverter, I have seen on West more that 10 events listed without any problems. On the 2nd inverter Ost the list is always empty when there more than 3-4 events.
Stefan

![image](https://user-images.githubusercontent.com/47024716/189593462-b3481e4f-fc6d-4e67-a99b-18102404963b.png)

**Comment by tbnobody** [comment]
Could you please open the URL: `http://<OpenDTU IP>/api/eventlog/status` in a browser and post the output? I assume that maybe the buffer for the json output is to small and therefor the entries get cut off.

**Comment by locke981** [comment]
{"116180204736":{"count":13,"events":[{"message_id":1,"message":"Inverter start","start_time":22526,"end_time":22526},{"message_id":12,"message":"Unknown","start_time":27684,"end_time":27684},{"message_id":14,"message":"Unknown","start_time":27813,"end_time":27813},{"message_id":148,"message":"Grid disconnection","start_time":27814,"end_time":27900},{"message_id":12,"message":"Unknown","start_time":28024,"end_time":28024},{"message_id":12,"message":"Unknown","start_time":28116,"end_time":28116},{"message_id":12,"message":"Unknown","start_time":28147,"end_time":28147},{"message_id":12,"message":"Unknown","start_time":29115,"end_time":29115},{"message_id":12,"message":"Unknown","start_time":29279,"end_time":29279},{"message_id":12,"message":"Unknown","start_time":29403,"end_time":29403},{"message_id":12,"message":"Unknown"}]}}

**Comment by tbnobody** [comment]
If you have already compiled it yourself and if you want to test it you can try to replace the line:
https://github.com/tbnobody/OpenDTU/blob/85d08e0aba937860c1eb96808cab5fd439228244/src/WebApi_eventlog.cpp#L25
by the following:
`AsyncJsonResponse* response = new AsyncJsonResponse(false, 2048); `

This is only a workaround as for more (up to 10 supported inverters) inverters the 2048 will be also to small. I think I have to rework the API a bit.

**Comment by locke981** [comment]
Ok, I will test that and update here, thanks for the great support and your work!

**Comment by locke981** [comment]
Looks good now....I will post again here if there are any issues.
![image](https://user-images.githubusercontent.com/47024716/189620498-68023bd2-e39c-4905-a536-b60d90cac45b.png)

**Comment by stefan123t** [comment]
@locke981 Danke für die Meldung, ja es gibt noch ein paar Unbekannte / unknown Fehlermeldungen.
U.a. 
* 12 (https://github.com/tbnobody/OpenDTU/issues/1068),
* 14 (https://github.com/tbnobody/OpenDTU/issues/131),
* 12, 13, 14, 36,  (https://github.com/tbnobody/OpenDTU/issues/121),
* 12, 14, 36, 46, 47, 73 https://github.com/tbnobody/OpenDTU/discussions/590

Ich bin in den `assets/warn_code.json` der Hoymiles S-Miles Installer App fündig geworden. 🥳 

Hier mal die bisher aufgetretenen Fehler oder Warnings aus dem in #121 angehängten warn_code.json (GitHub versteht nur ZIP ?).

11: Grid voltage surge
12: Grid voltage sharp drop
13: Grid frequency mutation
14: Grid phase mutation
36: INV overvoltage or overcurrent
46: FB overvoltage
47: FB overcurrent
71: VW function enable
72: FW function enable
73: TW function enable

Es wird von @tbnobody im Rahmen von #121 in OpenDTU implementiert und daher kann dieses Issue als Duplicate geschlossen werden.
