### ISSUE TITLE
Set daily yield to zero at midnight does not send the new values via MQTT

### ISSUE THREAD

**Issue by Slummi** [tbnobody/OpenDTU#1335]
### What happened?

I tested the new feature to set the daily yield to zero at midnight. It works, but unfortunately the new daily yield values are not all sent via MQTT. Only the total daily yield of the DTU and the daily yield of the first inverter are sent via MQTT. The values of all other inverters are not sent.

### To Reproduce Bug

Activate the feature to set daily yield to zero at midnight for all inverters connected to the OpenDTU. Watch the daily yield MQTT topics at midnight.

### Expected Behavior

I would expect that all daily yield values are also sent via MQTT if they are set to zero at midnight.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.9.11

**Comment by tbnobody** [comment]
You are right! Will release a updated version this evening.
