### ISSUE TITLE
mqtt lifetime power at night

### ISSUE THREAD

**Issue by DocSnyd3r** [tbnobody/OpenDTU#1337]
### What happened?

Hi,
the power gauge in home assistant toggles between 0 and unavailable at night.
I would expect a longer lifetime of the 0 value.
This happens with the new setting zero runtime data.
Before that the gauge was unavailable the whole night.

### To Reproduce Bug

toggle inverter setting sent zero values at night

### Expected Behavior

power gauge stays at 0 and does not go to unavailable

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.9.11

**Comment by tbnobody** [comment]
Could you please try if the error  also occours with the latest version?

**Comment by DocSnyd3r** [comment]
I just updated and it stopped sending 0 values alltogether. The settings to do so were kept in tact.
A reboot did not bring it back.

**Comment by tbnobody** [comment]
Thats correct because it didn't receive any data yet i would assume? (night, inverter off etc?)

**Comment by DocSnyd3r** [comment]
Yes it is night I assumed it would figure this with sundown time and location but I never set a location. Also there is a setting assume not availability which i set to 3 but this does not trigger 0 values. Also a cosmetic thing is current power limit shown as 0 where unknown would be more accurate.
Will test tomorrow night again.
Funny enough after a home assistant reboot a single 0 value came through.

**Comment by tbnobody** [comment]
If no data was ever received since a reboot of the ESP, no data will be published. 

>  Also a cosmetic thing is current power limit shown as 0 where unknown would be more accurate.

It is a number.... a number can have numeric values.... unknown is no numeric value... unfortunatly....

**Comment by DocSnyd3r** [comment]
so after sundown today it worked thanks.

**Comment by tbnobody** [comment]
Then I would close this issue.
