### ISSUE TITLE
[Request] device hierarchy im Home Assistant

### ISSUE THREAD

**Issue by CFenner** [tbnobody/OpenDTU#1359]
### Is your feature request related to a problem? Please describe.

I have a microinverter with two solar panels and I get a lot of entities on the device view. 

### Describe the solution you'd like

I would like to make use of device hierarchies in home assistant to see dtu, inverter and strings separated. There is the ‘via_device’ field in the [device registry](https://developers.home-assistant.io/docs/device_registry_index/#device-properties) which is used for this relation. In the end it could look like here for NAS, volumes and disks in my Synology.

![IMG_3485](https://github.com/tbnobody/OpenDTU/assets/9592452/b701f4a5-d8c2-421c-864b-efd1b588c081)
![IMG_3483](https://github.com/tbnobody/OpenDTU/assets/9592452/db2bc7f3-9974-4226-801d-cccc07e35de8)

**Comment by CFenner** [comment]
First very basic approach..

https://github.com/CFenner/OpenDTU/pull/1/files

Inverter View:
<img width="592" alt="Bildschirmfoto 2023-09-20 um 10 37 10" src="https://github.com/tbnobody/OpenDTU/assets/9592452/5abe7aa0-8957-4bd2-bd62-889f1ecfc112">

AC View:
<img width="583" alt="Bildschirmfoto 2023-09-20 um 10 37 22" src="https://github.com/tbnobody/OpenDTU/assets/9592452/a0001ccc-8ead-4eba-98ea-dc627d56ad21">

String View:
<img width="582" alt="Bildschirmfoto 2023-09-20 um 10 37 30" src="https://github.com/tbnobody/OpenDTU/assets/9592452/64b6cd64-e2c4-4711-89a0-0d8213c32946">

**Comment by tbnobody** [comment]
Implemented in 84248ec9b65e18a224a77d02d273bc0fb73548f0

**Comment by CFenner** [comment]
What about carving out the strings as well?
