### ISSUE TITLE
Wlan AP ständig on

### ISSUE THREAD

**Issue by apreller64** [tbnobody/OpenDTU#1364]
### What happened?

Bei Verwendung von Wired Ethernet (Olimex ESP32-POE) bleibt das WLAN im AP Modus ständig aktiv. Die SSID "OpenDTU-****** wird gesendet und unter Info -> Netzwerk steht bei "WLAN-Informationen Status aktiv". 

### To Reproduce Bug

Keine Wlan Konfiguration,  Anschluss per LAN

### Expected Behavior

Ich hatte erwartet das die OpenDTU den AP Modus nach x Minuten deaktiviert. Das ist aus Sicherheitsgründen wünschenswert. 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

V23.9.18

**Comment by tbnobody** [comment]
What do you see on the serial console? There should be something like 
`Admin AP remaining seconds:`
which counts the seconds until the AP gets disabled... what happens if your count down reaches its target?

**Comment by apreller64** [comment]
The DTU is installed in the roof box, the serial port is not routed to the outside. I will expand the DTU this weekend and report back.

**Comment by tbnobody** [comment]
Was ist denn hier deine Einstellung?
![image](https://github.com/tbnobody/OpenDTU/assets/1753222/b36f4224-6ef2-4f52-9ea9-e2f3d750bf83)

**Comment by apreller64** [comment]
![grafik](https://github.com/tbnobody/OpenDTU/assets/143283449/d43708dc-b2d7-4a2d-81f2-796ad65c12e5)

**Comment by tbnobody** [comment]
Due to the fact that there was no further response, I assume we can close this issue. Feel free to reopen it if it persists.
