### ISSUE TITLE
MQTT Value jumping randomly in Home Assistant

### ISSUE THREAD

**Issue by koch86** [tbnobody/OpenDTU#1366]
### What happened?

Using OpenDTU version 23.8.28
Almost every day I need to do corrections in the Home Assistant statistics, since there is one or two invalid values.
This looks like this:

![image](https://github.com/tbnobody/OpenDTU/assets/3626543/4bb602c9-ca35-4225-8646-dc62bfd9147a)

Value of the jump is:
![image](https://github.com/tbnobody/OpenDTU/assets/3626543/422e4788-0184-40e2-9a94-4826e1e4c076)

Same applies for the Yield Total with even higher values:
![image](https://github.com/tbnobody/OpenDTU/assets/3626543/80bf7938-687f-4735-a33e-9d3637041e58)

### To Reproduce Bug

Happens randomly but almost every day at different times

### Expected Behavior

No jumps in the value

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

23.8.28

**Comment by tbnobody** [comment]
To determine if this value is coming directly from the inverter or is somehow wrong interpreted by OpenDTU it is unfortunately required to have a serial log of the time period when the error occurs.

**Comment by koch86** [comment]
Ok, will try to record one of the moments.
Might take a while since the issue happens sporadically at any time of the day

Is there any better way to obtain such a log than having a PC attached to the ESP that runs a serial monitor?

**Comment by tbnobody** [comment]
> Is there any better way to obtain such a log than having a PC attached to the ESP that runs a serial monitor?

Unfortunately not... That's the most reliable way (to also capture exceptions from the core etc.)

**Comment by jstammi** [comment]
There is also wscat, that you can attach to the webapp monitor

tbnobody ***@***.***> schrieb am Do., 21. Sept. 2023, 15:32:

**Comment by koch86** [comment]
Thanks for your assistance! Decided to switch to other power measurement in Home Assistant.
