### ISSUE TITLE
Unknown model - HMS-900

### ISSUE THREAD

**Issue by aapee73** [tbnobody/OpenDTU#1392]
### What happened?

"Show Inverter Info" says: "Unknown model! Please report the "Hardware Part Number" and model"

![image](https://github.com/tbnobody/OpenDTU/assets/69870968/19f2605e-3353-4abd-b221-6c20f1bf508a)

### To Reproduce Bug

Connect a Hoymiles HMS-900

### Expected Behavior

Recognize hardware part number 270618883

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.9.18

**Comment by MasterMeyer** [comment]
same for HMS-1000
<img width="776" alt="Screenshot 2023-10-09 at 14 42 01" src="https://github.com/tbnobody/OpenDTU/assets/4363772/caae756f-c5a5-4cc9-9961-d5294611d164">
