### ISSUE TITLE
Webserver Crash in NTP wenn verbunden über AP

### ISSUE THREAD

**Issue by andreash-esp** [tbnobody/OpenDTU#143]
Hi,

wenn man über den AP verbunden ist, führt ein Aufruf der von Info/NTP zum Crash.
Das passiert scheinbar nur, wenn noch keine Wifi Config hinterlegt ist. War man mal verbunden, tritt der Reboot auch bei einer Verbindung über den AP nicht auf. 

Andreas

**Comment by tbnobody** [comment]
Thank you.... Fixed with 950b211fd5eba039582dfb0f7a562e53b471430b
