### ISSUE TITLE
string values != 0 at night

### ISSUE THREAD

**Issue by niwa2** [tbnobody/OpenDTU#1431]
### What happened?

When my inverter goes offline at night, the values for power, voltage, current and irradiation of the strings are keept at the last value.

It is at least confusing, that there is still some DC power, voltage and current beeing shown even though it is pitch black outside.

### To Reproduce Bug

Wait for the sun to go down and the inverter to go offline.
Then have a look at the power, voltage, current and irradiation values of each string of the offline inverter.

### Expected Behavior

Since the inverter goes offline because there is no sun, i would expect those values to be set to 0.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.9.18

**Comment by tbnobody** [comment]
Then just activate the relevant property:

![image](https://github.com/tbnobody/OpenDTU/assets/1753222/cf4fd6ed-8368-48e2-80a8-6a754741e83f)
