### ISSUE TITLE
OpenDtu update

### ISSUE THREAD

**Issue by Munic-KW** [tbnobody/OpenDTU#1439]
### What happened?

Since the new update Oktober 19th.  my OpenDtu loses connection. After reboot it works for about 30 min.

### To Reproduce Bug

loses connection

### Expected Behavior

keep up

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

latest

**Comment by Solarteur** [comment]
As I see it, there is no update from October 19, 2023???

**Comment by Matthy1810** [comment]
Try a different/better power supply and/or USB/power cable. I experienced a similar issue and a different (longer) cable fixed it.
