### ISSUE TITLE
Kein Live Data über AP

### ISSUE THREAD

**Issue by andreash-esp** [tbnobody/OpenDTU#144]
Hi,

Live Data wird nicht angezeigt, wenn man initial über den AP verbunden ist. 
Wurde mal ein Wifi angelegt, funktioniert es auch bei Verbindung über den AP.

Andreas

**Comment by tbnobody** [comment]
Das ist ganz logisch. Ohne eingetragenes wlan kein Zugriff zu einem NTP Server. Ohne Zugriff zu einem NTP Server keine Uhrzeit. Ohne Uhrzeit keine Anfragen an den wechselrichter da in jedem Paket die Uhrzeit enthalten ist.

**Comment by lumapu** [comment]
@tbnobody du kannst dich für diesen Betriebsmodus einfach eine 'Fake Zeit' nehmen, zB die des Firmware complies.
In der Ahoy Version wird aktuell einfach 1970 verwendet

**Comment by stefan123t** [comment]
Ich fände für diesen Fall AP-only mode eine Option zum manuellen setzen von Datum & Zeit sinnvoll.
