### ISSUE TITLE
[Request] Trim whitespaces before and after login username

### ISSUE THREAD

**Issue by mathieucarbou** [tbnobody/OpenDTU#1456]
### Is your feature request related to a problem? Please describe.

Mobile autocompletion usually puts a whitespace after the completed word. 
When that happens, it is hard to spot, and the login name becomes `admin ` instead of `admin`. 
So the connection is refused.

### Describe the solution you'd like

Trim login names

### Describe alternatives you've considered

- Either trim whisteapces
- Either prevent autocompletion from being allowed for the username field

**Comment by flooxo** [comment]
In my opinion, the best way to solve this issue is to trim the whitespaces, since some browsers do ignore the `autocomplete="off"` attribute. Also the user experience is better by auto-filling the form.
