### ISSUE TITLE
Power not set to 0 when not reachable at EOD

### ISSUE THREAD

**Issue by mhin76** [tbnobody/OpenDTU#1488]
### What happened?

At EOD when my inverter is getting offline OpenDTU still shows the last received power. I have set the "Zero runtime data". That works during the day when one of the inverter is too far away, but at EOD that is not working.

![image](https://github.com/tbnobody/OpenDTU/assets/49210075/d14702b0-d4a6-4f09-8412-54bbc6e46cf9)

### To Reproduce Bug

Set the flag "Zero runtime data", wait until EOD when Inverter is offline.

### Expected Behavior

to set Power to 0.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.9.18

### Anything else?

I am using HM-800 and HM-1500 inverter.
Using a pre-compiled binary from Diamex (shop that provides also the hardware).

**Comment by tbnobody** [comment]
Have you disabled the polling at night?

**Comment by mhin76** [comment]
yes that is turned off. ah, you mean maybe DTU puts itself to night time before my inverter had a chance to time out and therefore the zero runtime data will never be triggered?

**Comment by tbnobody** [comment]
> you mean maybe DTU puts itself to night time before my inverter had a chance to time out and therefore the zero runtime data will never be triggered?

That would be my guess yes. I will correct change the behavior of setting the runtime data to zero. currently it only happens on a active inverter (polling enabled). But as we see in your case, it might happen that the night time can occour before the inverter gets unreachable.

**Comment by mhin76** [comment]
Perfect guess!! Now all power are set to zero after activating polling at night. Thanks for that hint!
