### ISSUE TITLE
[Request] Set voltage and current for inverter string to 0 over night

### ISSUE THREAD

**Issue by jfrede** [tbnobody/OpenDTU#1510]
### Is your feature request related to a problem? Please describe.

At the moment OpenDTU shows the last read current and voltage for the whole night. 

### Describe the solution you'd like

It would be nice if we could set this to 0 when we are sure the inverter is offline.

**Comment by tbnobody** [comment]
This is already implemented.
Just enable the setting "Zero runtime data"

**Comment by jfrede** [comment]
Sorry didn't see that. It was well hidden. :-)
