### ISSUE TITLE
+ new mqtt topic [serial]/status/rssi

### ISSUE THREAD

**Issue by hamstie** [tbnobody/OpenDTU#1535]
### Describe the solution you'd like

it would be nice to have the rssi value of the dtu (not wifi)

**Comment by SuperNinja73** [comment]
as @tbnobody said : "Inverter RSSI is (not yet) published. (One reason is, that the nRF modules don't provide a detailed RSSI information)"

but I have an HMS1000 so a cmt2300A and it seems to me that RSSI is supported as i saw here  :
https://github.com/lumapu/ahoy/wiki/RF-Module-CMT2300A---E49-900M20S

**Comment by SuperNinja73** [comment]
we can imagine a RSSI triangle like this : 
![image](https://github.com/tbnobody/OpenDTU/assets/53425740/4eac67dd-9c17-4280-b69b-abdf7b41cadd)

**Comment by tbnobody** [comment]
Implemented in edfe06e31eae286fbb88da69e9b65420cfa8628a
