### ISSUE TITLE
Selbstständig alles gelöscht

### ISSUE THREAD

**Issue by h2okopfmt** [tbnobody/OpenDTU#1537]
### What happened?

Bei der Täglichen Kontrolle ist mir aufgefallen das die DTU Ihre Werte, Gesamtleistung und Gesamtertrag Heute, selbständig auf 0 gesetzt hat.

### To Reproduce Bug

Leider kann ich es nicht nachvollziehen 

### Expected Behavior

Es darf sich nicht zurücksetzten.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.11.16

**Comment by DPO99** [comment]
Die DTU kann 100 mal neu starten und das ist egal. Die Werte kommen vom WR. Ich gehe davon aus, dass bei dem aktuell doch sehr schlechten Wetter der HM einfach ausgegangen ist. Und wenn das passiert, dann werden auch die Werte zurück gesetzt (kam hier schon mehrfach vor).

**Comment by tbnobody** [comment]
As mentioned by @mroenne2022 and @DPO99 it's not possible to "delete" everything. This happens in case of a powercycle or if the inverter reboots. The ESP itself does not even store the values permanently.
