### ISSUE TITLE
HM-800 verliert Power Limit 

### ISSUE THREAD

**Issue by MichaelHH71** [tbnobody/OpenDTU#1538]
### What happened?

Das setzten der Leistungsbegrenzung wird kurz korrekt angezeigt. 5sec. später ist dieser Wert allerdings schon wieder verändert.
Z.B. Limit 150W permanent. -> beim nächsten Update im Dashboard wird dies korrekt angezeigt. Weitere 5sec. später sind es dann z.B 321W. Dieser Wert ändert sich immer wieder…

### To Reproduce Bug

Siehe oben

### Expected Behavior

Leistungbegrenzung sollte bestehen bleiben.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.11.16

**Comment by stefan123t** [comment]
Ich glaube Du solltest Dein Problem mit einem Serial Log untermauern. Anderenfalls kann das wahrscheinlich niemand vollständig nachvollziehen.

Siehe https://tbnobody.github.io/OpenDTU-docs/firmware/howto/serial_console/

**Comment by tbnobody** [comment]
Closed due to inactivity. Feel free to open a new issue if the problem persists
