### ISSUE TITLE
Firmwar update Probleme

### ISSUE THREAD

**Issue by WegeDave** [tbnobody/OpenDTU#1555]
### What happened?

Wenn ich probiere ein Firmware update zu mache nkommt immer dieser fehler siehe bild
![2023-12-08 20_12_05-OpenDTU und 10 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/tbnobody/OpenDTU/assets/118565482/1afe12fc-8f93-4ae4-8be9-a2a278e9b46c)

### To Reproduce Bug

also bei mir ist es wenn ich probiere ein Firmware update zu machen

### Expected Behavior

![2023-12-08 20_14_38-OpenDTU und 10 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/tbnobody/OpenDTU/assets/118565482/3abf1658-4aca-4847-903c-f49373a9b2fa)
![2023-12-08 20_14_52-OpenDTU und 10 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/tbnobody/OpenDTU/assets/118565482/95bfd28e-5bff-4efc-a4ae-03d98d1c779c)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

4f0dfe4

**Comment by tbnobody** [comment]
Duplicate of #1501
