### ISSUE TITLE
Unbekanntes Modell

### ISSUE THREAD

**Issue by Karli67** [tbnobody/OpenDTU#1567]
### What happened?

Unbekanntes Modell! Bitte melden Sie die "Hardware Teilenummer" und das Modell als Problem.

HMS-2000-4T
200051441TM.SBRO.DE.HM

### To Reproduce Bug

Modell wurde nicht erkannt 

### Expected Behavior

Wurde nicht erkannt

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

V23.11.16

**Comment by tbnobody** [comment]
Bitte einen Screenshot des kompletten Dialogs einfügen.

**Comment by Karli67** [comment]
![IMG_0798](https://github.com/tbnobody/OpenDTU/assets/153909608/2476d226-5633-458b-9d2d-2fdbc3cd41b2)

**Comment by Karli67** [comment]
Ist das so OK?

**Comment by tbnobody** [comment]
Welche OpenDTU Version verwendest du? Frage nur, weil die Hardwareteilenummer eigentlich zu kurz aussieht. War der Meinung ich hatte das in einer Version schonmal abgefangen.

**Comment by Karli67** [comment]
![IMG_0799](https://github.com/tbnobody/OpenDTU/assets/153909608/8aa07a94-c066-4b9a-9810-b05c97278458)

**Comment by Karli67** [comment]
Ich habe den Wechselrichter noch nicht am Netz angeschlossen.

**Comment by Karli67** [comment]
Nach dem Update und dem Anschluss an das Netz wurde der Wechselrichter erkannt.
Danke
