### ISSUE TITLE
Datums- und IP Anzeige im Display Pluszeichen statt Punkt

### ISSUE THREAD

**Issue by jblond4711** [tbnobody/OpenDTU#1572]
### What happened?

Auf meinem 2.42“ Display werden Pluszeichen beim Datum und der IP Adresse anstelle von Punkten angezeigt.

### To Reproduce Bug

Aufs Display gucken

### Expected Behavior

OpenDTU installiert

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.12.17

**Comment by tbnobody** [comment]
What display are you using? Not just the size, the complete name with it's controller.

**Comment by jblond4711** [comment]
Ich hoffe ein Bild reicht?

![IMG_0206](https://github.com/tbnobody/OpenDTU/assets/17287119/552387c1-6992-4254-928c-57b82f0f550c)

**Comment by tbnobody** [comment]
Currently the following i2c displays are supported:
* 2 = SSD1306
* 3 = SH1106

You are using a SSD1309...

**Comment by tbnobody** [comment]
If you used the generic_esp32 binary in the past you can try to flash the attached firmware. Make sure to change to the `display.type` to 4 in your device profile.

[firmware.zip](https://github.com/tbnobody/OpenDTU/files/13703914/firmware.zip)

**Comment by jblond4711** [comment]
Ich verwende die opendtu-generic.bin, wenn ich die generic_esp32 flashe gibt es eine Fehlermeldung bei dem Versionsstand.
Müsste ich die generic_esp32 am PC komplett neu flashen?
Kann ich den Display Type 4 auch in der generic.bin einstellen?

**Comment by jblond4711** [comment]
Gut, dann gucke ich morgen nochmal genauer da ich in den Einstellungen kein Display Typ 4 gefunden habe.
Reicht auch das OTA flashen?
Ich war nämlich schon dabei nochmal komplett neu zu flashen aber da es dann dunkel war und ich dann ja nichts mehr auf dem Display gesehen hätte.

**Comment by tbnobody** [comment]
OTA flashen und im Device Profile (das pin_mapping.json) den Display Typ ändern.

**Comment by jblond4711** [comment]
Habe jetzt alles so eingestellt wie von dir geschrieben.
Leider sind die Punkte vom Datum und der IP auf dem Display weiterhin Pluszeichen. Es wird mir eine neue Firmware angezeigt soll ich die mal flashen oder weiterhin die von oben verwenden?

**Comment by tbnobody** [comment]
> Es wird mir eine neue Firmware angezeigt soll ich die mal flashen oder weiterhin die von oben verwenden?

Die offizielle Firmware kann keinen DisplayType 4. (Den hattest du schon gesetzt oder?) Kann man auch unter Einstellungen --> Hardware kontrollieren. Wenn dann alles korrekt ist, aber die Anzeige immer noch falsch ist würde ich hier noch eine andere Firmware einstellen. Es gibt dummerweise 2 Treiber für das von dir beschriebene Display.

**Comment by jblond4711** [comment]
Den DisplayType habe ich auf 4 gesetzt.
Dann las uns (mich) mal bitte noch die Firmware mit dem anderen Treiber testen.
![IMG_0209](https://github.com/tbnobody/OpenDTU/assets/17287119/45f5f5b1-c8e3-4b2b-a46c-7ad613ad9e24)

**Comment by tbnobody** [comment]
The attached file uses U8G2_SSD1309_128X64_NONAME2_F_HW_I2C

If this  does not either it's maybe a issue in the U8G2 Library.

[firmware.zip](https://github.com/tbnobody/OpenDTU/files/13720257/firmware.zip)

**Comment by huste511** [comment]
Wenn Du so adhoc alternative Versionen bereitstellen kannst, könnte man dann nicht generell mehr Displays unterstützen?

Hatte mir in den letzten Monaten aus div. Quellen große und kleine OLEDs in verschiedenen Farben bestellt.
Bei allen habe ich die Plus-Zeichen. - Ich dachte schon da wäre normal und gewollt.
Auch im Netz findet man viele Bilder in der Variante.

Displays sind u.a. diese hier;
https://de.aliexpress.com/item/1005003484018034.html
https://de.aliexpress.com/item/1005003093058462.html

**Comment by jblond4711** [comment]
Schade, mit der von Dir zuletzt bereitgestellten Firmware sind immer noch die Pluszeichen da.
Würde es eventuell was ändern das Datum und die IP Anzeige etwas zu vergrößern? Platz ist auf dem großen Display ja noch vorhanden.
Mich wundert nur das bei der Uhrzeit der Doppelpunkt richtig angezeigt.

**Comment by tbnobody** [comment]
> Wenn Du so adhoc alternative Versionen bereitstellen kannst, könnte man dann nicht generell mehr Displays unterstützen?

Man muss es  halt selber kompilieren... können auch die wenigsten.

**Comment by tbnobody** [comment]
> Würde es eventuell was ändern das Datum und die IP Anzeige etwas zu vergrößern? Platz ist auf dem großen Display ja noch vorhanden.

Auf dem 0.96" display ist da fast kein platz

**Comment by jblond4711** [comment]
Gäbe es die Möglichkeit das Displayabhängig zu machen?  Also per Option einzustellen welche Displaygröße man verwendet?

**Comment by huste511** [comment]
Die div. Displaygrößen (0,96 ; 1,3 ; 2,42 usw.)  haben doch alle die gleiche Auflösung von 128x64 Pixel.
Was sollte das also bewirken?

**Comment by ampere-dieter** [comment]
Habe auch ein 2,42" Display verwendet. Geht sowohl mit der Standard firmware als Type#2 (SSD1306) als auch mit der firmware von hier als Type#4 (SSD1309) Display.  Man muss aber die seitlichen Pins benutzen, bei den oberen Pins sind SDA und SCL nicht angeschlossen. Hier der Link:  https://de.aliexpress.com/item/1005005241315177.html?spm=a2g0o.detail.0.0.51f813b8LyBDGH&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40000.327270.0&scm_id=1007.40000.327270.0&scm-url=1007.40000.327270.0&pvid=7e0c04e9-f1eb-4562-a43f-5e2db23c36e8&_t=gps-id:pcDet

![Display 2 42'' mit SSD1309](https://github.com/tbnobody/OpenDTU/assets/30777234/9429848d-bb66-4016-91b9-46293a8d9052)

Frohe Weihnacht, Dieter

**Comment by huste511** [comment]
Bei Type 4 hat Du Punkte oder Pluszeichen? Doppelpunkte sehen normals aus?
Bei den Displays kommt es nicht nur drauf an wo die Pins sind, sondern wie Lötbrücken etc. sitzen. Viele kann man ändern.

btw: Hatte man versucht Bilder von Displays mit Punkten in Google zu finden. >95% sind wohl aber mit Pluszeichen unterwegs ... ;-)

**Comment by ampere-dieter** [comment]
Hallo huste511,


![1703532349763](https://github.com/tbnobody/OpenDTU/assets/30777234/b5fd0fe3-28fa-449b-807b-2df864087d43)

Bei beiden firmware.zip Versionen hier in Fred wird bei meinem Display bei der kleinen Schriftgröße (Datum, Zeit) der Dezimalpunkt als Pluszeichen dargestellt und nicht als Punkt. Das gilt für Konfiguration als Type_2 als auch bei Type_4 Display. Stört mich aber nicht. Da das gleiche auch bei der default firmware auftritt, d.h. Mini-Pluszeichen statt Punkt, bin ich wieder auf die default firmware zurückgegangen. Meine 4 Panels liegen sowieso noch in der Hütte und müssen noch montiert werden. Mit einem  einstellbaren DC-Spannungswandler hab ich ein Panel am Wechselrichter simuliert und ihn eingerichtet. Ging problemlos. Z. Zt. bin ich am grübeln wie ich eine Nulleinspeisung hinkriege. Geht das mit OpenDTU oder muß man OpenDTU-onBattery verwenden? Am digitalen Zähler hängt eine Hichi Lesekopf. Mein alter analoger Zähler wurde leider ausgewechselt....
Dieter

**Comment by tbnobody** [comment]
I've just doublechecked on my display. Yes, these small dots look like plus signs. But that is related to the font and not a issue. On a small display you just don't see the plus sign as good as on a larger one. But the font cannot be changed as the resolution of the displays is the same. Therefor I am going to close this issue as it is not really a issue.
