### ISSUE TITLE
OpenDTU acquires LAN IP-address via DHCP although DHCP is set to off and static IP-address is defined

### ISSUE THREAD

**Issue by nakott** [tbnobody/OpenDTU#1579]
### What happened?

I'm using a OpenDTU with LAN-connector. All worked well with opendtu-generic.bin 231116. I updated to 231217.
OpenDTU acquires LAN IP-address via DHCP although DHCP is set to off and static IP-address is defined. 

I reverted back to 231116 and all is good again. After installing 231217, DHCP=off is ignored again. 

### To Reproduce Bug

Turn off DHCP, define static IP configuration, restart OpenDTU and check Info->Network section Network Interface (Ethernet)

### Expected Behavior

Static IP-address defined in Settings->Network should be used and shown under Info->Network

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

fbc39ef

### Anything else?

I'm using this OpenDTU
https://www.derdtushop.de/shop?store-page=Open-DTU-OpenDTU-fur-Hoymiles-HM-Reihe-Lan-Plug-%26-Play-ready-mit-Gehause-p580008627

Here, I defined the static IP to 192.168.178.220

![Set-Net](https://github.com/tbnobody/OpenDTU/assets/22239367/ccc938e8-6c24-44bb-9b68-7288aa4c4f70)

And here is, what the OpenDTU actually has: 192.168.178.185. My Fritzbox uses DHCP for addresses between 20 and 200.

![Sys-Net](https://github.com/tbnobody/OpenDTU/assets/22239367/90fc5611-b5f0-48b4-8055-981f8897009a)

**Comment by tbnobody** [comment]
Found the issue. will release a new version in the evening.

**Comment by nakott** [comment]
Works perfectly. Many Thanks :-)
