### ISSUE TITLE
Firmware Update only possible after reboot

### ISSUE THREAD

**Issue by de-sascha** [tbnobody/OpenDTU#1588]
### What happened?

If OPENDTU running some time and I need to update the firmware file the WEB IF not update. The percentage status bar went fast from 0-100% without apply the update. Workaround is reboot OpenDTU and then the Update can be apply. 

### To Reproduce Bug

Because after reboot I can apply the update. Assuming may this s an issue on the uptime. Because after reboot the firmware.bin can be uploaded. 

### Expected Behavior

May be fix the issue no reboot is required. 

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

v23.12.24

**Comment by tm-107** [comment]
Can't reproduce it here, firmware update works fine.

**Comment by MetaChuh** [comment]
@de-sascha 

is this issue solved for you too with v24.2.16 and can be closed ?

**Comment by de-sascha** [comment]
Yes seams fixed in the meantime
