### ISSUE TITLE
Firmware Update  v23.12.24 cannot be updated 

### ISSUE THREAD

**Issue by wesseli01** [tbnobody/OpenDTU#1592]
### What happened?

After the upload of the new FW Version  [opendtu-generic_esp32.bin](https://github.com/tbnobody/OpenDTU/releases/download/v23.12.24/opendtu-generic_esp32.bin) and the system was restarted - the new version is not active

### To Reproduce Bug

Upload 

### Expected Behavior

FW Version  [opendtu-generic_esp32.bin](https://github.com/tbnobody/OpenDTU/releases/download/v23.12.24/opendtu-generic_esp32.bin)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

OpenDTU-48FB10

### Relevant log/trace output

```Shell
FW Version  [opendtu-generic_esp32.bin](https://github.com/tbnobody/OpenDTU/releases/download/v23.12.24/opendtu-generic_esp32.bin)
```

**Comment by tbnobody** [comment]
Please provide a screenshot of Info --> System --> Memory Information

**Comment by maltejahn** [comment]
Hi, probably the same issue. I already tried it 3 times to Update the Firmware. But it still says that a new firmware is available. I used the opendtu-generic_esp32.bin v23.12.24 
![Screenshot_20231229_180449_Firefox](https://github.com/tbnobody/OpenDTU/assets/21693654/5a2e1110-3652-479f-aef4-29c421d5a7a2)

But.. with the v23.12.28 it works again

**Comment by Juergen2453** [comment]
Bei mir läuft die Version schon über einen Tag.

<img width="580" alt="image" src="https://github.com/tbnobody/OpenDTU/assets/116970574/02b5ba66-fa98-4b17-a369-92b578bb2905">

**Comment by wesseli01** [comment]
I have updated with the new version - v23.12.28. It is working now. Thank you for the fixing.

**Comment by wesseli01** [comment]
The topic can be closed now.
