### ISSUE TITLE
After restart from mqtt opendtu does not send data to mqtt, restart is needet

### ISSUE THREAD

**Issue by svalcken** [tbnobody/OpenDTU#1629]
### What happened?

mqtt server was rebootet. After them, opendtu does not reconnect and send data.

### To Reproduce Bug

Restart mqtt server and than data will not sendto mqtt.

### Expected Behavior

automatical reconnect to mqtt and send of data to mqtt.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.12.28

**Comment by tbnobody** [comment]
What do you see on the console if you restart the broker? What broker are you using? Please provide a screenshot of  **Info**  --> **MQTT**

**Comment by bombjack7000** [comment]
I have that on OpenDTU v23.12.24, too, after restarting Home Assistant. I am using the standard MQTT server in Home Assistant (core-mosquitto).
Everything back to normal after restart of OpenDTU.
![grafik](https://github.com/tbnobody/OpenDTU/assets/75941026/06c0d0ee-a117-4de8-b76d-a454ace8f364)

**Comment by tbnobody** [comment]
What is the mqtt status (info --> mqtt) if you restart the broker and the client does not work proberly?

**Comment by bombjack7000** [comment]
Whoa,
OpenDTU is connected, MQTT Explorer also shows the MQTT packets coming in.
The problem seems to be on the Home Assistant side!

I better report that there.

Thank you for your quick reply.
OpenDTU is a great project! 👍 👍 👍 

![grafik](https://github.com/tbnobody/OpenDTU/assets/75941026/6fb91d6c-2a9d-4404-84f3-f31d8aaa0ff6)

**Comment by srett** [comment]
I just had the same issue. **Info -> MQTT** showed **Status: Enabled**, but **Connection Status: Disconnected**. **Info -> Console** only showed inverter communication, nothing about MQTT. Simply saving the MQTT settings again without changing anything made it connect to mosquitto again. So it appears connection retry is broken under some circumstances. I'm on 24.1.26.
