### ISSUE TITLE
TSUN TSOL M1600 Support

### ISSUE THREAD

**Issue by tobox** [tbnobody/OpenDTU#163]
Weiß jemand, ob der TSUN TSOL M1600 unterstützt wird? Scheint von der "Baureihe" her sehr ähnlich zu sein wie der M800 bzw. die noch kleineren...

**Comment by tbnobody** [comment]
Beginnt deine Seriennummer mit 11? Das wäre ein gutes Anzeichen das es klappen könnte. Ich schreibe "könnte" weil es wohl verschiedene Firmware Versionen gibt. Die Einen funktionieren, die Anderen nicht.

**Comment by tobox** [comment]
Ja, Seriennummer beginnt mit 11617... Bin gespannt. WR ist da, ESP32 auch, Funkplatine im Zulauf.

**Comment by tbnobody** [comment]
Würde mich dann über eine Rückkmeldung freuen ob es klappt oder nicht. Dann könnte ich den Inverter auch noch in die Readme.md aufnehmen.

**Comment by tobox** [comment]
Ich habe den Wechselrichter mal temporär mit AC versorgt ohne das Solarmodule dran sind. Die OpenDTU habe ich auch nur mit Jumperkabeln zusammengesteckt. Aber ich befürchte fast, es funktioniert - oder was meint ihr? Ich habe nur die Seriennummer eingegeben, die Anzahl der Module hat er dadurch scheinbar schon selber rausgefunden.

![Screenshot 2022-09-28 at 21-07-18 opendtu](https://user-images.githubusercontent.com/4719666/192869169-89dcb04f-98f4-47db-aad5-60da6c7b3bb4.png)

**Comment by tobox** [comment]
Hier noch ein paar Nicht-Infos:
![Screenshot_20220928_210654](https://user-images.githubusercontent.com/4719666/192869784-69dc8be8-f78d-4c8b-a72d-cb2b1ecb471c.png)

**Comment by tbnobody** [comment]
Hm ne. Also die Anzahl der Module bekommt er über die Seriennummer raus. Nur mit AC aktiviert den Inverter nicht. Dieser wird NUR von der DC Seite her mit Strom versorgt. Also ohne Solarmodule ist noch alles offen :-)

**Comment by tobox** [comment]
Mist... Dann muss ich den Aufbau wohl morgen Abend mal nach draußen verlegen... Sollte ein PV-Modul reichen? Die stehen nämlich noch im Schuppen...

**Comment by tbnobody** [comment]
Mit einem Modul sollte er schon aktiv werden ja. Ich bin mir jetzt aber nicht 100% sicher ob man die AC Seite benötigt.

**Comment by tobox** [comment]
Kannst einen Haken dran machen! Läuft! Vielen Dank für das tolle Projekt!


![Screenshot 2022-09-29 at 08-36-51 opendtu](https://user-images.githubusercontent.com/4719666/192957161-b1b0626b-7477-44c1-a68c-57545c421a3d.png)

**Comment by tobox** [comment]
Falls das hier noch hilft:

![Screenshot 2022-09-29 at 08-38-58 opendtu](https://user-images.githubusercontent.com/4719666/192957516-404a0616-debf-490e-b241-396359a63fdf.png)
