### ISSUE TITLE
v24.1.14 : Unable to change CMT2300A frequency in DTU Settings

### ISSUE THREAD

**Issue by SuperNinja73** [tbnobody/OpenDTU#1662]
### What happened?

![image](https://github.com/tbnobody/OpenDTU/assets/53425740/5ed08ca8-d4f6-4a1d-b901-46aaca6c4508)
**1/ "the selected frequency (865MHz by default) is not authorized in the EU". OK, I will put the frequency known in France:**
![image](https://github.com/tbnobody/OpenDTU/assets/53425740/05844e17-5446-4d5f-bbb9-ab4c1ea7d574)

![image](https://github.com/tbnobody/OpenDTU/assets/53425740/e14f60a1-e680-4d7f-ad71-09d0d2a3f057)
**2/ I validate 868MHz and "868MHz is not between 860 and 923" so it doesn't work.**

### To Reproduce Bug

open DTU settings and try to change DTU CMT2300A Frequency

### Expected Behavior

868MHz must be accepted because it is between 860 and 923MHz

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.1.14

**Comment by tbnobody** [comment]
This is exactly the same issue as #1651
