### ISSUE TITLE
Cannot update OpenDTU from 23.10.9 to 24.1.4.

### ISSUE THREAD

**Issue by micha1221** [tbnobody/OpenDTU#1663]
### What happened?

Hi, I tried to change the firmware on my esp32 OpenDTU, but after uploading the firmware, I got a "bad http request" error.

### To Reproduce Bug

I tried it very often with the "master" and the 24.1.4 firmware, and also with latest files ... everythings the same.

### Expected Behavior

sucessful update to the latest firmware

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

	v23.10.9

**Comment by micha1221** [comment]
Sorry - new version 24.1.14 !

**Comment by nkappler** [comment]
Are you using a vpn?
Had this issue, although with another version.
For me it was the periodically refreshing connection that caused the error and turning off the vpn helped...

**Comment by ituri** [comment]
Have you tried rebooting? I'm under the impression that if your OpenDTU has been running for a couple of days, the memory will be too full to store the new firmware upgrade. Rebooting "cleans" the memory and allows for enough space for the update - at least that's my amateur theory why a reboot has always helped if updates failed beforehand.

**Comment by micha1221** [comment]
> Are you using a vpn? Had this issue, although with another version. For me it was the periodically refreshing connection that caused the error and turning off the vpn helped...

No, I'm using no vpn.

**Comment by micha1221** [comment]
> Have you tried rebooting? I'm under the impression that if your OpenDTU has been running for a couple of days, the memory will be too full to store the new firmware upgrade. Rebooting "cleans" the memory and allows for enough space for the update - at least that's my amateur theory why a reboot has always helped if updates failed beforehand.

offcourse I thought of that too ... and did many times - with no effect

**Comment by micha1221** [comment]
By the way: same behavior with the V24.1.18 from today ...

**Comment by nkappler** [comment]
> Have you tried rebooting? I'm under the impression that if your OpenDTU has been running for a couple of days, the memory will be too full to store the new firmware upgrade. Rebooting "cleans" the memory and allows for enough space for the update - at least that's my amateur theory why a reboot has always helped if updates failed beforehand.

I'm facing the same issue now,
Seconds after a reboot, the file upload will reach ~60% then it suddenly pauses and after some more time it aborts.

If I get a response to the update call at all, it always seems to be `OTA could not begin`

**Comment by nkappler** [comment]
![image](https://github.com/tbnobody/OpenDTU/assets/9429273/f601f493-3906-4bdf-9d8d-e03cfd325e02)
![image](https://github.com/tbnobody/OpenDTU/assets/9429273/6324c90f-75e1-4e04-9476-65bfdc1af4c3)

**Comment by nkappler** [comment]
Of course the moment I try to make a screen recording it succeeded...
It was my seventh try or so in total, a few minutes after reboot.
So maybe if it doesn't work immediately after a reboot and it doesn't work a long time after a reboot, try it a few minutes after rebooting.

**Comment by micha1221** [comment]
this is my screenshot:
![screenshot](https://github.com/tbnobody/OpenDTU/assets/123741694/5090fdbe-d70b-4303-a318-df1fb3abf8d7)

**Comment by micha1221** [comment]
and the errror:
![screenshot-bad](https://github.com/tbnobody/OpenDTU/assets/123741694/574c9001-2e5b-4670-ac78-19558eb6746d)

**Comment by micha1221** [comment]
OK - this was. Since I've done it seems to work.
