### ISSUE TITLE
Wrong "Total yield" reported during upgrade/reboot

### ISSUE THREAD

**Issue by schlami** [tbnobody/OpenDTU#1692]
### What happened?

I'm using 3 Hoymiles converters with OpenDTU. I was wondering, why from time to time I have wrong "total yield" values in InfluxDB. 

### To Reproduce Bug

Now I've found out that this has most likely to do with a upgrade/reboot. During the reboot it takes some time to receive new values from all converters. During that time it can happen, that only one converter has sent its data. OpenDTU takes this value from this one converter as "total yield" (because the other yield values are still missing) or it even sends a total yield of 0, if no converters have sent data so far. This leads to a dip in the InfluxDB.

### Expected Behavior

Solution proposal: Can the old values be preserved during an upgrade/boot-up? If not, could you delay the first data transmission to MQTT (either configurable or until all inverters become available)? This would help a lot to avoid manual corrections in the InfluxDB. Thanks!

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.1.26

**Comment by tbnobody** [comment]
> Solution proposal: Can the old values be preserved during an upgrade/boot-up?

Not possible as it cannot determined when a reboot occours (Power failure etc)
But you already have the `ac/is_valid` topic which is only 1 if all configured inverters are reachable.
