### ISSUE TITLE
Display SSD 1306 - White line on left side

### ISSUE THREAD

**Issue by HanSolu123** [tbnobody/OpenDTU#1694]
### What happened?

Hello,

there is a white line on the left side on the display (with rotation of 180°.
Anybody knows how to eliminate ?
![PXL_20240128_101539515 MP](https://github.com/tbnobody/OpenDTU/assets/117641113/148eda6d-df15-49ae-bed8-2026846e0478)

### To Reproduce Bug

Always
SW Version 24.1.26 and earlier

### Expected Behavior

Elimante the white line

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

24.1.26

**Comment by tbnobody** [comment]
Seems like the wrong display type is selected. SH1106 vs SSD1309

**Comment by HanSolu123** [comment]
Thanks for your tip. Changing to the correct display type solved the probelm
