### ISSUE TITLE
OpenDTU und BE COOL BC-B2500

### ISSUE THREAD

**Issue by Agtotto** [tbnobody/OpenDTU#1709]
### What happened?

heute 31.1.2024 hat der Speicher BE COOL BE-BC2500  unter Tags zufriedenstellend gearbeitet.
Am frühen Abend, nach dem die Paneele nichts mehr geliefert haben, ist die Entladeleistung auf ca 5W abgesunken und über Stunden bisher so geblieben. Es ist unverständlich, warum die Leistungsabgabe derart reduziert wird, obwohl noch 21% im Speicher sind.  Die Reduktion erfolgte vermutlich durch den Wechselrichter.
Dann habe ich den Wechselrichter Hoymiles HM800 über die openDTU neu gestartet und die Entladung ist sprunghaft auf 600W gestiegen. Dann hat das System wieder ordnungsgemäß gearbeitet.
Außerdem wird immer wieder "FB-Überspannung" gemeldet, obwohl keine zu hohe Spannung am Wechselrichter anliegt.

### To Reproduce Bug

Keine Angabe

### Expected Behavior

Normales Verhalten des Wechselrichters

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

	v4.4.6-dirty

### Relevant log/trace output

```Shell
21:10:26	21:10:26	1	Wechselrichter gestartet
08:14:02	13:03:02	46	FB Überspannung
```

**Comment by tbnobody** [comment]
This issue is most likely related to [OpenDTU-onBattery](https://github.com/helgeerbe/OpenDTU-OnBattery). I would suggest you open a issue there. The OpenDTU project itself does not even have the possibility to handle Battery discharge.
