### ISSUE TITLE
Hoymiles Zero Export with Shelly em zero export Control

### ISSUE THREAD

**Issue by lektronik** [tbnobody/OpenDTU#1712]
### What happened?

Hello, i have an issue running the script. Zero export script doesn't work... I tried to change the POWERMETER_TARGET_POINT to 50 from -75 as default, but nothing happened. I have an export of -100watt and more (is written on the script and also on shelly em interface)... Maybe this is not the minimum wattage from the grid  Any help here..?

### To Reproduce Bug

![image](https://github.com/tbnobody/OpenDTU/assets/63480329/3d5c136c-6412-4db8-a84f-c6164fdcd63f)

### Expected Behavior

I expected to go until 50watt 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.1.26

### Anything else?

[COMMON]

Number of Inverters
INVERTER_COUNT = 1

max difference in percent between SetpointLimit change to approximate the power to new setpoint
SLOW_APPROX_LIMIT_IN_PERCENT = 20

if slow approximation: additional limit based on the limit-difference to "smoot the curve": newLimitSetpoint = newLimitSetpoint + (LimitDifference * SLOW_APPROX_FACTOR_IN_PERCENT / 100)
SLOW_APPROX_FACTOR_IN_PERCENT = 20

interval time for setting limit to Hoymiles
LOOP_INTERVAL_IN_SECONDS = 20

delay time after sending limit to Hoymiles Inverter
SET_LIMIT_DELAY_IN_SECONDS = 5

Timeout time to wait for Acknowledge after sending limit to Hoymiles Inverter
SET_LIMIT_TIMEOUT_SECONDS = 10

delay time after sending limit to Hoymiles Inverter when using more than one Inverter
SET_LIMIT_DELAY_IN_SECONDS_MULTIPLE_INVERTER = 2

polling interval for powermeter (must be < LOOP_INTERVAL_IN_SECONDS)
POLL_INTERVAL_IN_SECONDS = 1

if your powermeter exceeds POWERMETER_MAX_POINT: immediatelly set the limit to predefined percent of HOY_MAX_WATT (if you have more than one inverter it´s the sum of all HOY_MAX_WATT)
value = 0 disables the feature. Values are possible from [0 to 100]
ON_GRID_USAGE_JUMP_TO_LIMIT_PERCENT = 100

max difference between Limit and real output power in % of HOY_MAX_WATT (100 = disabled)
MAX_DIFFERENCE_BETWEEN_LIMIT_AND_OUTPUTPOWER = 100

enable logging to file
ENABLE_LOG_TO_FILE = false

how many logfiles you wish to keep
LOG_BACKUP_COUNT = 30

defines how often the Inverter Power Status will be set, set it to "-1" for disabled (infinite repeat)
SET_POWERSTATUS_CNT = 10

log the inverter temperature
LOG_TEMPERATURE = false

delay time after turning the inverter off or on
SET_POWER_STATUS_DELAY_IN_SECONDS = 10

[CONTROL]

--- global defines for control behaviour ---
POWERMETER_TARGET_POINT is the target power for powermeter in watts
POWERMETER_TARGET_POINT = 50

POWERMETER_TOLERANCE is the tolerance (pos and neg) around the target point. in this range no adjustment will be set
POWERMETER_TOLERANCE = 25

POWERMETER_MAX_POINT is the maximum power of your powermeter for the normal "regulation loop".
if your powermeter jumps over this point, the limit will be increased instantly. it is like a "super high priority limit change".
if you defined ON_GRID_USAGE_JUMP_TO_LIMIT_PERCENT > 0, then the limit will jump to the defined percent when reaching this point.
POWERMETER_MAX_POINT = 0

**Comment by tbnobody** [comment]
Maybe you should try to create an issue in the repository of the zero export script. This repository is for the development of OpenDTU only.
