### ISSUE TITLE
HMS-450-1T reported as unknown device

### ISSUE THREAD

**Issue by nielsvbrecht** [tbnobody/OpenDTU#1744]
### What happened?

OpenDTU reports the HMS-450 as unknown device.

### To Reproduce Bug

Connect HMS-450 to OpenDTU

### Expected Behavior

It should report all the details as it does with my HMS-800

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

23.9.18

**Comment by nielsvbrecht** [comment]
Hardware id as reported in OpenDTU: 270553347

**Comment by tbnobody** [comment]
Thank you. Will be added in the next release
