### ISSUE TITLE
[Request] Show OpenDTU as separate PV Charger in the VRM

### ISSUE THREAD

**Issue by andreas-bulling** [tbnobody/OpenDTU#1759]
### Describe the solution you'd like

OpenDTU is currently not shown as a separate PV Charger in the Victron VRM - like multiple MPPTs are. It would be nice if OpenDTU was also shown separately to more easily see its yield.

**Comment by tbnobody** [comment]
Are you sure that this repo is the right place for this feature request? OpenDTU does not contain any kind of Victron support by itself. Maybe you mean [OpenDTU-on-Battery](https://github.com/helgeerbe/OpenDTU-OnBattery)?

**Comment by andreas-bulling** [comment]
yes, I am very sorry - accidentally posted this to the wrong repo.
