### ISSUE TITLE
Nach Update < 24.1.26 keine "aktuelle Anzeige"

### ISSUE THREAD

**Issue by Fooose** [tbnobody/OpenDTU#1767]
### Is your feature request related to a problem? Please describe.

Moin,
wie der Titel schon sagt funktioniert bei mir mach dem Upgrade die Anzeige nicht mehr.

<img width="1900" alt="1" src="https://github.com/tbnobody/OpenDTU/assets/93667250/d22f1e12-e4cd-4ec6-bdf8-3690e26342fe">
<img width="1898" alt="2" src="https://github.com/tbnobody/OpenDTU/assets/93667250/42a4cf2a-b930-44a5-9861-04692585048d">
<img width="1405" alt="Bildschirmfoto 2024-02-20 um 10 36 24" src="https://github.com/tbnobody/OpenDTU/assets/93667250/c20d3289-4944-4dd0-84c1-adc47c65ce52">

### Describe the solution you'd like

Vielleicht hat ja jemand einen Tipp, was ich übersehe oder/und falsch gemacht habe.

**Comment by tbnobody** [comment]
Sieht so aus als würde dein Browser keine WebSockets unterstützen. Auch bei deinem funktionierenden Bild war der Indikator schon rot. Die neue Version verwendet ausschließlich Websockets zum Update der Daten.

**Comment by Fooose** [comment]
Vielen Dank für deine schnelle Antwort, ich habe "Nginx Proxy" im Einsatz und da vergessen die Unterstützung für WebSockets zu aktivieren.
