### ISSUE TITLE
ESP32-S3 keine PSRAM Anzeige

### ISSUE THREAD

**Issue by Juergen2453** [tbnobody/OpenDTU#1769]
### What happened?

Keine PSRAM Anzeige.
Getestet mit:
ESP32-S3-DevKitC-1 N16R8 (32-Bit-LX7-Dual-Core-Prozessor mit bis zu 240 MHz, 512 KB SRAM, 384 KB ROM, 16 KB RTCSRAM, 8 MB PSRAM)

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

v24.2.16

### Anything else?

Einstellung VSC
![e1](https://github.com/tbnobody/OpenDTU/assets/116970574/32f55a6c-56af-4a84-abf3-1b14cb1e3104)

Einstellung pin_mapping.json
![e2](https://github.com/tbnobody/OpenDTU/assets/116970574/4b9c291b-3f61-422b-9feb-a67be6795941)

Ergebnis
![e3](https://github.com/tbnobody/OpenDTU/assets/116970574/03150cbc-886b-4af1-b71b-d0f3b3a0b238)

**Comment by tbnobody** [comment]
That is not a problem of opendtu but of the platformio configuration of your board. 
You could e.g. try this: https://github.com/platformio/platform-espressif32/pull/921#issuecomment-1766069497

**Comment by Juergen2453** [comment]
Super Danke für den link.
Dieser Eintrag hat geholfen:

![e5](https://github.com/tbnobody/OpenDTU/assets/116970574/c0756dad-2bfe-46ff-82cc-8dceb10fe720)

Danach habe ich PSRAM:

![e4](https://github.com/tbnobody/OpenDTU/assets/116970574/b6cdf87f-1f46-488a-99f0-76a7a8c5eab2)

Kann dann geschlossen werden.
