### ISSUE TITLE
Missing inverter data in /api/livedata/status

### ISSUE THREAD

**Issue by A380Coding** [tbnobody/OpenDTU#1777]
### What happened?

Upgraded to 24.2.16, coming from 24.1.26
Previously with the api request /api/livedata/status all inverter data could be fetched. With 24.2.16 the AC[], DC[] and INV[] arrays are missing. Only status values can be read.
Reading with /api/livedata/status?inv=serial sends all the data, but only for this one inverter

### To Reproduce Bug

just call http://<IP>/api/livedata/status

### Expected Behavior

Data from all inverters should be send back when calling http://<IP>/api/livedata/status.
AC, DC power, dailyenergy, totalenergy etc.

Or was that changed on purpose?

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

24.2.16, generic_esp32

### Relevant log/trace output

```Shell
-
```

### Anything else?

Bug or changed on purpose and now each inverter has to be read separately?
If changed on purpose -> Feature request to read all inverters at once at previously using /api/livedata/status command.

**Comment by tbnobody** [comment]
Please see #1763 and #1741 and the changelog and the breaking changes list at the README.md.

It was done on purpose and no, a feature request is not possible. The ESP32 does not have enough memory to render the 40kb json for the whole data at once. Even when implementing new features etc.
