### ISSUE TITLE
Typo in German language

### ISSUE THREAD

**Issue by Grothesk242** [tbnobody/OpenDTU#1780]
### What happened?

Netz: Eletrizitätsnetzausfall
should be: 
Netz: Elektrizitätsnetzausfall

### To Reproduce Bug

Check Ereignisanzeige

### Expected Behavior

Minor fix required

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.2.16

**Comment by rs3hc** [comment]
More misspelling in 2024.02.19.post1

![WhatsApp Bild 2024-02-24 um 13 29 40_d9d9f42b](https://github.com/tbnobody/OpenDTU/assets/69956680/03431b6f-fe09-46a7-8ff0-22e120a9549c)

And Buttontext is missing:

![WhatsApp Bild 2024-02-24 um 13 31 06_8f4927ba](https://github.com/tbnobody/OpenDTU/assets/69956680/ceeb57e7-0edf-4b6b-83b7-b3ea75f56dea)

**Comment by tbnobody** [comment]
@rs3hc maybe you should tell this things the OpenDTU-onBattery team or at least test if it also occours in this version if you file a issue here. Because all this stuff is working.

**Comment by rs3hc** [comment]
Ok 👍
