### ISSUE TITLE
API does not show panel data

### ISSUE THREAD

**Issue by floriangutzeit** [tbnobody/OpenDTU#1781]
### What happened?

I am calling the API with Node-RED under

http://{dtu_ip}/api/livedata/status

and it went very well until I did an update beginning this year. 

Since then, it's not possible to anymore to access e.g.

inverters.0.AC.0.Efficiency.v

of the json struct.

### To Reproduce Bug

call http://192.168.30.45/api/livedata/status on the webbrowser nor with Node-RED

### Expected Behavior

getting statistic detail data on e.g. panel DC voltage & power.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.2.16

### Relevant log/trace output

```Shell
http://192.168.30.45/api/livedata/status

{"inverters":[{"serial":"116491626706","name":"Hoymiles HMS-1600-4T","order":0,"data_age":1,"poll_enabled":true,"reachable":true,"producing":true,"limit_relative":44.5,"limit_absolute":712}],"total":{"Power":{"v":199,"u":"W","d":1},"YieldDay":{"v":1702,"u":"Wh","d":0},"YieldTotal":{"v":90.8710022,"u":"kWh","d":3}},"hints":{"time_sync":false,"radio_problem":false,"default_password":false}}
```

**Comment by tbnobody** [comment]
Please search for existing issues before opening a new one.
Also read the changelog (Breaking Changes)

Also see #1777, #1763, #1741
