### ISSUE TITLE
[Request] turn off automatic check of update of firmware

### ISSUE THREAD

**Issue by 4c2** [tbnobody/OpenDTU#1787]
### Is your feature request related to a problem? Please describe.

I turned on the automatic check for update under: Info -> System -> Firmware update. 
Later on I wanted to turn it of. But unfortunately, there is no option to turn it off again. 

### Describe the solution you'd like

have an option under Firmware update to turn off the automated check (again). 

### Describe alternatives you've considered

1) leave it as it is: disadvantage: github is contacted every log in. it is privacy protection issue "only"
2) add "check once" button: may cause additional work and benefit is less

### Additional context

used version: v24.2.16

**Comment by 4c2** [comment]
yes, this works. In firefox, one can find the settings here: 

![Bildschirmfoto vom 2024-02-27 18-31-17](https://github.com/tbnobody/OpenDTU/assets/76594587/164fbd4f-31de-49dc-8f5b-c1266886f5eb)
(set from 1 --> 0 and refresh page. 

Shall we leave the issue open for further improvements?

**Comment by MetaChuh** [comment]
> Shall we leave the issue open for further improvements?

probably yes, as it sounds reasonable to be able to reset this value from within the opendtu gui

**Comment by 4c2** [comment]
@tbnobody also thanks from my side. It works well in v24.3.15.
