### ISSUE TITLE
[Request] Add description for error 152

### ISSUE THREAD

**Issue by phol** [tbnobody/OpenDTU#1798]
### Is your feature request related to a problem? Please describe.

My inverters showed error code 152 on HMT-2250-6T, which is listed as "Unknown" in OpenDTU and not included in the Hoymiles manual. 
Therefore, I reached out to Hoymiles support.

### Describe the solution you'd like

This is the answer I received from Hoymiles support

"The 152 code is for the AC failure. When the phase angle difference between any two phases of the ABC phase exceeds 5° and the count exceeds 10 times, the alarming show on the platform."

Could you please add this description for error code 152.

**Comment by phol** [comment]
I think something like this should be added to `src/parser/AlarmLogParser.cpp`, but I'm getting error `too many initializer values`, so therefore I chose to open an issue, rather then a merge request, as I don't have any experience with C++.

```cpp
    { AlarmMessageType_t::ALL, 152, "AC failure: The phase angle difference between any two phases exceeded 5° >10 times", "", "" },
```

**Comment by homeautomation2022** [comment]
Change https://github.com/tbnobody/OpenDTU/blob/master/lib/Hoymiles/src/parser/AlarmLogParser.h#L11 to 131
and add
`{ AlarmMessageType_t::HMT, 152, "AC failure: The phase angle difference between any two phases exceeded 5° >10 times", "", "" },` here: https://github.com/tbnobody/OpenDTU/blob/master/lib/Hoymiles/src/parser/AlarmLogParser.cpp#L63

@phol Can you please thank Hoymiles and ask them via email whether you can get a current list of all error codes, as unfortunately some are missing from the instructions. We've been waiting for the missing ones for a long time, that would be nice.

**Comment by tbnobody** [comment]
I've already included it in my local development branch. Will be part of the next release

**Comment by lumapu** [comment]
would be nice to have all the error / warning codes. Does anybody searched already in the Hoymiles Cloud? I think they should be somewhere listed as JSON. Maybe it helps again to decompile a recent version of the Hoymiles App @DanielR92

**Comment by phol** [comment]
@homeautomation2022 I have requested a full list of codes, but unfortunately, Hoymiles customer service is not allowed to share it with customers. Therefore, I think we'll indeed have to rely on decompiling apps, searching through the cloud and asking whenever they pop up, as I just did in #1847 .
