### ISSUE TITLE
Hardware-Model unknown

### ISSUE THREAD

**Issue by svalcken** [tbnobody/OpenDTU#1805]
### What happened?

The Hardware Model is not detected.
Model No: 124097
Model Hoymiles HMS-800-2T

### To Reproduce Bug

Nothing to do. Automatic detected.

### Expected Behavior

Right detection of inverter and right grid Profile.
Installed is the grid Profile DE_VDE4105_2018 and in DTU is the grid Profile US - NA_IEEE1547_240V detected.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

V24.2.16

**Comment by svalcken** [comment]
![IMG_0244](https://github.com/tbnobody/OpenDTU/assets/2708976/45ae3a3f-332c-4b84-8da1-a9a0d53cddb6)

**Comment by tbnobody** [comment]
could you please doublecheck after a inverter restart (so most likley tomorrow) and a dtu restart? the hardware part number looks too short.

**Comment by tbnobody** [comment]
Because of #645, #1066, #1204, #1234, #1250 and #1254 which all reported the same Hardware-Part-Number I will define `124097` as invalid and trigger a re-request of the data.

**Comment by svalcken** [comment]
Ist mir heute aufgefallen, weil ich mich gewundert habe, dass der Wechselrichter mit mehr rund 611 statt Max 600w mir angezeigt wurde.
Darauf habe ich gesehen, dass das Grid Profil falsch ist und sehr kurze Hex String angezeigt wurde.

Und danach sah ich, dass der Wechselrichter nicht richtig angezeigt wurde.

Ich teste morgen, ob der Wechselrichter und das Grid wieder richtig erkannt wird.
Wechselrichter ist jetzt aus.
OpenDTU habe ich gerade rebootet.

Melde mich dann nochmal.

**Comment by svalcken** [comment]
Heute Morgen wurde der Wechselrichter korrekt erkannt und die Modelnummer ist auch länger.

Gleiches gilt fürs Gridprofil, dass gestern zu kurz war.

Kann es sein, dass der Speicher vollgelaufen ist oder dass die Übertragung nicht vollständig war?

Es muss ja ein Grund geben, warum die Daten falsch waren.

**Comment by homeautomation2022** [comment]
Übertragungsproblem ist am wahrscheinlichsten und anschließend falsch geparste Daten aus den Bytes.

**Comment by tbnobody** [comment]
> Übertragungsproblem ist am wahrscheinlichsten 

Wäre aber krasser zufall. weil die ganzen CRC prüfsummen passen ja. ansonsten würden die pakete ja sofort verworfen. irgendwas verhaspelt da der inverter. wie gesagt. die 124097 nehme ich zum anlass einen re-request zu senden. mal sehen was so passiert :)
