### ISSUE TITLE
add AC yieldtotal in HA like sensor and enable expiration for a part of sensor [Request]

### ISSUE THREAD

**Issue by smiley-2** [tbnobody/OpenDTU#1814]
### Describe the solution you'd like

Hello,
sorry for my english, I can't find the ac yieldtotal for all of my device in HA, only for each one.
An I think, if it's possible, It's great to enable the expiration but not for the ac yieldday total and for each device.
the value reset when we pass midnight, it's possible?

thanks!

**Comment by hschurer** [comment]
There is a MQTT topic that stores this value, but it's no automatically visible in Home-Assistant.
AC Yieldtotal of all inverters is available in a MQTT Topic : opendtu/ac/yieldtotal or solar/ac/yieldtotal depending on your naming convention.
You can add this sensor to HA bij manually listen on MQTT on this topic.

Regarding the value resets you can set these parameters individually on each inverter in their settings on OpenDTU
![image](https://github.com/tbnobody/OpenDTU/assets/89450968/996deb4c-4753-4c4d-a9b9-a2f90ff3f812)

**Comment by smiley-2** [comment]
a big thanks for your help!

**Comment by MetaChuh** [comment]
@smiley-2 
please close this issue, if the info from @hschurer has solved this issue for you.

greetings and thanks,
metachuh
