### ISSUE TITLE
Hexadecimal S/N cannot be entered

### ISSUE THREAD

**Issue by Megaranos** [tbnobody/OpenDTU#1833]
### What happened?

I tried to connect my HMS 1600 to my openDTU(-onBattery). My HMS has a hexadecimal S/N (1164A0086224) but the input is limited to numbers only. I cannot enter a hexadecimal S/N.

### To Reproduce Bug

To Reproduce Bug, try to enter a hexadecimal S/N.

### Expected Behavior

I expect to be able to enter a hexadecimal S/N.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.02.19.post1

### Anything else?

Corresponding discussion https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/757

**Comment by schlimmchen** [comment]
This is a picture of the inverters label, shared by @Megaranos in https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/757, rotated and adjusted for perspective:

![313109513-0e45bd75-23eb-4da9-8d56-abc5390619e4](https://github.com/tbnobody/OpenDTU/assets/3578416/d0b088b3-9bd8-414d-808b-10f7a1656175)

**Comment by tbnobody** [comment]
Implemented in f995287a6e721d5be06d9bdedfb354f76be2eaf6
