### ISSUE TITLE
Not able to update from v23.10 to higher one

### ISSUE THREAD

**Issue by mcfuhrt** [tbnobody/OpenDTU#1836]
### What happened?

I cannot update from version v23.10.9 to a higher version. I even get an OTA error for the next version.
<img width="849" alt="Screenshot 2024-03-17 at 16 01 04" src="https://github.com/tbnobody/OpenDTU/assets/39857259/9d4fa6a0-83ae-4bf2-a865-bc060f9fea5a">
<img width="828" alt="Screenshot 2024-03-17 at 15 59 46" src="https://github.com/tbnobody/OpenDTU/assets/39857259/11a062ab-b305-439b-8144-0982661a05cb">

### To Reproduce Bug

Downgrade to v23.10.9 and try to upgrade to on of the newer versions.

### Expected Behavior

Successful update to any of the next versions

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.10.9

**Comment by tbnobody** [comment]
Please search for existing issues before opening a new one. Your one is related to #1501
Provide a screenshot of Info --> System --> Memory Information
If the max sketch size is not equal 1920 please follow this manual:  https://www.opendtu.solar/firmware/howto/upgrade_partition/

**Comment by tbnobody** [comment]
Closed due to further activity. Feel free to reopen or create a new issue if the problem persists.
