### ISSUE TITLE
Unknown model - HMS-1600-4T Hardware Part Number: 124097

### ISSUE THREAD

**Issue by Soe-Koh** [tbnobody/OpenDTU#1852]
### What happened?

Unknown model - HMS-1600-4T Hardware Part Number: 124097

### To Reproduce Bug

Unknown model - HMS-1600-4T Hardware Part Number: 124097

### Expected Behavior

Unknown model - HMS-1600-4T Hardware Part Number: 124097

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.3.15

**Comment by tbnobody** [comment]
Related to #1846
