### ISSUE TITLE
[Request] Distinct MQTT Topics + Auto Discovery

### ISSUE THREAD

**Issue by Horstexplorer** [tbnobody/OpenDTU#1869]
### Describe the solution you'd like

1) MQTT topics, encompassing categories like 'General Topics' and 'Inverter total topics,' should contain an identifier directing to the specific opendtu instance they originate from. In certain scenarios, like communicating with both HM and HMS type of inverters, running multiple instances of OpenDTU becomes necessary. However, this may render messages unassignable, thus impeding further processing.

2) MQTT topics, spanning categories such as 'General Topics' and 'Inverter total topics,' should be integrated into the 'Home Assistant MQTT Auto Discovery' feature to simplify access to those aggregated values.

### Describe alternatives you've considered

1) You could manually calculate the sums from various inverter/panel specific values.
2) The data can be added into Home Assistant through following manual configuration steps.

**Comment by tbnobody** [comment]
1. Just change the base topic for each of your instances. e.g. `solar/<dtu serial>`
2. This was already requested in other issues and is also forseen here: #317
