### ISSUE TITLE
pool.ntp.org must not be used by software

### ISSUE THREAD

**Issue by bohni** [tbnobody/OpenDTU#1877]
### What happened?

Default NTP server is pool.ntp.org

https://github.com/tbnobody/OpenDTU/blob/3b05f447d5c2c9e386a432e0b015ca11db2c8595/include/defaults.h#L25

### To Reproduce Bug

Fresh install an check NTP config

### Expected Behavior

Use a vendor specific NTP server.

see https://www.ntppool.org/de/vendors.html

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

3b05f44

**Comment by bohni** [comment]
So, if you quote, so please quote complete:

Open Source projects are of course particularly welcome to use the pool in their default setup, __but we ask that you [get a vendor zone](https://www.ntppool.org/de/vendors.html#vendor-zone)__ when using the pool as a default configuration.

**Comment by tbnobody** [comment]
Thanks for the hint. I am already in contact with them.

**Comment by bohni** [comment]
> Thanks for the hint. I am already in contact with them.

You're welcome
