### ISSUE TITLE
Prometheus API labels changed, breaking dashboards

### ISSUE THREAD

**Issue by CommanderRedYT** [tbnobody/OpenDTU#1878]
### What happened?

Instead of using "AC" in "type" labels, it is now "INV". It also feels like some other things have changed, as it does not work 100% correct when replacing "AC" with "INV".

### To Reproduce Bug

Update to [v24.3.22](https://github.com/tbnobody/OpenDTU/releases/tag/v24.3.22)

### Expected Behavior

Database API should be backwards compatible

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.3.22

**Comment by tbnobody** [comment]
Unfortunatly not possible to keep all old api endpoints on a small device like the ESP. Please update your querys or use a previous version.

**Comment by CommanderRedYT** [comment]
How would you recommend making it so both old and new versions work? I would need that for my app

**Comment by tbnobody** [comment]
dont know anything about prometheus... but what about querying for AC.type + INV.type
the first one is filled the other one for new data.
