### ISSUE TITLE
Neustart notwendig - Änderung DTU Einstellungen/Parameter

### ISSUE THREAD

**Issue by relama** [tbnobody/OpenDTU#1884]
### What happened?

Nach Änderung des Abfrageintervalls [DTU Einstellungen->Abfrageintervall] wird der neue Wert erst nach Neustart der DTU übernommen.
u.U: tritt der Fehler auch bei andern Paramtern auf?

### To Reproduce Bug

Änderung des Abfrageintervalls und kontrolle ob auf LIve-Webseite die neue Intervallzeit berücksichtigt wird. 
Wechselrichter HMS-1000

### Expected Behavior

Erinnerung/Bemerkung für notwendigen manuellen Neustart.
  oder
automatischer Neustart
  oder 
paramteränderung ohne Neustart

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

xxx

**Comment by tbnobody** [comment]
Found the issue. Will be fixed in next release.
