### ISSUE TITLE
[Request] Eingabe der Hoymiles Seriennummern bei OpenDTU auch alpha-numerisch

### ISSUE THREAD

**Issue by NiklasBaSo** [tbnobody/OpenDTU#1904]
### Is your feature request related to a problem? Please describe.

Die Serialnummer meines Hoymiles Wechselrichters HMS 1600 4T ist alpha-numerisch. Nach meinen Recherchen ist das erst ab Herstelldatum bzw. -jahr 2024 so. Vorher war es rein numerisch.
Das Feld für die Eingabe der Serialnummer des Wechselrichters in OpenDTU ist anscheinend nur numerisch zu befüllen. Ist es möglich das Eingabefeld insofern neu zu definieren, dass auch alpha-numerische Serialnummern eingegeben werden können? Ansonsten ist es zur Zeit nicht möglich neue Wechselrichter aus 2024 bei OpenDTU zu erfassen.

### Describe the solution you'd like

Änderung der Definition des Eingabefelds der Serialnummer von numerisch zu alpha-numerisch.

### Describe alternatives you've considered

Falls es andere Lösungen gibt, gerne her damit :)

### Additional context

Analog zu Issue #714, da ging es aber um die Serialnummern der DTUs. Hier geht es um die Wechselrichter selbst.

**Comment by tbnobody** [comment]
Wurde bereits in https://github.com/tbnobody/OpenDTU/releases/tag/v24.3.15 implementiert...
