### ISSUE TITLE
total current power via mqtt to HomeAssistant

### ISSUE THREAD

**Issue by AzraelsDisk** [tbnobody/OpenDTU#1907]
### Is your feature request related to a problem? Please describe.

Today, I have to build an additional unit in the HA to combine all the current performance information from the individual devices into one.

### Describe the solution you'd like

I would like to see the current total power as it is available via MQTT under solar/ac/power in the Home Assistant automatically.

**Comment by tbnobody** [comment]
Duplicate of #1050
