### ISSUE TITLE
Entity for string voltage 

### ISSUE THREAD

**Issue by IenteredanUsername** [tbnobody/OpenDTU#1911]
### Is your feature request related to a problem? Please describe.

It would be great to obtain entities for the voltage of a string, allowing me to determine the state of charge based on the voltage of a connected battery to the inverter and display it in Home Assistant. Thank you so far!

### Describe the solution you'd like

Add entity for connected strings

**Comment by tbnobody** [comment]
Just enable the individual panels option...
https://www.opendtu.solar/firmware/configuration/mqtt_settings/#individual-panels

**Comment by IenteredanUsername** [comment]
perfekt, thank you !
