### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by deanZZZZZ** [tbnobody/OpenDTU#1923]
When Opendtu loses connection with the microinverters  homeassistant shows the last power (for example 800w) of the inverter until I restart esp 

### Describe the solution you'd like

Mqtt should report 0W if the connection between opendtu and the microinverter drops

**Comment by tbnobody** [comment]
Do you already enabled the "zero runtime data" functionally? 

https://www.opendtu.solar/firmware/configuration/inverter_settings/#zero-runtime-data

**Comment by deanZZZZZ** [comment]
No. I'll try
