### ISSUE TITLE
Wert bleibt beim ausgeschalteten Wechselrichter stehen.

### ISSUE THREAD

**Issue by Arkadier** [tbnobody/OpenDTU#1948]
### What happened?

Nachdem der Wechselrichter aus ist, bleibt (vermutlich der letzte übermittelte) Wert stehen. Bild 1
Erst nach einem Neustart der DTU ist der Wert bei 0. Bild 2.

Zur Erklärung. Die 15 Ereignisse in der Anzeige auf Bild 1 kommen vom gewollten Abschalten des WR, weil er auf einer Inselanlage läuft und bei vollem Akku gedrosselt und ggfs. abgeschaltet wird (Frequenz Shiffting). 
![IMG_0749](https://github.com/tbnobody/OpenDTU/assets/166981945/0bc9f644-85fc-41d5-b6f8-7c6324dd0e29)
![IMG_0750](https://github.com/tbnobody/OpenDTU/assets/166981945/63eb53b7-b6a4-4d2e-a31c-fba24593529a)

### To Reproduce Bug

Jeden Abend.

### Expected Behavior

Sollte ohne Neustart 0 Watt anzeigen, wenn der Wechselrichter aus ist.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

24.4.12

**Comment by tbnobody** [comment]
Das ist kein bug, das ist gewollt so. Aber schaue dir bitte #1923 an.

**Comment by Arkadier** [comment]
In dem Fall sorry, mein Fehler. Das war so, dass bloß ein DTU sich so verhalten hat, eine andere nicht. Die Einstellungen bei beiden DTUs waren die gleichen. Die Nullung war bei beiden ausgeschaltet.

**Comment by Arkadier** [comment]
Das war beides 24.4.12.
Der einzige Unterschied ist, dass eine mit dem Chip ESP32-D0WD-V3 ist und die, welche die "Probleme" breitet hat den Chip ESP32-D0WDQ6 hat.
