### ISSUE TITLE
Firmware update from v24.3.15 to any higher version via web interface says sucessful but version doesnt increase in system info

### ISSUE THREAD

**Issue by Rainking80** [tbnobody/OpenDTU#1952]
### What happened?

i cannot update v24.3.15 to any higher version via web interface. It finishes sucessfully but version doesnt increase in system info. i tried several versions.

### To Reproduce Bug

run a firmware update

### Expected Behavior

updating to v24.4.24

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.3.15

**Comment by Rainking80** [comment]
![image](https://github.com/tbnobody/OpenDTU/assets/5574367/c73fb314-6372-4657-ba92-a7ef2f41e6ea)
![image](https://github.com/tbnobody/OpenDTU/assets/5574367/fc1b66d9-7407-41f8-bf06-69868161b358)

**Comment by tbnobody** [comment]
Going to close this issue due to inactivity. 
Regarding the connection reset. I also face this issue sometimes. But its still unknown when the issue occours and how to fix it.
