### ISSUE TITLE
Problem beim ändern des Abfrage Intervalls

### ISSUE THREAD

**Issue by alfprae** [tbnobody/OpenDTU#1958]
### What happened?

Beim ändern des Abfrage Intervalls kommt folgende Meldung: Die Frequenz muss zwischen 860250000 und 923500000 kHz liegen und ein Vielfaches von 250kHz betragen!
Neuladen der Webseite bringt nichts, bereits auf 3 verschiedenen Geräten versucht.

### To Reproduce Bug

Neues Interval eingeben und speichern. Es gibt auch kein Feld mit der Frequenz.

### Expected Behavior

Ess kommt die Fehlermeldung Die Frequenz muss zwischen 860250000 und 923500000 kHz liegen und ein Vielfaches von 250kHz betragen! beim speichern

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.4.24

**Comment by tbnobody** [comment]
What RF module are you using? I assume it's a CMT2300a?

Could you please provide some screenshots of "Info" --> "System" and the "Settings" --> "DTU" view?

**Comment by alfprae** [comment]
Rf24Am 30.04.2024 10:01 schrieb tbnobody ***@***.***>:
What RF module are you using? I assume it's a CMT2300a?
Could you please provide some screenshots of "Info" --> "System" and the "Settings" --> "DTU" view?

**Comment by alfprae** [comment]
![grafik](https://github.com/tbnobody/OpenDTU/assets/168512451/17a871f9-ac3a-4d7f-b85c-3b17a0608d06)
Es ist ein nRF24 Modul

**Comment by alfprae** [comment]
![grafik](https://github.com/tbnobody/OpenDTU/assets/168512451/4f22eaeb-83ad-4fb4-b0ae-85a270487c48)
![grafik](https://github.com/tbnobody/OpenDTU/assets/168512451/676cd43c-59d5-47dc-93bf-d1bb4990f597)

**Comment by alfprae** [comment]
Auf allen 3 Geräten, Win11, Win10 und Android jeweils den Cache geleert und die Seite neu geladen. Hat nichts gebracht.

**Comment by tbnobody** [comment]
Hmmm kann ich leider immer noch nicht nachvollziehen. Klappt hier ohne Probleme. Mir ist noch nicht ganz klar was da passiert.

Könntest du ggf. über die Konfigurationsverwaltung ein Backup der config.json erstellen, mit einem Texteditor bearbeiten, da drin dein WiFi Passwort bzw. SSID löschen und die Config hier einstellen?

**Comment by tbnobody** [comment]
Also der Fehler befindet sich schon in der config.json. 
Speziell:
```json
"cmt_frequency": 1711573504,
```
Ich bin gerade nicht sicher wie das passiert ist. War das eine Neuinstallation von OpenDTU oder wurde upgegraded?

Als Workaround könntest du versuchen, den Wert in der json Datei (aber Vorsicht, die korrekte Datei ohne herausgelöschte Passwörter etc.) durch folgendes zu ersetzen:
```json
"cmt_frequency": 865000000,
```

**Comment by alfprae** [comment]
Es war eine alte Version drauf, diese habe ich geflasht auf die v24.1.26 und später ein Update auf die aktuelle Version gemacht. Der Fehler ist auch schon bei der v24.1.26 aufgetreten. Ich habe deien Workaround durchgeführt. Der Fehler ist weg, ich kann die Änderungen für die Einstellungen der DTU wieder speichern.
![grafik](https://github.com/tbnobody/OpenDTU/assets/168512451/c2e7062f-9f8e-483a-bb10-ae2c30980dc9)

Vielen Dank für die Lösung.

**Comment by alfprae** [comment]
Nochmalls vielen Dank
