### ISSUE TITLE
Prometheus API return wrong information in function addPanelInfo

### ISSUE THREAD

**Issue by Paddy65305** [tbnobody/OpenDTU#1960]
### What happened?

I have two Hoymiles and it seams that in the promotheus API the information how are writen from the "WebApiPrometheusClass::addPanelInfo" are wrong.
I get value for opendtu_PanelInfo, opendtu_MaxPower from the wrong inverter.
The API return for the PanelInfo from INV1 the PanelName from INV2 and
The API return for the PanelInfo from INV2 the PanelName from INV1.
Same for the MaxPower.

### To Reproduce Bug

Set in OPENDTU- Config  the panelnames for two DTU and call
/api/prometheus/metric

### Expected Behavior

The API should return for the PanelInfo from INV1 the PanelName from INV1 and
The API should return for the PanelInfo from INV2 the PanelName from INV2.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

24.4.12

**Comment by tbnobody** [comment]
Don't know. Here it works exactly as expected. Could you please provide screenshots of your config and of the output of the metrics endpoint?

**Comment by Paddy65305** [comment]
I hope it's okay that the OpenDTU Screenshoot of the configuration of the Inverters are in German.
But you see in the config of my HM-300 is one string and the Hoymiles HM 600 have two.

![config_HM300](https://github.com/tbnobody/OpenDTU/assets/35470080/08358598-30b0-4dfb-a8da-a68532004012)
![config_HM600](https://github.com/tbnobody/OpenDTU/assets/35470080/0b60ac42-da94-4289-b03e-d66d4300511a)

and this will return from the api-endpoint:
![prometheusAPI](https://github.com/tbnobody/OpenDTU/assets/35470080/c58482e6-2b16-43a8-b40a-3ee641e48977)

the second stringname from the HM-600 is missing

**Comment by tbnobody** [comment]
> I hope it's okay that the OpenDTU Screenshoot of the configuration of the Inverters are in German.

Of course :)

Thank you!
Found the issue. Will befixed in next release!
