### ISSUE TITLE
Hoymiles Inverter: Serial number  with alphabetic character (f.e. 1144AXXXXXX)

### ISSUE THREAD

**Issue by kstkstkst** [tbnobody/OpenDTU#1972]
### Is your feature request related to a problem? Please describe.

Actual Hoymiles inverters have a serial number which contains an alphabetic character (f.e. 'A').

### Describe the solution you'd like

Actually in openDTU a int64 object is used for the Hoymiles serial number.
This type should modified to a string or char object.

**Comment by tbnobody** [comment]
> This type should modified to a string or char object.

Nope... it should not. If you enter a serial number with characters, they are automatically converted to decimal (instead of hex).
