### ISSUE TITLE
Cannot add serial number containing letters (HMS-800-2T) 

### ISSUE THREAD

**Issue by Bleygo** [tbnobody/OpenDTU#1989]
### What happened?

Hello,
I have three HMS-800-2T. One of the three broke down.
After a breakdown, I have to add the new inverter but the serial number contains letters, so it is impossible to add it in OpenDTU

![image](https://github.com/tbnobody/OpenDTU/assets/126673463/14c6d092-3eb9-4b6f-96b0-04577bcd2028)

![image](https://github.com/tbnobody/OpenDTU/assets/126673463/c77243bd-06e8-4c2d-8a6d-b04939cfd473)

Do you have a solution ?
Merci 

### To Reproduce Bug

adding an inverter with letters, there will be an error message

### Expected Behavior

Possible addition of an inverter with letters

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.2.16

**Comment by tbnobody** [comment]
This was implemented some when in march. Please upgrade to a more up-to-date version
