### ISSUE TITLE
[Request] Stand-alone Hoymiles lib / Support for RTL-SDR and SX127x/RFM9x chips

### ISSUE THREAD

**Issue by LorbusChris** [tbnobody/OpenDTU#1993]
### Describe the solution you'd like

I'd like to integrate communications with my Hoymiles HMS more flexibly into other projects, i.e. to recv messages without pulling in all of OpenDTU.

I'd also like to be able to do this using an RTL-SDR dongle.

It looks like it could also be possible to use an SX1276 (aka RFM95) for this, which supports LoRa, FSK, GFSK, MSK, GMSK and OOK. Even the SX1231/RFM69 might be supportable. Are there any obvious reasons these chips CANNOT be used that I'm missing?

Has anyone considered adding a Hoymiles HMS decoder to https://github.com/merbanan/rtl_433 ?

SX1276 enablement could then happen in https://github.com/NorthernMan54/rtl_433_ESP, which would make the decoder more widely usable in the Arduino/ESP32 ecosystem.

### Additional context

Related: There is already a very neat unofficial esphome component which essentially just extracts the Hoymiles lib from this repo: https://github.com/kvj/esphome_Hoymiles_Inverter/ - adding the decoder to esphome properly would also help making this an official component, even without support for any additional RF chips. (cc @kvj)

xref: https://github.com/lumapu/ahoy/issues/1630 for the sibling issue on the Ahoy repo

**Comment by tbnobody** [comment]
This is something which will not be done by me.... The RF modules are chooses as they are because they are also built into the inverters and use the same parameters as in the inverters. 
Just now the whole communication is already separated into a library (which is included into the opendtu git repo).
