### ISSUE TITLE
MQTT: setting limits not working after changing basic topic

### ISSUE THREAD

**Issue by michib-xx** [tbnobody/OpenDTU#2000]
### What happened?

I have appended an organizing string to the basic MQTT topic, i.e., from `solar/` to `solar/baga/`. 

Now, setting the limits via the `cmd` topic does not work anymore. Previously, the topic to write to was `solar/<invnr>/cmd/limit_nonpersistent_relative`, now, it should be `solar/baga/<invnr>/cmd/limit_nonpersistent_absolute`. However, writing to it does not change the limit. If I reset the basic topic to `solar/`, it works again. 
I've also tried to publish to the original topic, but this doesn't work either.

No matter, if relative or absolute limit is used.

### To Reproduce Bug

- Change the basic topic.
- Try to write a new limit.

### Expected Behavior

The written limit should be applied.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.5.6

**Comment by tbnobody** [comment]
You are right. currently it seems a opendtu restart is required to subscribe to the new topics. will be fixed in next release
