### ISSUE TITLE
Limit Value of inverter displayed wrong

### ISSUE THREAD

**Issue by schwidl** [tbnobody/OpenDTU#2003]
### What happened?

After restarting of openDTU, the Limit of one inverter is displayed 0%, but the inverter is producing something.
The permanent limit of the inverter is definetly set to 100%.
After around 5 minutes, the displayed limit changes to 100%.

### To Reproduce Bug

Just restart the openDTU and watch the limits of the inverters. They are not displaying the real limit. 
![Limit0_Power161W](https://github.com/tbnobody/OpenDTU/assets/67996154/acd7478a-dd76-4748-a5d1-d8297aabfade)

After arround 5 minutes, this is displayed:
![Limit100_AfterSeveralMinutes](https://github.com/tbnobody/OpenDTU/assets/67996154/a84aeb15-5393-414e-a7e4-f06bef5585dc)

### Expected Behavior

I expect the limit value to display correctly from the beginning and not needing several minutes to display correctly.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.5.6

**Comment by tbnobody** [comment]
Thats normal behavior. The limit can only read every 4min without flooding the event log with error messages. Therefor there is a waiting time of 4 minutes before reading the value.

**Comment by schwidl** [comment]
Alright, then it´s a feature. Thanks!
