### ISSUE TITLE
Anzeige der CPU-Temperatur unter System möglich?

### ISSUE THREAD

**Issue by tm-107** [tbnobody/OpenDTU#2018]
### Describe the solution you'd like

Da der ESP32 meines Wissens nach einen internen Temperatursensor hat, wäre es vielleicht schön diesen Wert unter System darzustellen. Würde mich interessieren wie warm das Teil im meist geschlossenen Gehäuse wird.
Meine Shellys (Plus 1PM mit Tasmota) bringen es in der Verteilung ja schon auf über 60°C.

**Comment by Schaefers** [comment]
This is definitely possible, I just did a quick test using `temperatureRead()`: 

![image](https://github.com/tbnobody/OpenDTU/assets/9284160/a89b597e-80a6-4821-ae50-bf359a596607)

@tbnobody if it helps, I could create a MR, but I guess it's just copy paste and some formatting.

**Comment by tbnobody** [comment]
It's already implemented in my local branch. Will be included in the next release.

**Comment by tm-107** [comment]
Thank you!

**Comment by tbnobody** [comment]
Implemented in 6ce474053e280182f1f41327e9dd42d055171ee0
