### ISSUE TITLE
HMS2000 Grid Profile - wrong display of RVHF

### ISSUE THREAD

**Issue by fred777** [tbnobody/OpenDTU#2021]
### What happened?

For both of my HMS2000 with grid profile **DE - DE_VDE4105_2018** the **Frequency Watt (FW) / Recovery High Frequency (RVHF)** parameter is displayed wrongly:

![image](https://github.com/tbnobody/OpenDTU/assets/5749774/f5c84a77-f3a3-43a6-8061-4e4fba9326e1)

=> it should read 50.2Hz :-)

Raw grid profile:
```
03 00 20 01 00 0a 08 fc 07 30 00 1e 0b 3b 00 01 04 0b 00 1e 09 e2 10 00 13 88 12 8e 00 01 14 1e 00 01 20 00 00 01 30 03
02 58 0a c8 07 a3 13 92 12 8e 40 00 07 d0 00 10 50 08 00 01 13 9c 03 e8 00 10 01 f6 13 74 70 02 00 01 27 10 80 00 00 00
08 5b 01 2c 08 b7 09 41 09 9d 01 2c 90 00 00 00 ff a1 b0 00 00 00 01 f4 00 5f a0 02 00 00 00 00 d7 fb
```

In case you're wondering about the non-standard FW Droop Slope (Kpower_Freq) of 100%Pn/Hz instead of 40 - this is correct and on purpose. And it's only active for one of my HMS2000. The other one is using the original grid profile as provided by Hoymiles, see below

![image](https://github.com/tbnobody/OpenDTU/assets/5749774/215fe887-3e11-44c2-ad80-54b4864e1ead)
```
03 00 20 00 00 0a 08 fc 07 30 00 1e 0b 3b 00 01 04 0b 00 1e 09 e2 10 00 13 88 12 8e 00 01 14 1e 00 01 20 00 00 01 30 03
02 58 0a c8 07 a3 13 92 12 8e 40 00 07 d0 00 10 50 08 00 01 13 9c 01 90 00 10 01 f6 13 74 70 02 00 01 27 10 80 00 00 00
08 5b 01 2c 08 b7 09 41 09 9d 01 2c 90 00 00 00 ff a1 b0 00 00 00 01 f4 00 5f a0 02 00 00 00 00 71 df
```

### To Reproduce Bug

display grid profile for HMS2000 and look at RVHF parameter

### Expected Behavior

50.2Hz should be shown instead of 5.02Hz

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

1f1227f

**Comment by tbnobody** [comment]
Hm in this case I would say we haven't understood the structure of the profile correctly.... 
The combination `50 08` in your profile means 
* 0x50 = Frequency Watt (FW)
* 0x08 = Version of profile table

0x08 of the table looks currently as follows:
![image](https://github.com/tbnobody/OpenDTU/assets/1753222/7ba06852-1745-4b1e-8580-ba46128ab9c3)

Whereby the last column is the divider. 
This works currently perfectly for the profiles "DE_VDE4105_2018" in https://github.com/tbnobody/OpenDTU/wiki/Grid-Profile-Parser and also other profiles which access the combination `50 08`.

But if it's not working for your profile, there's still something wrong with the parser logic.

Maybe this is somehow related to #1606

**Comment by tbnobody** [comment]
Based on what I've seen in #1606 the current dividor for the RVHF value should be 10 instead of 100. But lets wait for the confirmation.

And you are right. The version  information are not yet decoded in all details. are you able to see the firmware version and bootloader version in the s-miles cloud as well? does this match the opendtu ouput?

**Comment by tbnobody** [comment]
I know it's a little bit offtopic now but if you have time and like to help, could maybe have a look at the serial console while you reboot the ESP? You should see some requests and responses for `DevInfoAll` and `DevInfoSimple`
It would be helpfull to get this responses in order to determine the correct hardware version. (should be inside in one of these two packages)

**Comment by tbnobody** [comment]
Thats how we are currently reading the values (based on your data)
![image](https://github.com/tbnobody/OpenDTU/assets/1753222/8fa56f7e-122f-4d06-b101-3d3cca17ed04)


The purple marked cells are currently not used. Green and cyan are used and decoded (see green values below).

But based on this data I currently don't see anything that could represent a `H00.04.00`
