### ISSUE TITLE
Grid Profile is detected as XX - EN 50549-1:2019 but Smiles Cloud shows as 2.0.0 (DE_VDE4105_2018)

### ISSUE THREAD

**Issue by pioneer-01** [tbnobody/OpenDTU#2028]
### What happened?

The Grid Profile interpreted by OpenDTU as XX - EN 50549-1:2019 but Smiles Cloud shows as 2.0.0 (DE_VDE4105_2018)

I use a Hoymiles HM-600-2T.

The Grid profile shown in OpenDTU is

![IMG_1685](https://github.com/tbnobody/OpenDTU/assets/138626767/279fac70-0119-46f3-8311-95d97b571fed)

Hoymiles cloud shows something different
![IMG_1684](https://github.com/tbnobody/OpenDTU/assets/138626767/e70fd078-ec80-4154-a338-fd8155d3ee8a)

### To Reproduce Bug

Not sure how :-)

### Expected Behavior

The Grid Profile is shown correctly, which I guess is the DE_VDE4105_2018

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

24.5.6

**Comment by pioneer-01** [comment]
I checked here as well https://github.com/tbnobody/OpenDTU/wiki/Grid-Profile-Parser
and found the profile code in this table as well
![IMG_1686](https://github.com/tbnobody/OpenDTU/assets/138626767/51e23b7e-867a-4636-90e6-be921639ee81)

**Comment by tbnobody** [comment]
> Hoymiles cloud shows something different

Thats interessting because `20 01`
![grafik](https://github.com/tbnobody/OpenDTU/assets/1753222/47a9d25d-6d5b-42b5-aa44-88cec753d883)

in your screenshot should be the version number of the profile. This does not match the version number in your Holymiles account. The screenshot of the wiki pages shows the right information.

**Comment by tbnobody** [comment]
Have you tried to restart OpenDTU? The gridprofile is only read once. If you maybe changed in during the runtime it is not updated again.

**Comment by ms49434** [comment]
> Yes, I restarted OpenDTU by even unplugging the USB power adapter. After restart the profile shows still as XX - EN 50549-1:2019

I've seen this problem in the past with one of my inverters where the information provided by the Hoymiles Cloud was different to the information read from the inverter (via OpenDTU). I managed to solve the issue by reapplying the correct grid profile from a desktop browser (It didn't work with the Hoymiles Installer App).

**Comment by ms49434** [comment]
> To reapply the profile, you used the Hoymiles DTULite stick instead of OpenDTU for a while and applied the profile via S-Miles website?

The profile was set/updated with a Hoymiles DTU Pro S, an installer account and login from a desktop browser at https://global.hoymiles.com/platform/login

**Comment by pioneer-01** [comment]
Thanks, I will use my Hoymiles DTU Stick now to give it a try to re-apply the profile. Then later I can check in OpenDTU again, which is of course currently not running in parallel. 

I have to add, that I am located in Munich, Germany.

the Hoymiles cloud offers only one profile for my location:
![IMG_1690](https://github.com/tbnobody/OpenDTU/assets/138626767/00fce8f2-3a63-4bde-a236-15197f4a924a)

**Comment by pioneer-01** [comment]
Ok, after reapplying the grid profile everything is shown correctly in OpenDTU. 
![IMG_0289](https://github.com/tbnobody/OpenDTU/assets/138626767/7d3a8c55-aa63-409e-88c2-fbb339f34c44)
![IMG_0288](https://github.com/tbnobody/OpenDTU/assets/138626767/df19f42c-ebe3-4747-b639-fb312f812696)

It seems the issue was never on OpenDTU side but Hoymiles cloud screwed something up.

**Comment by tbnobody** [comment]
In this case I would close the issue. 

But interesting. It seems that the original DTU does send the grid profile but does not check whether it was successfull.
