### ISSUE TITLE
Rename/add description to strings

### ISSUE THREAD

**Issue by darkaragon** [tbnobody/OpenDTU#2043]
### Is your feature request related to a problem? Please describe.

Would be nice to rename the strings or add a description to the strings in the frontend for better identification of the PV module in small plants.

### Describe the solution you'd like

Request for feature

**Comment by tbnobody** [comment]
Thats already possible. Please check [here](https://www.opendtu.solar/firmware/configuration/inverter_settings/#name-string-1-x)
