### ISSUE TITLE
Hoymiles HMS-800W hat scheinbar neuen SN-Bereich

### ISSUE THREAD

**Issue by AndreasDev05** [tbnobody/OpenDTU#2061]
### What happened?

Hallo, ich bin gerade dabei mein Hoymiles HMS-800W mit openDTU zu verbinden. Wenn ich versuche die Seriennummer (SN) der internen DTU einzugeben, bekomme ich eine Fehlermeldung, dass sie zu groß ist.
Wenn ich versuche, die meiner Meinung nach richtige, SN des Wechselrichters einzugeben, wird der Typ nicht erkannt und ich kann entsprechend mehr Pannels konf. .
Ich habe ein Hoymiles HMS-800W
Habe ich ein Fehler gemacht? Wie kann ich helfen?
**Danke**
![1718213704329](https://github.com/tbnobody/OpenDTU/assets/66874272/8d976fb0-df6e-4d66-9a2a-daf2316aa8c1)

### To Reproduce Bug

Ja.

### Expected Behavior

Die SN getauscht. Bei der DTU eine zufällige Zahl eingegeben.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.6.10

### Relevant log/trace output

```Shell
Ich setzte ein ESP32, als setzte ich Funkmodule NRF+ und CMT ein.
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by tbnobody** [comment]
HMS-800W haben eine integrierte DTU und sprechen direkt WLAN. Alle Modelle mit W werden von OpenDTU nicht unterstützt (kein NRF noch CMD Modul)
