### ISSUE TITLE
Grid Profil / Frequency Watt (FW) / Wrong shown value "Recovery High Frequency (RVHF)"

### ISSUE THREAD

**Issue by Timbo8112** [tbnobody/OpenDTU#2075]
### What happened?

The value "Recovery High Frequency (RVHF)" is shwon as  5,02 Hz instead of 50,2 Hz
<img width="571" alt="2024-06-17_19h12_38" src="https://github.com/tbnobody/OpenDTU/assets/173088187/06fd0359-0e06-46af-a388-cd12c6e366c1">

### To Reproduce Bug

Used Grid Profil: DE_VDE4105_2018 as created by Hoymiles. Values are correct at the origin profil.
Used Inverter: HMS-900 2T, HW: H00.04.00, SW: V01.00.04
<img width="1164" alt="2024-06-17_19h23_44" src="https://github.com/tbnobody/OpenDTU/assets/173088187/4cedb9fb-7c05-4647-ab04-9e8bd75cc49a">

### Expected Behavior

Correct divider for showing wrong frequency value

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.06.03

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by tbnobody** [comment]
It is now exactly how hoymiles is interpreting the profiles. Please see #2021 and #1606

Especially #1606 shows how the different profiles are interpreted by hoymiles. 

It's shown not right for some inverters but others are shown correctly now.
