### ISSUE TITLE
Reset- bzw. Neustart-Befehl der openDTU über MQTT

### ISSUE THREAD

**Issue by crisi-solar** [tbnobody/OpenDTU#2078]
### Describe the solution you'd like

Es wäre toll wenn man ein Reset bzw. Neustart der openDTU über einen MQTT-Befehl z.B. in Homeassistant auslösen könnte da ich die DTU jeden Tag in der Früh neu starten muss.

**Comment by tbnobody** [comment]
duplicate of #1147
