### ISSUE TITLE
Crash during connection attempt to MQTT broker in Azure Event Grid

### ISSUE THREAD

**Issue by wohlfrom** [tbnobody/OpenDTU#2110]
### What happened?

When configuring secure TLS MQTT connection to [Azure Event Grid](https://learn.microsoft.com/en-us/azure/event-grid/mqtt-transport-layer-security-flow) the ESP crashed during connection and enters a reboot loop until MQTT is disabled in OpenDTU again.

### To Reproduce Bug

Create a MQTT broker in Azure Event Grid following [this tutorial](https://learn.microsoft.com/en-us/azure/event-grid/mqtt-publish-and-subscribe-portal)
Configure OpenDTU with the server `*.germanywestcentral-1.ts.eventgrid.azure.net`
After saving the configuration and first attempt is made to connect to the MQTT broker the crash occurs.

### Expected Behavior

Succesfull connection or failure message that no successful connection was made.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.6.10

### Relevant log/trace output

```Shell
15:38:01.346 > [  6449][V][ssl_client.cpp:62] start_ssl_client(): Free internal heap before TLS 236760
15:38:01.355 > [  6457][V][ssl_client.cpp:68] start_ssl_client(): Starting socket
15:38:01.387 > [  6493][V][ssl_client.cpp:146] start_ssl_client(): Seeding the random number generator
15:38:01.399 > [  6502][V][ssl_client.cpp:155] start_ssl_client(): Setting up the SSL/TLS structure...
15:38:01.405 > [  6510][V][ssl_client.cpp:178] start_ssl_client(): Loading CA cert
15:38:01.418 > [  6521][V][ssl_client.cpp:234] start_ssl_client(): Loading CRT cert
15:38:01.419 > [  6530][V][ssl_client.cpp:243] start_ssl_client(): Loading private key
15:38:01.436 > [  6541][V][ssl_client.cpp:254] start_ssl_client(): Setting hostname for TLS session...
15:38:01.436 > [  6550][V][ssl_client.cpp:269] start_ssl_client(): Performing the SSL/TLS handshake...
15:38:01.806 > Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception). 
15:38:01.814 > Debug exception reason: Stack canary watchpoint triggered (mqttclient)
```

### Please confirm the following

- [ ] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by fawick** [comment]
This is not limited to Azure in any way. I ran into the same problem when using a private MQTT server encrypted with TLS.

**Comment by stefan123t** [comment]
@fawick can you try the patch @wohlfrom added in #2109 ?
Actually it increases the mqtt buffer / stack size from 5120 to 6400 bytes which fixes the issue for him and @scorpi11

**Comment by fawick** [comment]
I'm afraid I cannot, at least not on a short time-frame. For the time being, I am using the released binaries and have no build environment for OpenDTU. 

I've been hoping, once it is known this problem indeed affects more users and is not limited to a single MQTT broker, the OpenDTU maintainers might consider replicating the problem and decide from there whether increasing the default stack size would be acceptable.

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.

I'd like to propose to retitle the issue to `Crash upon establishing TLS-secured MQTT connection`
