### ISSUE TITLE
Hostname can not be changed with Olimex POE Build in Ethernet Mode

### ISSUE THREAD

**Issue by D3R-ST3FAN** [tbnobody/OpenDTU#212]
When connected via Ethernet Cable using the Olimex POE device (no Wifi mode) the hostname can not be changed via WebUI because SSID validation fails.

Errormessage: SSID must between 1 and 31 characters long!

Maybe split Hostname SSID validation?

**Comment by tbnobody** [comment]
You are right. Thats a issue at the moment. The Ethernet Mode is not taken into account at the validation. As a workaround you could insert a dummy SSID. Have to fix this later.

**Comment by D3R-ST3FAN** [comment]
Just wanted to confirm that this has been fixed.
Thank you!
