### ISSUE TITLE
Faulty Sketch size reported in Info Web page

### ISSUE THREAD

**Issue by Web-svg** [tbnobody/OpenDTU#2133]
### What happened?

Hello,
Using Olimex POE card (16MB) and CMT2300A running with firmware V24.6.29 I'm facing what it could be considered as a kind of typo issue:
Info page part related to memories space usage report inconsistent value for sketch (see picture) in all 3 languages.

### To Reproduce Bug

Go to Webapp and Info/system
![2024-07-09 11_05_56-OpenDTU-bug](https://github.com/tbnobody/OpenDTU/assets/63095113/f4fcbbf5-9fd9-4010-825f-c50619158a2c)

### Expected Behavior

Just showing appropriate result of calculation

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

V24.6.29

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by tbnobody** [comment]
What exactly is inconsistent?

**Comment by Web-svg** [comment]
Hello,
Percentage vs memory size i assumeDoes I'm wrong?
Kind regards

Le 9 juil. 2024 à 11:25, à 11:25, tbnobody ***@***.***> a écrit:

**Comment by tbnobody** [comment]
1630 / 1792 = 91%
Seems right for me

**Comment by Web-svg** [comment]
I understood my misunderstanding suddendly....sorry for that.
Could you delete it?


Le 9 juil. 2024 à 12:30, à 12:30, tbnobody ***@***.***> a écrit:
