### ISSUE TITLE
Feature: show NRF24.printPrettyDetails to verify connection problems

### ISSUE THREAD

**Issue by stefan123t** [tbnobody/OpenDTU#214]
The AhoyDTU sends the NRF24.printPrettyDetails upon start of the app. This contains several interesting output to verify connectivity between ESP32 and NRF24.
Though OpenDTU requires recompiling the image for a different Pinout it would be good for support purposes to have the above output.

**Comment by tbnobody** [comment]
At first I also wanted this in the output. But imho the only thing which is important to verify is a valid connection. This is already shown in the WebUI as well as in the serial console.

**Comment by tbnobody** [comment]
Currently the web gui shows connection state and type of the RF chip. If more is required I will add the addtional info
