### ISSUE TITLE
Feature Request : Webinterface verbessern

### ISSUE THREAD

**Issue by ntfrnd** [tbnobody/OpenDTU#216]
Hallo,

ich würde mir für das Webinterface ein paar kleine teilw. optische Verbesserungen wünschen.
Leider habe ich davon keine Ahnung, sonst würde ich selbst Hand anlegen :-) 
Ich hab mal kurz Paint bemüht um meine "Ideen" hier zur Diskussion zu stellen:

1) Bei nur einem Inverter könnte ich auf diese Darstellung verzichten:

![grafik](https://user-images.githubusercontent.com/99898355/195418083-4bf5408f-d2f1-4f05-ac31-076c52dca857.png)

Vielleicht könnte man diese "Auflistung/Gruppierung" nur einblenden, wenn mehr als ein Inverter im Setup eingetragen ist?

2) Das (vom Inverter zurück gelesene) Powerlimit könnte man nicht nur im Menü anzeigen, sondern auch in der Titelzeile. Das macht sich gut, wenn man die Website nebenher geöffnet hat (Tablet). So hat man alles im Blick ohne klicken zu müssen:
 
![grafik](https://user-images.githubusercontent.com/99898355/195419144-3a0cda27-1fd2-417a-9f2a-79356003ad96.png)

3) Auf dem Smartphone finde ich die Darstellung der Website etwas unschön. 

![grafik](https://user-images.githubusercontent.com/99898355/195422863-b5ba5d51-4407-4c06-b782-39fab1a75560.png)

Vielleicht könnte man hier, neben 1), auch noch die Titelzeile des Inverters etwas aufräumen. Wie z.B. jede Info in eine neue Zeile packen, die Icons rechtsbündig, etwa so:
![grafik](https://user-images.githubusercontent.com/99898355/195422999-2229a462-03a6-4305-b0be-fbf460815d5d.png)

Was haltet Ihr davon? Ist wahrscheinlich überschaubarer Aufwand, wenn man weiß wie....

**Comment by b-a-9-0** [comment]
Ich finde die Vorschläge gut!

**Comment by tbnobody** [comment]
Ich auch. Es gibt aktuell nur ein paar Dinge die mehr brennen. Aber steht definitiv auf der Liste.

**Comment by ntfrnd** [comment]
> Ich auch. Es gibt aktuell nur ein paar Dinge die mehr brennen. Aber steht definitiv auf der Liste.

Alles gut, ich wollte nur mal Wünsche platzieren falls es jemand langweilig wird :)

**Comment by hubsi5** [comment]
Und, schwubdiwub schon umgesetzt.
genial, danke!

**Comment by tbnobody** [comment]
Teilweise :)
Die blauen Buttons sind noch da, egal wie viele Inverter eingetragen sind. Hab da aber auch schon eine idee

**Comment by hubsi5** [comment]
Ich bin immer wieder von deiner Professionalität begeistert.
Einfach Top. Danke

**Comment by eeprom23** [comment]
Wäre es möglich noch die Gesamtleistung einzublenden aller inverter und diese per mqtt zu übertragen ?  Bin sehr zufrieden mit Stabilität und Funktionen von opendtu. Nur die o.g. Funktion würde mich sehr freuen. Danke

**Comment by tbnobody** [comment]
Das Ausblenden der Blauen Tabs bei nur einem Inverter sollte sich mit f193e0cafccd8401c55a2d2b10daa43ec8325d6f erledigt haben...

**Comment by tbnobody** [comment]
Die Gesamtleistung und Gesamtertrag summiert für alle Inverter wird seit 438ce36bab8e0096fb7c79546fd7a9edf851d7d9 im web interface angezeigt. MQTT ist noch ausstehend.

**Comment by homeautomation2022** [comment]
Ich hänge mal hier meine Verbesserungsvorschläge fürs Webif an:

Inverter Settings:
- für String 1 und String 2 sollte bei Edit Inverter ein anderer Name anlegbar sein (für Live Data)
- die nicht vorhandenen Strings sollten je nach eingegebener Serial(Typ) in Edit Inverter ausgeblendet werden

Live Data:
- Irradiation nur anzeigen, wenn auch ein Wert größer 0 bei Max power konfiguriert ist
- hinter den Werten von Current Limit und Data Age ist ein Leerzeichen("% " und "seconds ")
- schwieriger(long term): wäre schöner, wenn nicht immer fest 2 Kommastellen bei den Live Daten da sind, sondern entweder bei 0 die Stelle streichen bis zur letzten Ziffer ODER meiner Meinung nach am besten aus den Field defines die Anazhl der Kommastellen holen, es gibt 0, 1, 2 und 3 Nachkommastellen je nach Wert

- ein ESP Reboot Button irgendwo wäre noch gut

**Comment by ntfrnd** [comment]
> Ich hänge mal hier meine Verbesserungsvorschläge fürs Webif an:
> 
> Inverter Settings:
> 
> * für String 1 und String 2 sollte bei Edit Inverter ein anderer Name anlegbar sein (für Live Data)
> * die nicht vorhandenen Strings sollten je nach eingegebener Serial(Typ) in Edit Inverter ausgeblendet werden
> 
> Live Data:
> 
> * Irradiation nur anzeigen, wenn auch ein Wert größer 0 bei Max power konfiguriert ist
> * hinter den Werten von Current Limit und Data Age ist ein Leerzeichen("% " und "seconds ")
> * für calculated CH0 Fields ebenfalls fixe Nachkommastellen hinterlegen
> 
> System Info:
> 
> * bei Memory Info ist bei den Spalten Usage und Free ebenfalls ein unnötiges Leerzeichen am Zeilen/Wert-Ende
> 
> Generell ist hinter manchen Reitern(blau) bei Settings und Infos sowie auch in der Menüleiste ein unnötiges Leerzeichen hinten dran, bei anderen wiederum nicht, sollte einmal alles nachgesehen und gefixt werden, möchte jetzt nicht alles einzeln hier aufführen, Strg+A hilft. Die Ursache dafür ist, das manchmal in einem div der Text mit 2 Zeilenumbrüchen(davor und dahinter) eingerückt ist, statt alles hintereinander in einer Zeile stehen zu haben.
> 
> ein ESP Reboot Button irgendwo wäre noch gut

Find ich gut. Macht das Ganze noch etwas perfekter

**Comment by tbnobody** [comment]
Folgendes ist schon erledigt:
* für String 1 und String 2 sollte bei Edit Inverter ein anderer Name anlegbar sein (für Live Data)
* die nicht vorhandenen Strings sollten je nach eingegebener Serial(Typ) in Edit Inverter ausgeblendet werden
* Irradiation nur anzeigen, wenn auch ein Wert größer 0 bei Max power konfiguriert ist

Für das Thema MQTT Totals publishen gibt es einen eigenen Feature Request: #350

**Comment by tbnobody** [comment]
Ich würde das issue hier schließen, da der letzte Punkt, das Thema mit den Nachkommastellen jetzt auch erledigt ist (1d650b59aeb8aac002da233bfe3a9aa255fcdd6f)
