### ISSUE TITLE
nRF24 Chip-Status not connected

### ISSUE THREAD

**Issue by j0na553n** [tbnobody/OpenDTU#2191]
### What happened?

After Update the Chip ist not connected

### To Reproduce Bug

Update

### Expected Behavior

-

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.8.5

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported

**Comment by tbnobody** [comment]
Provide some screenshots of the info --> system page.

**Comment by j0na553n** [comment]
Hi of course here are some screenshots

![image](https://github.com/user-attachments/assets/857aabf3-73ed-4932-8cbd-559a07e4d19b)
![image](https://github.com/user-attachments/assets/31de9e92-de2b-4b11-b52b-bbddf0729653)
![image](https://github.com/user-attachments/assets/ac99e607-cf99-40d3-bbac-d0ca81d64279)

After downgrade the fault is also there.

**Comment by tbnobody** [comment]
Seems your wiring of the NRF module is somehow damaged.

**Comment by j0na553n** [comment]
oh well this is possible, i have to check. 
Thanks for you hint. 
Do you know is it possible to user an other version of opendtu?

**Comment by j0na553n** [comment]
After a Physical reboot and check of contacts everything works fine.
