### ISSUE TITLE
Überschusseinspeisung nur bei Netzfreqenz kleiner 50 Hz

### ISSUE THREAD

**Issue by XpertXXL** [tbnobody/OpenDTU#2209]
### Is your feature request related to a problem? Please describe.

Um die zunehmende Belastung der Stromnetze bei Überproduktion durch die erneuerbaren Energien zu reduzieren, wäre es sinnvoll nur dann ins Netz einzuspeisen, wenn im Netz Strombedarf besteht (Netzfrequenz < 50 Hz) Keine Einspeisung wenn Netzfrequenz > 50 Hz ist, um Netze nicht zusätzlich zu belasten.

### Describe the solution you'd like

Die bisherige Funktion von OpenDTU ist absolut spitze! Ich möchte einfach mal die Diskussion lostreten, ob wir nicht die Netzbetreiber mit einer solchen Regelung seitens DTU entlasten könnten. Immer mehr liest man von Überlastung der Netze und einem drohenden Kollaps oder wahnsinnigen Kosten zur Kompensierung und Stabilisierung der Netze (das zahlen wir ja auch über die Netzentgelde)
Wäre es möglich, die DTU so zu programmieren, dass die aktuelle Netzfrequenz als Referenz für Strombedarf oder Stromüberschuss ausgewertet wird und wir nur bei Bedarf ins Netz einspeisen, ansonsten Nulleinspeisung oder der vom Nutzer festgelegte Wert.

**Comment by stefan123t** [comment]
@XpertXXL ich will ja nicht vorgreifen, aber ist das nicht eigentlich die Aufgabe des jeweiligen Grid Profiles, ?
z.B.: [DE_VDE4105_2018](https://github.com/lumapu/ahoy/wiki/Protocol#file-name-de_vde4105_2018)
