### ISSUE TITLE
Olimex ESP32-POE - Errors if Ethernet is not connected (WiFi-Mode)

### ISSUE THREAD

**Issue by wib100** [tbnobody/OpenDTU#224]
Hi,
I did some test with the current version and noted that there are some errors reported in the serial console if the Ethernet port is not connected during startup:
18:25:45.147 > ets Jul 29 2019 12:21:46
18:25:45.147 > 
18:25:45.147 > rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
18:25:45.147 > configsip: 0, SPIWP:0xee
18:25:45.147 > clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:25:45.147 > mode:DIO, clock div:2
18:25:45.147 > load:0x3fff0030,len:1184
18:25:45.147 > load:0x40078000,len:13132
18:25:45.147 > load:0x40080400,len:3036
18:25:45.147 > entry 0x400805e4
18:25:45.147 > 
18:25:45.147 > Starting OpenDTU
18:25:45.147 > Initialize FS... done
18:25:45.147 > Reading configuration... done
18:25:45.147 > Initialize Network... ETH start
18:25:46.432 > done
18:25:46.432 > Setting Hostname... Initialize NTP... done
18:25:46.435 > Initialize MqTT... done
18:25:46.438 > Initialize WebApi... done
18:25:46.442 > Initialize Hoymiles interface... Connection successfull
18:25:46.454 >   Setting radio PA level...
18:25:46.457 >   Setting DTU serial... 
18:25:46.460 >   Setting poll interval...
18:25:46.463 > done
18:25:46.463 > Switch to WiFi mode
18:25:46.465 > E (4305) esp_netif_lwip: esp_netif_new: Failed to configure netif with config=0x3ffb26e0 (config or if_key is NULL or duplicate key)
18:25:46.476 > E (4314) esp.emac: esp_eth_mac_new_esp32(595): alloc emac interrupt failed
18:25:46.482 > [  4324][E][ETH.cpp:270] begin(): esp_eth_mac_new_esp32 failed
18:25:46.488 > Setting Hostname... done
18:25:46.506 > E (4352) esp_netif_lwip: esp_netif_new: Failed to configure netif with config=0x3ffb2670 (config or if_key is NULL or duplicate key)
18:25:46.517 > E (4354) esp.emac: esp_eth_mac_new_esp32(595): alloc emac interrupt failed
18:25:46.523 > [  4364][E][ETH.cpp:270] begin(): esp_eth_mac_new_esp32 failed
18:26:01.534 > Disable search for AP... done

I compiled the firmware with the default platform.ini (no debug switched used).

Thanks!

**Comment by stromibaer** [comment]
Im running Olimex too with WiFi enabled. It's working. What problems do you have with it?

**Comment by wib100** [comment]
It's working fine, but I noted that there are some errors during device startup if no ethernet is connected and just wanted to report this.

**Comment by tbnobody** [comment]
Yeah I also saw this output during my tests. Seems to come from the deep of the esp-idf. Would ignore it for now as it doesn't really affect the function.
