### ISSUE TITLE
[Request] Add text field to WebUI (f.e. near serial number or name) where we can store comments about system

### ISSUE THREAD

**Issue by KurtPfeifle** [tbnobody/OpenDTU#2250]
### Is your feature request related to a problem? Please describe.

I always get confused when I look at multiple micro inverters: "Which is which?"

### Describe the solution you'd like

Add text field to WebUI (f.e. near serial number or name) where we can store comments about system

**Comment by tbnobody** [comment]
Duplicate of #806
