### ISSUE TITLE
[Request] Add power level (dBm) to user interface + MQTT

### ISSUE THREAD

**Issue by SciLor** [tbnobody/OpenDTU#2254]
### Is your feature request related to a problem? Please describe.

If you have connection problems, due to high distances or walls it would help to find the optimal spot for the DTU.

### Describe the solution you'd like

Storing the last dBm of each inverter + the min / max values (including a reset)
The last dBm should be added to MQTT

### Additional context

The raw data is available in the console, so the dBm should be available and could be exposed.

**Comment by schlimmchen** [comment]
Completed by edfe06e31eae286fbb88da69e9b65420cfa8628a?
