### ISSUE TITLE
"Equal brightness" in LED settings does not work correctly

### ISSUE THREAD

**Issue by LennartF22** [tbnobody/OpenDTU#2332]
### What happened?

Nothing that bothers me, but technically still a bug, so I though I'd report it: When changing the brightness of LED 0 to **0%** in device settings, the brightness of LED 1 stays at its previous value, even when the **Equal brightness** switch is active.

### To Reproduce Bug

- Go the the **Settings > Device-Manager** page
- Switch to the **LEDs** tab
- Ensure **Equal brightness** is active
- Set **LED 0 brightness** to **0%**

### Expected Behavior

**LED 1 brightness** should change to **0%** together with LED 0, as it is already done when setting the brightness to any other value. Interestingly, setting **LED 1 brightness** to **0%** (so the other way around) also correctly changes the brightness of LED 0.

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

v24.9.26

### What firmware variant (PIO Environment) are you using?

generic_esp32

### Anything else?

![image](https://github.com/user-attachments/assets/f0a9dbbb-6509-4dd7-800b-b5e4307a9f66)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by tbnobody** [comment]
Yes... was a "bug"... will be fixed in the next release.
