### ISSUE TITLE
[Request] Anfrage-Häufigkeit in der Nach reduzieren

### ISSUE THREAD

**Issue by sbernhard** [tbnobody/OpenDTU#2349]
### Is your feature request related to a problem? Please describe.

Nicht wirklich, außer dass es viele "Fehler" bei den Radio-Statistics gibt

### Describe the solution you'd like

Während der Nacht, bzw. wenn der HMS mehrmals nicht erreichbar war, die Häufigkeit der Anfragen von der DTU zum HMS reduzieren. 

### Describe alternatives you've considered

- Einstellungen "Nachtzeiten wo keine Anfragen geschickt werden"

**Comment by tbnobody** [comment]
> Einstellungen "Nachtzeiten wo keine Anfragen geschickt werden"

Was spricht gegen diese Einstellung?

**Comment by tbnobody** [comment]
außerdem, 

Duplicate of #547

**Comment by sbernhard** [comment]
Oh, sorry. Natürlich, dass ist die Option die ich gesucht habe. Ganz vergessen 😃
