### ISSUE TITLE
Unknown model 

### ISSUE THREAD

**Issue by t0mmey** [tbnobody/OpenDTU#2374]
### What happened?

The hoymiles support just updated my HM-1200 and opendtu now shows Unknown model. Hardware teilenummer is 124097

### To Reproduce Bug

After firmware update by hoymiles support 

### Expected Behavior

Proper recognition 

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

?

### What firmware variant (PIO Environment) are you using?

Generic 

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by schneeer** [comment]
Hello,
take a look here: #2153
It's about HMS... inverters, but maybe the firmware update is the problem.

**Comment by Frohbi83** [comment]
Hallo, ich habe genau das gleiche Problem. Ich nutze OpenDTU on battery und in den Wechselrichterinformationen steht auch unbekanntes Modell. Das Problem habe ich schon im OpenDTU on battery-Repository geschildert und wurde hierher verwiesen. Vielleicht kann jemand helfen?
https://github-com.translate.goog/hoylabs/OpenDTU-OnBattery/issues/1348?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=de&_x_tr_pto=sc
![Screenshot 2024-10-26 093729](https://github.com/user-attachments/assets/27ea735f-bd1b-46eb-85d8-420815ce825e)

**Comment by tbnobody** [comment]
@Frohbi83 ich füge deine Hardware Teilenummer beim nächsten Release als HMS-700 hinzu. 
@t0mmey bei dir ist es schwieriger. Deine Nummer passt  nicht in das bekannte Schema.

**Comment by t0mmey** [comment]
> @Frohbi83 ich füge deine Hardware Teilenummer beim nächsten Release als HMS-700 hinzu. @t0mmey bei dir ist es schwieriger. Deine Nummer passt nicht in das bekannte Schema.

Danke dir. Bei mir hat es sich komischerweise von allein gelöst. Ich hab nix gemacht und einen Tag später wird es wieder korrekt angezeigt. Auch die Teilenummer wird jetzt anders angezeigt 🤷🏼‍♂️

![IMG_6580](https://github.com/user-attachments/assets/d4043e76-932f-4140-9764-190bbdec1b2d)

**Comment by Frohbi83** [comment]
> @Frohbi83Ich füge deine Hardware-Teilenummer beim nächsten Release als HMS-700 hinzu. @t0mmeyBei dir ist es schwierig. Deine Nummer passt nicht in das bekannte Schema.

Vielen Dank für die schnelle Hilfe. Ich warte das nächste Release ab und gebe eine kurze Rückmeldung ob nach dem Update alles funktioniert.

**Comment by tbnobody** [comment]
HMS-700 is added in 4594bcb23ee160bb392aacc507dd5396b9e3a444
