### ISSUE TITLE
Zeitumstellung Bug: Berechnung Sonnenaufgang und Sonnenuntergang

### ISSUE THREAD

**Issue by Rob0xFF** [tbnobody/OpenDTU#2377]
### What happened?

Am Tag der Zeitumstellung wird der Sonnenlauf nach alter Zeit berechnet. Der Tag-Modus beginnt damit am Tag der Umstellung eine Stunde zu spät im Herbst, bzw. endet eine Stunde zu früh im Frühling.

### To Reproduce Bug

Tag der Zeitumstellung, Einstellungen->NTP, Dämmerungstyp: Standarddämmerung (90,8°)

Info->NTP. Folgende Anzeige:

Status | synchronisiert
Lokale Uhrzeit: Sunday, October 27 2024 10:11:52
Morgendämmerung: Sunday, October 27 2024 07:53:00
Abenddämmerung: Sunday, October 27 2024 17:53:00

### Expected Behavior

Tag der Zeitumstellung, Einstellungen->NTP, Dämmerungstyp: Standarddämmerung (90,8°)

Info->NTP. Folgende Anzeige:

Status | synchronisiert
Lokale Uhrzeit: Sunday, October 27 2024 10:11:52
Morgendämmerung: Sunday, October 27 2024 **06:53:00**
Abenddämmerung: Sunday, October 27 2024 **16:53:00**

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

4035a41

### What firmware variant (PIO Environment) are you using?

generic_esp32

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by tbnobody** [comment]
As a work around, just wait till tomorrow or restart the dtu to have the new values immeditatly. Currently the sunset / sunrise data is only updated at midnight and not immediatly after a DST change.
