### ISSUE TITLE
Error Parsing pinmapping.json in Hardware. Load/Save COnfigurations not possible.  

### ISSUE THREAD

**Issue by Kroki0815** [tbnobody/OpenDTU#2398]
### What happened?

After Upgrade to 2024.11.07 i got an errror in Hardware: Syntaxfehler in 'pin_mapping.json': Unexpected token '<', "<!DOCTYPE "... is not valid JSON

It is not possible to select a Hardware-Profile anymore. 

Also the Configuration-Menu is not reachable anymore ! So no up/download of pinmapping/config is possible.

It looks like that maybe these links-entries in the pinmapping causes this error:

`        "name": "OpenDTU Fusion v2 with NRF24",
        "links": [
            {"name": "Information", "url": "https://github.com/markusdd/OpenDTUFusionDocs"}
        ],
        "nrf24": {
`

[openDTU_fusion_kroki.json](https://github.com/user-attachments/files/17674774/openDTU_fusion_kroki.json)

[error_hardware](https://github.com/user-attachments/assets/ef9c3323-ae9c-4623-9c13-691d6ff6ad02)

[error_configuration](https://github.com/user-attachments/assets/985342cf-a15c-409d-9807-fdc3c0627618)

### To Reproduce Bug

Load the attached pinmapping.

### Expected Behavior

Also the pinmapping is buggy it should be possible to load/save configurations and pinmappings.

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

v2024.11.7

### What firmware variant (PIO Environment) are you using?

generic_esp32s3_usb

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by Kroki0815** [comment]
I downgraded to previous version and uploaded the pinmapping without the 'links ' entires: Same behaviour after upgrade to actual version!

[pin_mapping.json](https://github.com/user-attachments/files/17674980/pin_mapping.json)

**Comment by tbnobody** [comment]
When does the loading cycle of the config management view occur? 
* You just open the view
* You try to upload a file

The config management dialog will not even look at the content of the json file which are currently on the ESP itself.

**Comment by tbnobody** [comment]
Just to highlight it: Upgrade to the latest version and clean your browser cache.

**Comment by Kroki0815** [comment]
You are right, sorry ! Now it's working. I thought i cleaned up the brower cache, but i only cleaned up the last day !

**Comment by tbnobody** [comment]
Just out of curiosity, did you use OTA do upgrade the firmware or did you do it via USB?
