### ISSUE TITLE
SunSpec(kompatibel) Protokoll 

### ISSUE THREAD

**Issue by De-Ichirou** [tbnobody/OpenDTU#24]
Das SunSpec-Protokoll ist Modbus-Basiert, am einfachsten ModbusTCP, was per WLAN ja sowieso schon in Hardware verfügbar ist.
Damit wird es möglich, den/die Wechselrichter in anderen Systemen zu integrieren, z.B. Victron mit angeschlossenen Speichersystemen, die Daten in das System zu bekommen und (später) auch die Leistungslimitierung umsetzen zu können.

Hier werden insgesamt 2 relevante Komponenten benötigt:
- Leistungslimitierung der WR
- ModbusTCP mit SunSpec

Die Leistungslimitierung ist ja bereits in der Entwicklung, bis diese funktioniert könntest du eine Modbus-Verbindung vorbereiten?
Im Setup wird zusätzlich zur IP-Adresse ein Schalter/Haken für Enable Modbus sowie ein Port (default: 502) benötigt. 

Als Basis wird functioncode 0x04 Read Input Registers der Adressen 30001 bis 40000 sowie 0x03 Read Holding Registers und später wahrscheinlich 0x06 Write Single Register (Limits) benötigt. 
Ich schaue mir das SunSpec gerade an um die genaue Registerbelegung herauszukriegen. 
Eine Python-Implementierung gibt es bereits: [https://github.com/sunspec/pysunspec2](https://github.com/sunspec/pysunspec2)

Kannst du dazu eine define vorbereiten, in der man die entsprechenden Werte den registern zuweisen kann? 
Es kann sein, dass noch weiteres benötigt wird, für den Anfang und Test wäre es das einfachste, nur die AC-Werte in die Register 30000 und folgede zu schreiben, die man mit functioncode 0x04 lesen kann.

**Comment by dachauan** [comment]
Modbus TCP Sunspec wäre wirklich von Vorteil wenn man OpenDTU in eine größere Installation (z.B. Victron oder SMA) einbinden möchte.
