### ISSUE TITLE
MQTT telegram YieldTotal is kWh

### ISSUE THREAD

**Issue by dersch81** [tbnobody/OpenDTU#242]
Hi, 

here https://github.com/tbnobody/OpenDTU/blob/master/docs/MQTT_Topics.md is described YieldTotal is submitted as Wh. But it is submitted as kWh. Would it be possible to send the telegram as Wh?

**Comment by tbnobody** [comment]
Chaning this would break all currently running instances and data recordings...

**Comment by dersch81** [comment]
Ok, then just the doc need to be fixed
