### ISSUE TITLE
More than 10 Inverters on one OpenDTU requested  

### ISSUE THREAD

**Issue by pitsolar** [tbnobody/OpenDTU#2426]
### Is your feature request related to a problem? Please describe.

I am extending the number of panels of my installation using the garage roof. With the extension I am going beyond the maximum number of allowed (Hoymiles) ten inverters. I would need to have 11 :-(

### Describe the solution you'd like

Any chance to get the maximum number of inverters increased in the standard "opendtu-generic.bin" (at least to 14). 

### Describe alternatives you've considered

Thanks to a [running discussion](https://github.com/tbnobody/OpenDTU/discussions/1953) in German I am aware of adjusting the file:
OpenDTU/include/Configuration.h
old: #define INV_MAX_COUNT 10
new: #define INV_MAX_COUNT 14
It is mentioned that more is not possible because of the config size.

The other alternative of adding additional OpenDTUs would be possible but if there is a way around I would appreciate it. The integration into Home Assistant would be simpler staying with one piece of hardware

**Comment by tbnobody** [comment]
It is limited to 10 because of the available memory in the ESP32. 
But you are free to test it with 14. I will not increase the value because of possible stability issues.
