### ISSUE TITLE
WLAN Verbindungsverluste

### ISSUE THREAD

**Issue by ms1958** [tbnobody/OpenDTU#2437]
### What happened?

hallo, 
ich habe die OpenDTU mit der Version 24.11.7 am laufen.
Ich muss jetzt fast jeden zweiten Tag in die Garage, um die DTU zu reseten, weil er sich nicht wieder mit dem WLAN verbunden hat.
Die Tasmota Module daneben haben immer Connect vom gleichen Access Point. - Nach einer kurzen unterbrechung connecten die Tasmota sofort wieder,. Aber Die DTU nicht. - Das Thema hatten wir schon mal vor einiger Zeit.

Gruss, Manfred

### To Reproduce Bug

passiert alle 2,3 Tage

### Expected Behavior

das nach einem kurzen Wlanausfall sich die DTU wieder mit dem WLAN/Access Point verbindet

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

v24.11.7

### What firmware variant (PIO Environment) are you using?

generic_esp32

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by tbnobody** [comment]
> Das Thema hatten wir schon mal vor einiger Zeit.

Und auch die Issues sind dafür noch offen (#2366, #2400). Es macht keinen Sinn hier noch ein Issue aufzumachen.

Duplicate.
