### ISSUE TITLE
Prometheus power metric stuck after inverter power off

### ISSUE THREAD

**Issue by leahoswald** [tbnobody/OpenDTU#2455]
### What happened?

After updating from v24.10.15 to v24.11.7 the opendtu_Power metric is stuck to the last value reported by the inverter before power off due to too low power. So my inverter reports 6 W the whole night. The web interface and the mqtt client both report 0W correctly.
![Screenshot2024-12-09_22-17-45](https://github.com/user-attachments/assets/e663f4c6-85b6-4b52-8e7f-2e71169740b8)

### To Reproduce Bug

Look at the opendtu_Power metric at night. It is most probably not zero.

### Expected Behavior

The value is zero if the inverter isn't reachable or in power off state. As it was in v24.10.15

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

v24.11.7

### What firmware variant (PIO Environment) are you using?

generic_esp32

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by tbnobody** [comment]
Here it is zero and there was no change in the prometheus code as well..... Do you have any graphs of the days before which you can compare? 

Did you enable the [Zero Runtime Data](https://www.opendtu.solar/firmware/configuration/inverter_settings/#zero-runtime-data) function? Otherwise the values will never be zero at night (yeah maybe in some circumstances when the sun goes down very slowly and sets all the values to  zero before the inverter switches of --> happens often in sumer times)

**Comment by leahoswald** [comment]
Interesting, will have a look tomorrow.

**Comment by leahoswald** [comment]
You are right. It looked like it started with the update but there is one night a few days before the update where it happened too. Then nothing and the last few days it happened every day. And the Zero Runtime Data function wasn't enabled. I enabled it now. I wonder why I didn't observed this in over a year before but I think this will fix it. Sorry for the noise.

**Comment by leahoswald** [comment]
And just for the completeness if someone searches for the same thing: it works now with this option set.
