### ISSUE TITLE
Temperaturwert plötzlich falsch

### ISSUE THREAD

**Issue by ce3rd** [tbnobody/OpenDTU#246]
Hi, seit heute in der Früh wird die Temperatur falsch angezeigt - liegts am hm1500 oder an opendtu? Kann sein, dass es bei uns heute das erste mal minus Grade hatte - ev. das schuld? 
json "Temperature":{"v":6552.200195,"u":"°C"}
mqtt und web im anhang
![opendtutemp2](https://user-images.githubusercontent.com/115698782/196864518-45b8bc16-24ab-4f6e-8045-dbd1ecc54ae8.jpg)
![opendtutemp1](https://user-images.githubusercontent.com/115698782/196864536-215776bd-bb6d-44aa-9b6d-533ba1f20477.jpg)

**Comment by ce3rd** [comment]
ok, jetzt wo wir ins + rutschen passt es wieder: "Temperature":{"v":0.200000003,"u":"°C"}

**Comment by tbnobody** [comment]
Hallo,

damit bist du wohl der erste der jemals je negative temperaturen gemessen hat :)
Muss mal gucken wo da eine Konvertierung schief geht.

**Comment by stefan123t** [comment]
@tbnobody sieht nach einem fixed point integer und keinem uint aus.
65536 bzw. 6553.6 wäre demnach -0.1 °C wenn ich es richtig interpretiere.

**Comment by homeautomation2022** [comment]
quick fix für den eigentlich int16_t Wert mit einer Kommastelle, der aber als uint16_t zu float verarbeitet wird:
```
if (TEMP > 3276.7)
    TEMP -= 6553.6;
```
