### ISSUE TITLE
[Request] Additional support for ESP32-D0WDQ6-V3

### ISSUE THREAD

**Issue by mr-p666** [tbnobody/OpenDTU#2464]
### Is your feature request related to a problem? Please describe.

For my next setup, I got myself a few ESP32-D0WDQ6-V3s, which work pretty well.
I'm just missing the flash size and, above all, the CPU temperature, like I have on my ESP32-D0WD-V3.
For testing, I've already installed Tasmota on one of them, and there I get the measured values ​​from the flash size and also the sensor.

![image](https://github.com/user-attachments/assets/906c5134-dc3a-4103-8d58-64dbc3401209)

Thx a lot! :-)

### Describe the solution you'd like

Display of the two missing data. The flash size and the CPU temperature.

**Comment by tbnobody** [comment]
Please provide a screenshot of your system overview site running on the ESP32-D0WDQ6-V3

**Comment by mr-p666** [comment]
Sorry, I've been away for the last few days.
Hope this helps!
![signal-2024-12-31-102750](https://github.com/user-attachments/assets/ed52d582-5ff2-4efa-b8b4-7ef3813c9c9b)
![signal-2024-12-31-103209](https://github.com/user-attachments/assets/1adc89c1-bfbd-43a8-b379-3c71158e4fbf)
![signal-2024-12-31-103106](https://github.com/user-attachments/assets/2b77be04-b72d-48f0-aeb6-14903f3b0c1d)
![signal-2024-12-31-103143](https://github.com/user-attachments/assets/1def72d5-54c8-433f-9128-a9f02de8e365)

**Comment by tbnobody** [comment]
Please just install the latest Version to get Support for temperature and Flash Size. You are using the one from April where such things are just Not yet implemented

**Comment by mr-p666** [comment]
Shame on me... Thanks for your quick support!
I used the web installer on opendtu.solar to flash the new chip, expecting it always use the latest firmware, and it didn't occur to me to check the version number. :disappointed: 
Thanks again and Happy New Year! :fireworks:

**Comment by stefan123t** [comment]
@tbnobody which version will it use ? The latest release just before updating / regenerating the opendtu.solar pages from MkDocs ?

https://www.opendtu.solar/firmware/webinstall/
