### ISSUE TITLE
include ,in the project a second Akku via mqtt?!

### ISSUE THREAD

**Issue by mikewolf99** [tbnobody/OpenDTU#2486]
### Is your feature request related to a problem? Please describe.

is there a chance to include a second akku ? via mqtt 

### Describe the solution you'd like

is there a chance to include a second akku ? via mqtt

### Describe alternatives you've considered

is there a chance to include a second akku ? via Mqtt

### Additional context

is there a chance to include a second akku ? via mqtt

**Comment by tbnobody** [comment]
This project does not even include a first akku.... do you mean the OpenDTU-OnBattery project? Then please close this issue and open a issue there.

**Comment by mikewolf** [comment]
closed

**Comment by mikewolf** [comment]
[closed]
