### ISSUE TITLE
Unable to save DTU-Settings with auto-generated serial#

### ISSUE THREAD

**Issue by wib100** [tbnobody/OpenDTU#268]
### What happened?

After flashing the latest release 1.22 (ab72763), I tried to update poll interval in DTU Settings, but I was unable to save the changes because I received a message that the Serial# is not valid (please see screenshot
![Unable to save DTU Settings](https://user-images.githubusercontent.com/35136309/197785232-a2fa3a42-8ebe-42ab-8883-a8e24da3d3b6.png)
).
After removing one digit, I was able to save settings.

### To Reproduce Bug

- Flash a device with the latest version
- go to DTU-Settings
- change any value
- try to save the settins

### Expected Behavior

Auto generated serial should be a valid value.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

ab72763

**Comment by tbnobody** [comment]
The issue is just related to the web UI (https://github.com/tbnobody/OpenDTU/blob/ab727638810292cf2d45499588b553c8c1cb84a6/webapp/src/views/DtuAdminView.vue#L14). Will fix it this evening.
