### ISSUE TITLE
Leistungslimitierung HM-1500 ohne Effekt

### ISSUE THREAD

**Issue by DaAlchemist** [tbnobody/OpenDTU#27]
Hallo, ich habe einen HM-1500, wenn ich versuche bei MaxPower einen Wert einzusetzen und dann zu speichern , kommt zwar die Rückmeldung "Inverter changed" aber eine Limitierung findet nicht statt.

**Comment by tbnobody** [comment]
Hier findet auch keine Limitierung statt. Der Wert sollte die max. Leistung der angeschlossenen Solarzellen darstellen. Errechnet wird damit der Irradiation Wert in der Live Ansicht.
