### ISSUE TITLE
MI 300 Seriennummer

### ISSUE THREAD

**Issue by m0tschi** [tbnobody/OpenDTU#273]
### What happened?

Guten Abend zusammen,
leider hab ich noch einen MI-300 mit der S/N: 102160910382 welcher nicht erkannt wird trotz des aktuellen Git's
![grafik](https://user-images.githubusercontent.com/115314335/198131824-17d53d51-2cdb-428d-a7c9-940dbab4038a.png)
und leider sind meine Programmierkentnisse zu rudimentär um das selbst zu fixen... Wäre über hilfe sehr Dankbar!
Grüße
Marcel

### To Reproduce Bug

-

### Expected Behavior

MI-300

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

13b22de

**Comment by tbnobody** [comment]
MI Inverter werden nicht unterstützt (ist auch in der Readme zu finden) da diese ein komplett anderes Protokoll verwenden (Gen2 vs. Gen3).
