### ISSUE TITLE
No Values in Irradiation 

### ISSUE THREAD

**Issue by Hans-JR** [tbnobody/OpenDTU#30]
Moin,
erstmal vielen Dank für die tolle Arbeit.
Ich habe heute mal die aktuelle Version 01.17 geflasht. Soweit hat alles geklappt. Aufgefallen ist mir, dass das Feld für die Irradiation den Wert 0.00% anzeigt. Ich habe vorher den Adapter von ahoy getestet. Da wurde der Wert angezeigt.
Mein WR ist ein HM-300.
![Screenshot 2022-07-14 095554](https://user-images.githubusercontent.com/37930673/178932087-ef8c9262-adfe-4821-bfe9-da47d4069a92.jpg)
![Screenshot 2022-07-14 095727](https://user-images.githubusercontent.com/37930673/178932104-25c55f4e-02c2-4a56-af90-cbfa5d7d9d6d.jpg)

**Comment by braini75** [comment]
Moin,
hast du unter Settings -> Inverter Settings -> Edit Inverter... den Max power Wert eingetragen?

**Comment by tbnobody** [comment]
Hallo,

es sieht so aus als hättest du bei den Inverter Eingängen keinen Maximalwert konfiguriert: (siehe: https://github.com/tbnobody/OpenDTU/blob/master/docs/screenshots/13_InverterSettings.png)

**Comment by Hans-JR** [comment]
Das wars. Jetzt wird der Wert angezeigt. Ich hatte mich natürlich an das o. g. Bild gehalten. Da sind leider keine Werte eingetragen. So hab ich das dann auch gemacht.
Danke. Falls mir noch was auffällt, werde ich es berichten. 
Gruß
Hans-Jürgen
