### ISSUE TITLE
[Request] Longer MQTT-Username

### ISSUE THREAD

**Issue by Sinned42** [tbnobody/OpenDTU#302]
### Is your feature request related to a problem? Please describe.

I am using flespi.io as a broker for my MQTT.
Flespi.io uses tokens instead of Username and Password - unluckyly 64 characters, but only 32 characters are accepted.

### Describe the solution you'd like

I suggest doing some changes in code:

configuration.h line 20
#define MQTT_MAX_USERNAME_STRLEN 64

MqqtAdminView.vue line 58
<input type="text" class="form-control" id="inputUsername" maxlength="64"

Best regards,
Sinned42

**Comment by Sinned42** [comment]
Perfect, thank you. Time doesn't matter, I put my username direct in MqttSettings.cpp and it worked so far for me.

**Comment by m0tschi** [comment]
I appreciate it a lot, may you can do the same for the passwords? :)
thank you for all the improvements!

**Comment by OgerTours** [comment]
I check it with [ee5b5b1](https://github.com/tbnobody/OpenDTU/commits/ee5b5b1) build and unfortunatly it's still not allowing to put more than 32 chars into username field.

Can some please check and/or confirm?

**Comment by tbnobody** [comment]
What  error message are you getting?

The UI itself allows a lot of characters...
![image](https://user-images.githubusercontent.com/1753222/202850056-f040bd9d-83d9-413b-a442-e3acb991153b.png)

**Comment by OgerTours** [comment]
Sorry, my stupid fault, I fully need to refresh the browser page, seems that browser was caching the page contnet and doesn't allow it to put more than 32 chars. Now it's working. Sorry for confusion.

**Comment by tbnobody** [comment]
May I ask which browser you are using? (With my Vivaldi which uses the chromium engine the  ETAG headers are working pretty well and I just have to reload (just F5) the page to get the new changed content)

**Comment by OgerTours** [comment]
I use the Firefox Browser. You can perform a page reload with STRG+R or Shift+Click on the reload symbole.
