### ISSUE TITLE
Inverter Limit can be changed without being logged in first / Password protection does not work

### ISSUE THREAD

**Issue by D3R-ST3FAN** [tbnobody/OpenDTU#318]
### What happened?

With commit 11c272b (maybe earlier) inverter limit can be changed without being logged in in WebUI.
Inverter can also be restarted and trurned on/off. 

These functions should be protected as well.

### To Reproduce Bug

go to status page and set limit

### Expected Behavior

changing the limit should not be possible if not logged in

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

11c272b

**Comment by tbnobody** [comment]
Is on my list... Will follow the next days... Also Power On/Off/Restart will be protected...

**Comment by tbnobody** [comment]
Should be fixed with e0b069ff3da978c370157996870096e738e392ab
