### ISSUE TITLE
Seriennummer wird nach Update nicht mehr akzeptiert

### ISSUE THREAD

**Issue by tobox** [tbnobody/OpenDTU#337]
### What happened?

Ich habe gerade meinen OpenDTU, die Ende September korrekt funktioniert hat, auf den aktuellen Github Stand geupdatet. Im Anschluss wurde der WR nicht mehr erkannt. Ich kann ihn auch nicht erneut einrichten, wenn ich die Seriennummer eingebe, wird gesagt, die Seriennummer wäre zu groß:

![Screenshot_20221113_124250](https://user-images.githubusercontent.com/4719666/201520067-34275d5a-6998-4ce2-9aae-f96f967cb2f4.png)

### To Reproduce Bug

Aktuelle Firmware einspielen, TSUN 1600 mit langer Seriennummer einrichten.

### Expected Behavior

Sollte funktionieren, so wie früher.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

bad9031

### Relevant log/trace output

```Shell
Siehe Screenshot
```

**Comment by tbnobody** [comment]
Warum möchtest du die Seriennummer der DTU ändern? Hast du mehrere ESP Instanzen laufen und die Autogenerierung funktioniert nicht so das sich Seriennummern überschneiden?? 
Der Max Wert von 99999999999 wurde vor 19 Tagen auf 199999999999 geändert: 9c7dc681b1d91e58a80ccf268d56e3e335e04ee0

Frisch mal die Webseite neu auf (Strg+F5). Aber nochmal. An dieser Stelle trägt man NICHT die Seriennummer eines Inverters ein.

**Comment by tobox** [comment]
Au man... User Error. Ich habe die Seriennummer des WR bei der DTU eintippen wollen... Mehrmals zu uralten Versionen gedowngraded, immer dasselbe Problem. 

Jetzt gehts, hatte nur Tomaten auf den Augen. Sorry.
