### ISSUE TITLE
[Request] Summe über alle Inverter

### ISSUE THREAD

**Issue by merlin00284** [tbnobody/OpenDTU#347]
### Is your feature request related to a problem? Please describe.

Leider sind aktuelle Leistung, Tagesertrag,... nur für jeden eingerichteten Inverter einzeln zu betrachten.

### Describe the solution you'd like

Ein Block, welcher die Summe der Leistungsdaten über alle eingerichteten Inverter darstellt. Ähnlich dem oberen Block von AHOY.
Optional beim Invertersetup eine Checkbox, welche definiert, ob der Inverter in der Summendarstellung berücksichtigt wird.

**Comment by tbnobody** [comment]
Das ist seit ca. 14 Tagen implementiert: 438ce36bab8e0096fb7c79546fd7a9edf851d7d9
Du solltest die aktuelle Version verwenden...
