### ISSUE TITLE
Publish Inverter Total Data via MQTT

### ISSUE THREAD

**Issue by DerFossiBaer** [tbnobody/OpenDTU#350]
### Is your feature request related to a problem? Please describe.

Ich hab über den String http://ip-vom-dtu/api/livedata/status die Totalwerte aller aller auf dem DTU angemeldeten Wechselrichter gefunden, so wie sie auch im Kopf der GUI angezeigt werden. Diese scheinen jedoch per MQTT versendet zu werden.

### Describe the solution you'd like

Die Daten habe ich mir jetzt per http-get geholt.
Schön wäre es, wenn die Daten direkt per MQTT mit auflaufen würden.

**Comment by tbnobody** [comment]
Das steht bereits auf der "Wish List". Aber nun gibts auch ein Feature Request Issue das ich schließen kann wenn erledigt :)

**Comment by fkroepfl** [comment]
@tbnobody die Frage des Neulings: wie sieht der aktuelle Plan dazu aus? 🤗

**Comment by lanfire001** [comment]
Gibt es einen Zeithorizont wann das umgesetzt wird, oder muss man für dieses Feature auf die geforkte Version von Thro42 zurückgreifen?

**Comment by tbnobody** [comment]
Implemented in 26cbc496a795454b6808913f4fe66f6c623a267c
