### ISSUE TITLE
Irradiation is always zero

### ISSUE THREAD

**Issue by b-a-9-0** [tbnobody/OpenDTU#36]
Hi, 
I have OpenDTU running with 1x HM-1200 connected. Everythink works fine so far, except the irradiation value is always zero (see attachted picture). In my setup, there is only one PV module connected to the inverter. Irradiation is zero independent from current DC power.

![grafik](https://user-images.githubusercontent.com/10331861/180283009-04c28aa1-e3c8-4ef2-b7af-3bfa1dbc6c35.png)

Thanks for this amazing project!

**Comment by b-a-9-0** [comment]
used git hash: 0abd05c7ce28ea0fbb216524432a6211412dd303

**Comment by tbnobody** [comment]
Please go to the editor edit window and enter the max power of your PV module in the right channel as shown here: https://github.com/tbnobody/OpenDTU/blob/master/docs/screenshots/13_InverterSettings.png

**Comment by b-a-9-0** [comment]
Thanks, never saw these fields before!

**Comment by tbnobody** [comment]
Due to the fact that you where the second user who didn't see the addtional parameters I added a hint:
![image](https://user-images.githubusercontent.com/1753222/180294012-53aca99d-066e-426b-9a2d-9c2ca3451ddf.png)

**Comment by b-a-9-0** [comment]
Perfect!
