### ISSUE TITLE
Pinning change under settings [Request]

### ISSUE THREAD

**Issue by dAjaY85** [tbnobody/OpenDTU#421]
### Is your feature request related to a problem? Please describe.

Die D1 ESP32 Version ist vom Formfaktor sehr ähnlich zu der D1 Mini Version, dementsprechend ist es auch Möglich die ESP32 Version auf einen D1 mini Sockel drauf zu stecken. Leider passt dann aber die vordefinierte IRQ und CE Belegung des ESP32 Builds nicht dazu. Der IRQ Pin müsste auf GPIO17 und der CE Pin auf GPIO16 geändert werden. 

siehe Vergleich der Pin Belegung:
![image](https://user-images.githubusercontent.com/6034639/206652696-688ce834-0fe3-4fed-beb2-5a75702da1d8.png)

### Describe the solution you'd like

Es sollte eine Möglichkeit eingebracht werden, um die PIN-Belegung in den Einstellungen ändern zu können.
Allternativ dazu sollte ein zusätzliches ESP32 D1 Build mit der Komptabilität zum D1 Mini erzeugt werden.

### Describe alternatives you've considered

Es gibt die Möglichkeit die Pin Belegung beim kompilieren zu ändern, aber es hat nicht jeder die Möglichkeit, das Projekt über VSCode kompilieren zu können.

### Additional context

Durch diese Maßnahme wäre ein Wechsel vom D1 Mini ESP8266 auf einen D1 ESP32 mit geringen Aufwand möglich, es müsste lediglich der D1 Mini durch en D1 ESP32 getauscht werden.

**Comment by tbnobody** [comment]
Dies  ist durch die Device Profiles nun möglich. Pin Belegungen können in json Dateien zusammengefasst, ausgetausch, hochgeladen und  ausgewählt werden.

**Comment by dAjaY85** [comment]
Benötige dafür mehr Informationen, bzw. Unterstützung bei der Display Klasse.
