### ISSUE TITLE
HMS-2000 Unterstützung

### ISSUE THREAD

**Issue by JanX2** [tbnobody/OpenDTU#46]
Wie kann ich vorgehen um meinen HMS-2000 zu den unterstützen Geräten hinzuzufügen?

Ich bin Softwareentwickler. Apple Plattformen. Mein C++ ist nicht so besonders. Aber irgendwo muss ich ja anfangen. ;)

**Comment by tbnobody** [comment]
Vmtl. leider garnicht, da schon das Funkmodul (Hardware) ein anderes ist bei den HMS Invertern.

**Comment by JanX2** [comment]
Huch! Aber die werden doch von den selben DTUs unterstützt. Hab ich da was falsch verstanden?

**Comment by tbnobody** [comment]
HM und MI verwenden DTU-Lite und DTU-Pro
HMS und HMT verwenden DTU-Lite-S und DTU-Pro-S

**Comment by JanX2** [comment]
Ok. Mein Fehler.
