### ISSUE TITLE
[Request] Total Yield Total, Total Yield Day, Total Power aller Wechselrichter per MQTT

### ISSUE THREAD

**Issue by MiniOh** [tbnobody/OpenDTU#471]
### Describe the solution you'd like

Hallo, 

Ist es möglich bzw. angedacht die Werte
Total Yield Total, Total Yield Day, Total Power aller Wechselrichter per MQTT zu übertragen?
Dann müsste man diese nicht erst danach zusammenrechnen?

Vielen Dank schon vorab.

====================================================

Hello,

Is it possible or the values are being considered
Transfer Total Yield Total, Total Yield Day, Total Power of all inverters via MQTT?
Then you wouldn't have to add them up afterwards?

Thank you in advance.

**Comment by tbnobody** [comment]
Duplicate of #350
