### ISSUE TITLE
Language bundle fr.json differs from en.json/de.json

### ISSUE THREAD

**Issue by helgeerbe** [tbnobody/OpenDTU#490]
### What happened?

The France language bundle differs from the English and German bundles. 

In `fr.json` element 

````
inverteradmin{
    ...
    "StringNameHint": "Here you can specify a custom name for the respective port of your inverter.",
    ... 
},
````

is missing.

In `fr.json` in block 

````
    "invertertotalinfo": {
        ....
        "TotalVoltage": "Tension moyenne",
        "TotalCurrent": "Courant"
    },
````

the elements do not exist in `en.json`and `de.json`.

### To Reproduce Bug

Check line numbers and elements in language bundles.

### Expected Behavior

I would expect that all language bundles  should contain the same elements.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

dfec263

**Comment by tbnobody** [comment]
Thats right. `TotalVoltag`e and `TotalCurrent` don't belong here. I will remove them. If a translation is missing in one of the files the english translation will be used. I cannot translate this into French. I am not aware of the language. So therefor I could only copy the english text into the fr.json file. This would lead to the same result as if I just leave it out until someone translates it.
