### ISSUE TITLE
zero export via Home Assistent - opendtu lost connection to HM 1500

### ISSUE THREAD

**Issue by mag2bue** [tbnobody/OpenDTU#496]
### What happened?

If I update the power frequently, opendtu lost the connection to HM 1500. After restart opendtu, connection is back.

### To Reproduce Bug

Update the power each 5s

### Expected Behavior

Opendtu lost the connection to HM1500. 
Restart Opendtu -> connection are back.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

64afbf8

### Anything else?

I use Home Assistent via a automation to do "zero export"  If the automation runs, after around 10min, opendtu lost the connection to hm1500. I was hoping the connectin comes back - after 1h I did a restat of opendtu, connection come back.

INFO: update the power is via number.xxxx_limit_persistent_absolute

**Comment by tbnobody** [comment]
What shows the serial console?

There is NO static connection between the DTU and the inverter. For every request it is as it would be the first one. 
Have you tried to send the requests in a longer period than 5s?
Not sure if this short period is working.

**Comment by LJ9210** [comment]
@mag2bue  how did you enable zero export via automation?  can you put the yaml code here?

**Comment by mag2bue** [comment]
Good to know. Thanks! 

I will change my update time to 30s.
After the next sunny day, I will come back.

serial console?   where can I  find it?

**Comment by Archibald-Harry-Tuttle** [comment]
OpenDTU > info > console

**Comment by mag2bue** [comment]
funny - I can see the console on my mobile phone. but no on my computer.

![image](https://user-images.githubusercontent.com/25908794/211265891-48092d91-6b1d-41fe-a027-b87bfaf8cd15.png)


Browser: Chrome, Windows11

**Comment by tbnobody** [comment]
You should either clean your cache or reload the page with ctrl+f5. That should fix it

**Comment by tbnobody** [comment]
I assume that a increase of the update time solved the issue. Will close it... feel free to open it again if new information is available.
