### ISSUE TITLE
[Request] Anzeige des RSSI Wertes jedes WR?

### ISSUE THREAD

**Issue by tobiasfaust** [tbnobody/OpenDTU#503]
### Describe the solution you'd like

Hi,
ich suche nach einer Möglichkeit den besten Platz für die OpenDTU abhängig der Empfangsqualität der WR zu finden. Dafür wäre der RSSI Werte jedes WR hilfreich. Wäre es möglich diesen auf der "Live" Seite (zb. im Abschnitt "Phase 1" mit anzuzeigen wenn es ihn denn irgendwie gäbe?

**Comment by tbnobody** [comment]
Aktuell gibt es nichtmal die Möglichkeit überhaupt einen RSSI Wert auszulesen. Das NRF Modul selbst bietet so etwas als 1-bit Wert an aber hier gibt es aktuell keinerlei Erfahrungen.
