### ISSUE TITLE
[Request] Restrict access to config by user / password

### ISSUE THREAD

**Issue by erniberni** [tbnobody/OpenDTU#506]
### Is your feature request related to a problem? Please describe.

With knowledge of the ip address openDTU is accessible for anybody, even Network configs and sw update is possible. This is a big security issue. 

### Describe the solution you'd like

access to any other menu than Live Data and About should be restricted only for admin with password

**Comment by tbnobody** [comment]
I dont know what you mean... Everything is password protected.
