### ISSUE TITLE
pin_mapping.json Abspeichern

### ISSUE THREAD

**Issue by Juergen2453** [tbnobody/OpenDTU#523]
### What happened?

Wenn ich eine Sicherung der pin_mapping.json in der Konfigurationsverwaltung abspeichere so wird sie als config.json abgespeichert. Besser wäre es doch wenn sie als pin_mapping.json abgespeichert würde.

### To Reproduce Bug

Abspeichern in der Konfigurationsverwaltung.

### Expected Behavior

Dateiname: pin_mapping.json

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

0f39771

**Comment by tbnobody** [comment]
Fixed with 0772fd02aacc4b367e22a90346871bbd4f63a4c7
