### ISSUE TITLE
[Request] Offset für yieltotal ?!

### ISSUE THREAD

**Issue by eeprom23** [tbnobody/OpenDTU#549]
### Describe the solution you'd like

Ist es möglich einen Offset für yieldtotal zu hinterlegen um eventuell gebrauchte Wechselrichter zu „Nullen“ oder sich den Jahresertrag besser darstellen zu lassen ?

**Comment by jimknopf63** [comment]
Sollte möglich sein, Ahoy hat das mittlerweile implementiert. Da kann man einen Korrekturwert Yield Total setzen der dann vom tatsächlichen abgezogen wird

**Comment by tbnobody** [comment]
Das YieldTotal wird aus Werten der einzelnen String Kanäle ausgerechnet. D.h. um einen Konstanten Datenstand zu haben müsste der Offset ja pro String-Eingang einstellbar sein. Ist möglich, aber nur damit das so bewusst ist.

**Comment by eeprom23** [comment]
> Das YieldTotal wird aus Werten der einzelnen String Kanäle ausgerechnet. D.h. um einen Konstanten Datenstand zu haben müsste der Offset ja pro String-Eingang einstellbar sein. Ist möglich, aber nur damit das so bewusst ist.

Diese Funktion wäre toll. Bei ahoy ist es glaube gelesen zu haben auch so gelöst ! Vielen Dank für deine tolle Arbeit.

**Comment by JoeGhost-22** [comment]
Ist mir heute auch aufgefallen, da ich eine ahoy laufen habe und sie dort vorhanden ist. Die Nullung wäre ein nice to have. Besser wäre wenn beide dtu's die gleichen Topics nutzen würden. Ansonsten top Arbeit.

**Comment by tbnobody** [comment]
Implemented in 8cbae767970cc356026be3ac87279f3852d9b036
