### ISSUE TITLE
[Request] More digits for net/grid frequency possible?

### ISSUE THREAD

**Issue by JsBergbau** [tbnobody/OpenDTU#570]
### Is your feature request related to a problem? Please describe.

OpenDTU reports the net/grid frequency with 2 digits like 49.97 Hz. 
Since frequency snychronization is essitial I wonder if inverter reports frequency more accurate and OpenDTU just rounds the value. If so it would be great to get more digits, at least 3 like https://www.netzfrequenz.info/ reports.

### Describe the solution you'd like

Report more digits of grid frequency if inverter supports it.

**Comment by tbnobody** [comment]
The inverter does not report more digits then shown in the web UI or via mqtt. No rounding is done internally.
