### ISSUE TITLE
Change Limit via Home Assistant has no effect

### ISSUE THREAD

**Issue by itn3rd77** [tbnobody/OpenDTU#598]
### What happened?

I wanted to change the Limit via Home Assisitant but it seems neither the sliders entities for relative limit adjustment nor the number entities for absolute limit adjustment have any functionality.

![grafik](https://user-images.githubusercontent.com/2655169/219850107-9a63c058-e90e-48dc-b7d9-0450c9effc84.png)

I changed the values and watched the topics via MQTT Explorer but nothing changes. Is this a bug or intentional feature and the sliders and number entities are only for representation?

### To Reproduce Bug

In the device page of the auto detected device in Home Assistant move the slide e.g. for "Limit NonPersistent Relative" and check the result via openDTU UI or MQTT Explorer. Nothinfg happend and after the next update the slider is back at 100%.

### Expected Behavior

Changing the values via automation or UI in Home Assistant should result in an actial change of the desired limit.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

9681ede

**Comment by tbnobody** [comment]
Just doublechecked it here... works without problems:
![image](https://user-images.githubusercontent.com/1753222/219855353-ea243d2b-03dc-4077-89b1-f1f64349d8b9.png)

![image](https://user-images.githubusercontent.com/1753222/219855362-b116786d-6268-4a21-bc59-24cabea807c1.png)


First the command topic changes to 89 then after a little bit the status topic.

**Comment by itn3rd77** [comment]
Thanks again for the quick reply. Double check ACL and permissions but did not find an issue. As you confirmed it is working I removed the cmd topic and and now it is working - crazy shit. Double checked after a restart of HA and MQTT broker. Still working. Don't know what was wrong with the cmd topic, but now it works without flaws.

Thanks and best regards!
