### ISSUE TITLE
[Request] Unknown Inverter hardware part number

### ISSUE THREAD

**Issue by schwitzer78** [tbnobody/OpenDTU#617]
### Is your feature request related to a problem? Please describe.

Hallo ich habe einen 
HM-600 WR
600.HRS0.EU.HM

und OpenDTU erkennt ihn nur als unbekanntes Modell - und ich soll hier ein Ticket aufmachen.
Braucht ihr sonst noch 
![image](https://user-images.githubusercontent.com/125819361/220589197-ea2e9554-6b98-4f0d-8179-2d639a0e7c11.png)

### Describe the solution you'd like

HM-600 WR
600.HRS0.EU.HM

**Comment by tbnobody** [comment]
Hallo, Danke für die Info. Hardware Teilenummer 0 bzw. Hardware version 00.00 hört sich sehr seltsam an. Könntest du nach einer nacht (wenn der Inverter Stromlos war) ggf. nochmal schauen?

**Comment by tbnobody** [comment]
Da hier keine Rückmeldung mehr kam würde ich den "Issue" erstmal schließen.
