### ISSUE TITLE
[Request] yield_day zurücksetzen möglich? Sinnvoll/nötig für Akkubetrieb

### ISSUE THREAD

**Issue by ntfrnd** [tbnobody/OpenDTU#620]
### Is your feature request related to a problem? Please describe.

Betreibt man den Hoymiles am Akku, wird der Tages-Ertragszähler (yield_day) nie zurückgesetzt. 

Prinzipiell scheint ein reset des yield_day zu funktionieren - ich meine dies bei AhoyDTU gesehen zu haben?

### Describe the solution you'd like

Es wäre prima, wenn man eine Möglichkeit schaffen würde, den yield_day aus OpenDTU heraus zu resetten.
Wenn der Benutzer die Bedingungen in den Einstellungen selbst festlegen könnte, wäre sehr hilfreich, z.B.
- beim Tageswechsel
- beim Einschalten des Inverters
- zu einer festgelegten Uhrzeit
- Reset über MQTT 

Das würde helfen, bei Nachteinspeisung aus dem Akku anhand des eigenen Ablaufs für jeden Zyklus einen korrekten yield_day zu erhalten.

Beispiel:
Anwender 1: PV liefert, Einspeisung startet, Akku wird geladen, PV liefert nicht mehr, Einspeisung erfolgt weiter aus Akku. Wenn ich nun den Inverter abschalte (es sollte egal sein, ob das um 22h oder 3h oder sonst wann ist) ist das mein yield_day. Beim nächsten Einschalten (wenn die PV wieder liefert) sollte dieser wieder genullt starten.

Anwender 2: PV liefert, Einspeisung startet, Akku wird geladen, PV liefert nicht mehr. Einspeisung stoppt. Dies ist mein yield_day, der aber nicht zurückgesetzt wird, weil der Akku permanent am Inverter hängt. Einspeisung über Nacht (z.B. 20-4 Uhr) zur Grundlastabdeckung, also Inverter ein, yield_day resetten, Inverter aus, dies ist der yield_day der Nachteinspeisung. Damit bekommt man zeitlich versetzt zwei yield_days, die man weiterverarbeiten kann. 
Hier würde auch der Reset beim Inverter einschalten helfen, oder über MQTT, dann kann man das aus seiner Anwendung selbst steuern und wäre maximal flexibel :-)

### Describe alternatives you've considered

Dies würde Zusatzequipment ersparen.

**Comment by tbnobody** [comment]
YieldDay kommt ausschließlich aus dem Inverter. Es kann nicht einfach irgendwann zurückgesetzt werden ohne intern klimmzüge zu unternehmen und hin und her zu rechnen. YieldDay wird bei jedem Inverter Neustart zurückgesetzt. Das liegt aber nicht am ESP o.ä. sondern das macht der Inverter von sich aus.

**Comment by helgeerbe** [comment]
Es gäbe die Möglichkeit einen Inverter restart um Mitternacht durchzuführen, wenn das wichtig ist. Alternativ würde ich in HomeAssistant einfach einen Helper nehmen. Da gibt es auch Tageszähler.

**Comment by ntfrnd** [comment]
Hab ich befürchtet.
Aber wie macht das AhoyDTU? Da geht's offenbar auch?
Machen die dann einen Inverter-restart?

Home-Assistant hab ich nicht. Ansonsten müsste ich mir über die Differenzen über den Gesamtzähler selbst bilden.

**Comment by helgeerbe** [comment]
@ntfrnd dann sende doch per MQTT um Mitternacht.

[serial]/cmd/restart | W | Restarts the inverters (also resets YieldDay) | 1
-- | -- | -- | --

**Comment by ntfrnd** [comment]
Alles gut, ich finde selber ne Lösung. Entweder Restart des Inverters oder Rechnen über den Gesamtverbrauch. Mal sehen...

**Comment by D3R-ST3FAN** [comment]
> Ich hatte eine Frage zu dem YieldTotal. Kann ich diesen über den Wechselrichter zurücksetzen? Damit ich zb bei einem Gebrauchtkauf, meine aktuellen Werte habe.

Nein, das geht nicht. Du kannst aber bei den Einstellungen des WR einen Offset Pro Kanal einstellen. Das wird dann im "angezeigten" YT eingerechnet.

**Comment by tomg1970** [comment]
Ok so habe ich das schon gemacht. Also so eine Art "Werksreset" gibt es dann nicht.
DANKE dir
