### ISSUE TITLE
Crash on wipy 3.0

### ISSUE THREAD

**Issue by horfic** [tbnobody/OpenDTU#63]
Hi,
first of all i wanted to thank you for such great product.

When i first connected to the freshly flashed pycom wipy 3.0 and clicked around in the web gui i have seen that when i clicked Info -> Ntp without setting yet a wifi station information that the page did not load any content and the device rebooted.

![Screenshot 2022-08-06 154505](https://user-images.githubusercontent.com/994939/183251569-6589eacf-e42e-4d68-80aa-6985713c848d.png)

The issue only happend once for me.

cheers,
Horst

**Comment by tbnobody** [comment]
This is already fixed...
