### ISSUE TITLE
[Request] Set Relay on specific solar yield

### ISSUE THREAD

**Issue by janosch1337** [tbnobody/OpenDTU#631]
### Describe the solution you'd like

can you please implement a function that sets a GPIO to High when the PV panels have a certain yield? gladly for 4xRelay cards. then with 4 different input fields(set value Watt) + 2x delay times. first delay timer for delayed switch on and second for delayed switch off. so you could prevent that a "small" cloud directly causes the relay to be switched off.

so I would have the possibility to realize directly with the opendtu the logic for heating rod or heat pump pool!

**Comment by tbnobody** [comment]
I will not implement such a special feature. This project is only a bridge between the inverter and wifi. If you like such features you could implement it with any home automation software (e.g. HomeAssistant or OpenHAB). If you like it directly on the mikrocontroller you have to implement it yourself unfortunatly.
