### ISSUE TITLE
[Request] Don’t show not used strings on Live View

### ISSUE THREAD

**Issue by FilipeAmadeuO** [tbnobody/OpenDTU#633]
### Is your feature request related to a problem? Please describe.

Can you please implement a customization feature of the Live View ?
As an example, I have a HM-1500 but only using 3 of the 4 strings. 
The non-used string still shows on Live View 

### Describe the solution you'd like

Don´t show non used string on Live View

### Describe alternatives you've considered

More customization of Live View

**Comment by upintheairsheep** [comment]
Are you active Fillipe
