### ISSUE TITLE
Unbekanntes Modell! Hardware-Teilenummer 269496322 HM-400

### ISSUE THREAD

**Issue by dare83** [tbnobody/OpenDTU#644]
### What happened?

Unbekanntes Modell! Hardware-Teilenummer 269496322 HM-400

### To Reproduce Bug

Unbekanntes Modell! Hardware-Teilenummer 269496322 HM-400

### Expected Behavior

Unbekanntes Modell! Hardware-Teilenummer 269496322 HM-400

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

21aa3c5

**Comment by Solarteur** [comment]
Die oben angegebene Teilenummer passt nicht in das Schema der HM-Seriennummern. Diese müsste für einen HM-400 mit 1121 beginnen  und acht weitere Ziffern haben, also **HM-400: 1121 xxxx xxxx**

Vgl. z, B. https://www.mikrocontroller.net/topic/525778?page=single#7020587

**Comment by tbnobody** [comment]
Die Nummer von oben scheint wirklich eine Hardware-Teilenummer zu sein und keine Seriennummer.

![image](https://user-images.githubusercontent.com/1753222/221831420-30e5aabf-ee03-4a3e-9ce6-b229ed01d9c1.png)

Rot markiert wäre die entsprechende Nummer. Passt also schon irgendwie ins Schema.

@dare83 was sind denn die linken 7 Stellen der Seriennummer?

**Comment by dare83** [comment]
Also die Seriennummer ist 112163908926

![grafik](https://user-images.githubusercontent.com/49066898/221835719-ab31472c-b850-4720-8ac3-a6b2b45294b8.png)

Die Hardwareteilenummer habe ich aus der Anzeige vom OpenDTU

![grafik](https://user-images.githubusercontent.com/49066898/221835514-ac9e0131-dfe9-4937-942c-bf666b90a215.png)

**Comment by Solarteur** [comment]
Gibt es eine Fehlermeldung bei Hinzufügen eines neuen Wechselrichters unter Eingabe der Seriennummer (1121...)? Die Hardware-Teilenummer ist da ohne Bedeutung . Ist der HM-400 in Betrieb,  d. h. ein PV-Modul angeschlossen und es ist draußen hell? Nur dann kann OpenDTU den Wechselrichter erreichen.

**Comment by tbnobody** [comment]
Nein.... Er wird ja auch ausgelesen.... Soweit alles gut. Es kann nur nicht mit der Hardware-Teilenummer auf die Leistung usw. geschlossen werden.

**Comment by dare83** [comment]
> Gibt es eine Fehlermeldung bei Hinzufügen eines neuen Wechselrichters unter Eingabe der Seriennummer (1121...)? Die Hardware-Teilenummer ist da ohne Bedeutung . Ist der HM-400 in Betrieb, d. h. ein PV-Modul angeschlossen und es ist draußen hell? Nur dann kann OpenDTU den Wechselrichter erreichen.

ließ sich hinzufügen, läuft und zeig alles richtig an (soweit ich das verstehe)

**Comment by dare83** [comment]
> Nein.... Er wird ja auch ausgelesen.... Soweit alles gut. Es kann nur nicht mit der Hardware-Teilenummer auf die Leistung usw. geschlossen werden.

ich habe nur das gemacht, was in der meldung steht (siehe screenshot) ;) "Bitte melden sie die Hardwareteilenummer und das Modell..."

**Comment by tbnobody** [comment]
> ich habe nur das gemacht, was in der meldung steht (siehe screenshot) ;) "Bitte melden sie die Hardwareteilenummer und das Modell..."

Alles gut, danke dafür! :)

Werde den Teilenummer in die Mappings mit aufnehmen.
