### ISSUE TITLE
Hardware Teilnummer unbekannt

### ISSUE THREAD

**Issue by boctus** [tbnobody/OpenDTU#645]
### What happened?

Die Teilenummer ist unbekannt: 124097
Es handelt sich um eine HM-1500
Für die Datenbank.

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

97bc964

**Comment by tbnobody** [comment]
Da hier keine Rückmeldung mehr kam würde ich den "Issue" erstmal schließen.

**Comment by oggli01** [comment]
Hallo

habe das selbe problem HMS 2000 einer geht super ein andere fehler Die Teilenummer ist unbekannt: 124097 kann jemand helfen
danke VG Kai
