### ISSUE TITLE
Web API Auth required needs to be updated

### ISSUE THREAD

**Issue by polarbearing** [tbnobody/OpenDTU#646]
### What happened?

Upgraded OtA yesterday. 

Tried the web API, but it seems some calls that are listed in the [doc](https://github.com/tbnobody/OpenDTU/blob/master/docs/Web-API.md) as no auth actually need one. 

If that's intended, the doc should be updated accordingly. 

### To Reproduce Bug

curl -v

### Expected Behavior

doc matches system

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

a341c88

### Relevant log/trace output

```Shell
curl -v  http://opendtu/api/livedata/status
HTTP/1.1 401 Unauthorized

curl -v http://admin:****@opendtu/api/livedata/status
HTTP/1.1 200 OK

same e.g. for /api/system/status
```

**Comment by tbnobody** [comment]
Have you enabled this?
![image](https://user-images.githubusercontent.com/1753222/222228633-312c30cc-9c0e-49b2-ab6a-4e3c0c889664.png)

If not, you need a password

**Comment by tbnobody** [comment]
Added some remarks here: b91da0f681ef96bb611b723ffebe718fb6c08ca5
