### ISSUE TITLE
Add support for HMS2000 4T

### ISSUE THREAD

**Issue by belowm** [tbnobody/OpenDTU#659]
### Is your feature request related to a problem? Please describe.

First of all, thanks for this amazing project!
I own the HMS 2000 4T inverter and would love to see support for this added. Is it feasible at all, or has the protocol change significantly?

### Describe the solution you'd like

I'd like to help with this. Can someone point me to resources on how to get started?

**Comment by tbnobody** [comment]
This one is a duplicate of #412 
Btw, Work in Progress
