### ISSUE TITLE
LiveView for a short period 

### ISSUE THREAD

**Issue by OnkelDeus83** [tbnobody/OpenDTU#666]
### What happened?

Hi all,

I have a problem since 3 Days. After I installed an second Hoymiles. If I want to connect my OpenDTU via browser, I can not see LiveView. Browser wants to load but nothing happend. Erverything else works.  After restart via web I can see only for a short period LiveView.
![Screenshot 2023-03-07 180605](https://user-images.githubusercontent.com/121680563/223495943-1d399c98-3cad-40bc-957e-ffe9b26099bc.png)

### To Reproduce Bug

After restart via web I can see only for a short period LiveView.

### Expected Behavior

Do I dit  somthing wrong?

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

b42fff8

**Comment by helgeerbe** [comment]
Hi @OnkelDeus83,

this happens to me, only if the memory is fragmented and OpenDTU can't allocate memory for the JSON response. Can you check the console output? Do you see something like "Call to /api/livedata/status temporarely out of resources."

**Comment by OnkelDeus83** [comment]
Hi @helgeerbe,

I got only this as console output

20:22:58.253 > Interrupt received
20:22:58.355 > Interrupt received
20:23:03.695 > Interrupt received
20:23:03.785 > Interrupt received
20:23:08.996 > Interrupt received
20:23:09.103 > Interrupt received
20:23:14.551 > RX Period End
20:23:14.551 > All missing
20:23:14.551 > Nothing received, resend whole request
20:23:14.551 > TX SystemConfigPara Channel: 61 --> 15 80 21 81 47 80 14 54 .....
20:23:19.676 > Fetch inverter: 114........
20:23:19.676 > Request SystemConfigPara
20:23:19.874 > Interrupt received
20:23:19.874 > TX RealTimeRunData Channel: 40 --> 15 83 08 74 81 80 1....... 
20:23:25.049 > Interrupt received
20:23:25.169 > Interrupt received
20:23:30.389 > Interrupt received
20:23:30.488 > Interrupt received
20:23:35.847 > Interrupt received
20:23:41.172 > Interrupt received

**Comment by tbnobody** [comment]
What is the output if you open `http://<ip>/api/livedata/status`

**Comment by OnkelDeus83** [comment]
![P_20230310_113048](https://user-images.githubusercontent.com/121680563/224293610-fdd35e78-c1d5-4821-a82e-9773feb75e5b.jpg)

**Comment by OnkelDeus83** [comment]
![P_20230310_113048_1](https://user-images.githubusercontent.com/121680563/224293895-da29712d-450a-4c51-afc8-70852312a426.jpg)

**Comment by smarthausleben** [comment]
> I’m having the same problem since a while. I’m not sure but it can be that the problems started after I used a second OpenDTU device for testing. Also not sure but if I remember right, I could fix it by switching on the testing OpenDTU device and opening the web interface there. I guess after that both Interfaces where reachable again. Maybe another possibility was that I didn’t close the web interface on an other computer, so the browser window was still open on that computer. Currently I have the problem and below you can see the live status of that device.
> 
> I will start the test OpenDTU device later today and post the result here.
> 


**UPDATE**
So, starting the second device didn’t fix the problem. Web interface on the test device works without a problem but the other device is still not reachable on the web interface. Currently I’m just getting a white page. In the past sometimes it also loaded the top headline and the “Live-Daten” headline.

_“*/api/livedata/status”_ works without a problem and ioBroker is receiving the _mqtt_ data as well.

**Comment by smarthausleben** [comment]
By the way, I forgot to mention that I can’t reach the web interface from other devices too no matter which browser I’m using on those devices. So it really looks like a problem on the ESP32 device itself.

**Comment by Koen00** [comment]
I have the same issues. Once having the live view, I should not switch views, because I will not see anything else than an empty window. 
Using this ESP32: ESP32-S2 with external Antenna (Adafruit QT Py ESP32-S2 WiFi Dev Board with uFL Antenna Port - STEMMA QT)
Sometimes if I wait a long time (5 mins) there appears data again. Sometimes I also have an issue that the entire webpage is unreachable and I have to power cycle the ESP.

Memory usage:
`Heap 65%, Free 66kB;
LittleFs 8%, Free 176kB;
Sketch 71%, Free 565kB
`

Console output is normal. Seeing transmissions and such. nothing else.

**Comment by tbnobody** [comment]
@Koen00 how many inverters have you configured? A heap usage of 65% and 66kb free looks absolutly wrong. 
I have configured 2 inverters and have 147kb heap available. 
With so less available heap it is not possible to generate the statistics data. Therefor you don't get a live view.

**Comment by tbnobody** [comment]
Heap is in the RAM. Based on the datasheet an ESP32 (as well as -S2) has 320kB of RAM. Not sure why you have so less free.

**Comment by OnkelDeus83** [comment]
> Heap is in the RAM. Based on the datasheet an ESP32 (as well as -S2) has 320kB of RAM. Not sure why you have so less free.

Hi, thx that was the right way. I changed the ESP an everything is ok. I take a normal one without -S2.
