### ISSUE TITLE
Incorrect hiding of unused strings in Live View

### ISSUE THREAD

**Issue by PATROMO** [tbnobody/OpenDTU#670]
### What happened?

As the title says: Incorrect hiding of unused strings in Live View

Look at screenshots

<img width="1793" alt="Bildschirm­foto 2023-03-08 um 08 12 21" src="https://user-images.githubusercontent.com/318564/223646713-cc0cf7a4-fcf5-473a-a908-095b059bdc1f.png">

<img width="711" alt="Bildschirm­foto 2023-03-08 um 08 13 28" src="https://user-images.githubusercontent.com/318564/223646703-5f480d28-f6a1-44d6-824d-383c56bfd6a2.png">

Bug is from 220884f72ee331cf4fc0ecb30c33feccd7eca560. 

### To Reproduce Bug

Open Live View

### Expected Behavior

Look at screenshot

<img width="1663" alt="Bildschirm­foto 2023-03-08 um 08 22 47" src="https://user-images.githubusercontent.com/318564/223647957-74f0cc33-8c02-4f5d-81d4-aa17d9ac612b.png">

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

cbbbc21

**Comment by tbnobody** [comment]
What shows the setting of your inverter? (especially the max power for each string)

**Comment by PATROMO** [comment]
@tbnobody this is just an HTML markup error. Look at my Screenshort in "Expected Behavior". 
My first two strings are unused :)

**Comment by tbnobody** [comment]
Ahhh I see... problem seems to be this line:
https://github.com/tbnobody/OpenDTU/blob/cbbbc211343cc01dab89f684e3bc9df2ad8e16cb/webapp/src/views/HomeView.vue#L97

the column div is always output even if the innerhtml is later on hidden... will fix it this soon.

**Comment by PATROMO** [comment]
Thank you, it works.
