### ISSUE TITLE
[Request] German problem - 70% interlocking of the PV system

### ISSUE THREAD

**Issue by Odysseus85** [tbnobody/OpenDTU#679]
### Is your feature request related to a problem? Please describe.

For a long time in Germany, the feed-in power of most photovoltaic systems was limited to 70 percent of the nominal power for private individuals to avoid overloading the public grid... what bullshit. The new government has now almost lifted this. However, many providers refuse to lift this setting in the plants because it is too much effort or want to have several hundred euros for it.

The problem is that the Fronius is throttled because of this limit 4500 when other inverters (the two Hoymiles) supply too much current although the limit applies only to itself.
e.g. in my screenshot you can see that I can't change the zero feed in Value. At the same time, however, this ensures that if I add more (not locked) inverters in opendtu, the software throttles my Fronius roof system.

Can I somehow discard this value throttling in openDTU?
Thanks for your help!

Odysseus

### Describe the solution you'd like

The possibility to change or comment out the limits via config file.

![Fronius](https://user-images.githubusercontent.com/126114730/224287984-601e0a1d-bebf-43a5-bbef-8178c9765ceb.JPG)
![Fronius2](https://user-images.githubusercontent.com/126114730/224288143-ac5d6093-bc15-49f0-8ada-c1935a369482.JPG)
![unnamed](https://user-images.githubusercontent.com/126114730/224288180-f62c8041-d586-4ff1-b5cb-571c94337318.png)

**Comment by tbnobody** [comment]
I don't know exactly what you want. Is your inverter limited to 70% as a factory default? Then it's not possible to change this limit with OpenDTU because it's either a firmware setting (firmware upgrade is not possible with OpenDTU) or a grid profile setting (also not possible to update).

**Comment by Odysseus85** [comment]
Hello and thank you for the answer. The problem is a little difficult to explain understandably. 
So this inverter has never throttled off before. This has only started after adding to openDTU. 
Only since then it "knows" that the power production is above 4500 and locks.

**Comment by tbnobody** [comment]
Does the OpenDTU Webinterface show any Inverter Limits? Because OpenDTU does not have any Fronius interface or something like this. Maybe you have to find the issue in your source code where you are writing the OpenDTU data in Fronius?

**Comment by Odysseus85** [comment]
ok i will try to check that, only limit i found until now was the one above from the first screenshot.

**Comment by petrm** [comment]
You can only solve your problem by removing the 70% cap from your Fronius. I have two explanations:
1) Fronius talks to your grid energy meter and once it sees more than 70% of own maximum power going out, it throttles to hit that number.
2) Same like 1), except it throttles based on what Victron GX sees as total PV power generated.

Does it also throttle when you remove the OpenDTU integration from your GX? If yes, it's 1), if no it's 2).

**Comment by Odysseus85** [comment]
Hello pterm, and thank you for reply.
Yes it's definetly the second one, after removing from the gx device the throttleling stoped.
Its not the best solution but works for now, until I get somehow this baseline removed.

Thanks to everyone!
