### ISSUE TITLE
[Request] ESP32-C3-DevKitC-02 support

### ISSUE THREAD

**Issue by math322** [tbnobody/OpenDTU#680]
### Is your feature request related to a problem? Please describe.

I currently ported OpenDTU to a ESP32-C3-DevKitC-02. The source need some changes to get it working:

> src/InverterSettings.cpp

> SPIClass* spiClass = new SPIClass(HSPI);

HSPI is defined as 1 but it need to be 0

> src/PinMapping.cpp

> bool PinMappingClass::isValidNrf24Config()

The test checks for ">" but the Boards has a GPIO 0 and the check should be ">="

My settings in platformio.ini are:

; https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html
[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags = ${env.build_flags}
    -DHOYMILES_PIN_CS=2
    -DHOYMILES_PIN_MOSI=6
    -DHOYMILES_PIN_MISO=5
    -DHOYMILES_PIN_SCLK=4
    -DHOYMILES_PIN_IRQ=0
    -DHOYMILES_PIN_CE=1

The board also has no display and it would be nice to disable it completely, maybe with a define!?

### Describe the solution you'd like

-

**Comment by tbnobody** [comment]
ESP32-C3 should be already supported
