### ISSUE TITLE
Code size to large

### ISSUE THREAD

**Issue by EckmarSchmitz** [tbnobody/OpenDTU#686]
### What happened?

Getting the Git code and compile with "d1 mini esp32" I get the following error message:

Checking size .pio\build\d1 mini esp32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  17.4% (used 57160 bytes from 327680 bytes)
Error: The program size (1706889 bytes) is greater than maximum allowed (1572864 bytes)
Flash: [=====*** [checkprogsize] Explicit exit, status 1
=====]  108.5% (used 1706889 bytes from 1572864 bytes)
============================================ [FAILED] Took 38.87 seconds ============================================

Environment    Status    Duration
-------------  --------  ------------
d1 mini esp32  FAILED    00:00:38.873
======================================= 1 failed, 0 succeeded in 

With another ESP8266 board I get the same problem.
How to change the file size?

### To Reproduce Bug

Compile code from git hub with visual studio code

### Expected Behavior

binary should be generated.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

?

### Relevant log/trace output

```Shell
Checking size .pio\build\d1 mini esp32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  17.4% (used 57160 bytes from 327680 bytes)
Error: The program size (1706889 bytes) is greater than maximum allowed (1572864 bytes)
Flash: [=====*** [checkprogsize] Explicit exit, status 1
=====]  108.5% (used 1706889 bytes from 1572864 bytes)
============================================ [FAILED] Took 38.87 seconds ============================================

Environment    Status    Duration
-------------  --------  ------------
d1 mini esp32  FAILED    00:00:38.873
======================================= 1 failed, 0 succeeded in
```

**Comment by tbnobody** [comment]
Maybe you have done some own modifications to the souce code. The original code compiles without any problems and also fits into the flash.

**Comment by EckmarSchmitz** [comment]
Hallo tbnobody,
ich habe nochmals über VisualStudioCode das komplette Projekt aus Github neu geholt. Keine Änderungen gemacht nur neu über Ausführen/Debug starten das Projekt kompiliert.

Das ist die Ausgabe komplett:
*  Task wird ausgeführt: C:\Users\mail\.platformio\penv\Scripts\platformio.exe debug

Processing generic (board: esp32dev; framework: arduino; platform: espressif32@>=6.0.1)
---------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Firmware Revision: g055eb3a
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (6.1.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20007.0 (2.0.7)
- tool-esptoolpy @ 1.40500.0 (4.5.0)
- tool-openocd-esp32 @ 2.1100.20220706 (11.0)
- toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 45 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESP Async WebServer @ 1.2.3+sha.1dde9cf
|   |-- AsyncTCP @ 1.1.1
|   |-- ArduinoJson @ 6.20.1
|   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- ArduinoJson @ 6.20.1
|-- espMqttClient @ 1.3.3+sha.6a3f3a8
|   |-- AsyncTCP @ 1.1.1
|   |-- WiFiClientSecure @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- RF24 @ 1.4.5
|   |-- SPI @ 2.0.0
|-- U8g2 @ 2.34.15
|   |-- SPI @ 2.0.0
|   |-- Wire @ 2.0.0
|-- sunset @ 1.1.7
|-- LittleFS @ 2.0.0
|   |-- FS @ 2.0.0
|-- Hoymiles @ 0.0.1
|   |-- RF24 @ 1.4.5
|   |   |-- SPI @ 2.0.0
|   |-- Every
|   |-- SPI @ 2.0.0
|   |-- TimeoutHelper
|-- Ethernet @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- Update @ 2.0.0
|-- ResetReason
|-- DNSServer @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- WiFi @ 2.0.0
|-- MqttSubscribeParser
|   |-- espMqttClient @ 1.3.3+sha.6a3f3a8
|   |   |-- AsyncTCP @ 1.1.1
|   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|-- Ticker @ 2.0.0
Building in debug mode
Converting .pio\build\generic\index.html.gz.txt.o
Converting .pio\build\generic\zones.json.gz.txt.o
Converting .pio\build\generic\favicon.ico.txt.o
Converting .pio\build\generic\app.js.gz.txt.o
Compiling .pio\build\generic\src\Configuration.cpp.o
Compiling .pio\build\generic\src\Display_Graphic.cpp.o
Compiling .pio\build\generic\src\InverterSettings.cpp.o
Compiling .pio\build\generic\src\MessageOutput.cpp.o
Compiling .pio\build\generic\src\MqttHandleDtu.cpp.o
Compiling .pio\build\generic\src\MqttHandleHass.cpp.o
Compiling .pio\build\generic\src\MqttHandleInverter.cpp.o
Compiling .pio\build\generic\src\MqttSettings.cpp.o
Compiling .pio\build\generic\src\NetworkSettings.cpp.o
Compiling .pio\build\generic\src\NtpSettings.cpp.o
Compiling .pio\build\generic\src\PinMapping.cpp.o
Compiling .pio\build\generic\src\SunPosition.cpp.o
Compiling .pio\build\generic\src\Utils.cpp.o
Compiling .pio\build\generic\src\WebApi.cpp.o
Compiling .pio\build\generic\src\WebApi_config.cpp.o
Compiling .pio\build\generic\src\WebApi_device.cpp.o
Compiling .pio\build\generic\src\WebApi_devinfo.cpp.o
Compiling .pio\build\generic\src\WebApi_dtu.cpp.o
Compiling .pio\build\generic\src\WebApi_eventlog.cpp.o
Compiling .pio\build\generic\src\WebApi_firmware.cpp.o
Compiling .pio\build\generic\src\WebApi_inverter.cpp.o
Compiling .pio\build\generic\src\WebApi_limit.cpp.o
Compiling .pio\build\generic\src\WebApi_maintenance.cpp.o
Compiling .pio\build\generic\src\WebApi_mqtt.cpp.o
Compiling .pio\build\generic\src\WebApi_network.cpp.o
Compiling .pio\build\generic\src\WebApi_ntp.cpp.o
Compiling .pio\build\generic\src\WebApi_power.cpp.o
Compiling .pio\build\generic\src\WebApi_prometheus.cpp.o
Compiling .pio\build\generic\src\WebApi_security.cpp.o
Compiling .pio\build\generic\src\WebApi_sysstatus.cpp.o
Compiling .pio\build\generic\src\WebApi_webapp.cpp.o
Compiling .pio\build\generic\src\WebApi_ws_console.cpp.o
Compiling .pio\build\generic\src\WebApi_ws_live.cpp.o
Compiling .pio\build\generic\src\main.cpp.o
Building .pio\build\generic\bootloader.bin
Generating partitions .pio\build\generic\partitions.bin
esptool.py v4.5
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Compiling .pio\build\generic\lib849\AsyncTCP\AsyncTCP.cpp.o
Compiling .pio\build\generic\lib8bc\FS\FS.cpp.o
Compiling .pio\build\generic\lib8bc\FS\vfs_api.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFi.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiAP.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiClient.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiScan.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiServer.cpp.o
Compiling .pio\build\generic\lib633\WiFi\WiFiUdp.cpp.o
Archiving .pio\build\generic\lib849\libAsyncTCP.a
Compiling .pio\build\generic\libcce\ESP Async WebServer\AsyncEventSource.cpp.o
Archiving .pio\build\generic\lib8bc\libFS.a
Compiling .pio\build\generic\libcce\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\SPIFFSEditor.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\WebAuthentication.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\WebHandlers.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\WebRequest.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\generic\libcce\ESP Async WebServer\WebServer.cpp.o
Compiling .pio\build\generic\libfe8\WiFiClientSecure\WiFiClientSecure.cpp.o
Archiving .pio\build\generic\lib633\libWiFi.a
Compiling .pio\build\generic\libfe8\WiFiClientSecure\esp_crt_bundle.c.o
Compiling .pio\build\generic\libfe8\WiFiClientSecure\ssl_client.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\MqttClient.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Packets\Packet.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Packets\Parser.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Packets\RemainingLength.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Packets\String.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Transport\ClientAsync.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Transport\ClientPosix.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Transport\ClientSecureSync.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Transport\ClientSync.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\Transport\IPAddress.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\TypeDefs.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\espMqttClient.cpp.o
Compiling .pio\build\generic\libed0\espMqttClient\espMqttClientAsync.cpp.o
Compiling .pio\build\generic\libbb1\SPI\SPI.cpp.o
Compiling .pio\build\generic\lib20f\RF24\RF24.cpp.o
Compiling .pio\build\generic\lib9fd\Wire\Wire.cpp.o
Compiling .pio\build\generic\lib21c\U8g2\U8g2lib.cpp.o
Compiling .pio\build\generic\lib21c\U8g2\U8x8lib.cpp.o
Compiling .pio\build\generic\lib21c\U8g2\clib\mui.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\mui_u8g2.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_bitmap.c.o
Archiving .pio\build\generic\libbb1\libSPI.a
Archiving .pio\build\generic\libcce\libESP Async WebServer.a
Archiving .pio\build\generic\libfe8\libWiFiClientSecure.a
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_box.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_buffer.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_button.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_circle.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_cleardisplay.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_d_memory.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_d_setup.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_font.c.o
Archiving .pio\build\generic\libed0\libespMqttClient.a
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_fonts.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_hvline.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_input_value.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_intersection.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_kerning.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_line.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_ll_hvline.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_message.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_polygon.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_selection_list.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8g2_setup.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8log.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8log_u8g2.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8log_u8x8.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_8x8.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_byte.c.o
Archiving .pio\build\generic\lib20f\libRF24.a
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_cad.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_capture.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_a2printer.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_gp1247ai.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_gp1287ai.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_gu800.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_hd44102.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_il3820_296x128.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ist3020.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ist3088.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ist7920.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ks0108.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_lc7981.c.o
Archiving .pio\build\generic\lib9fd\libWire.a
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ld7032_60x32.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ls013b7dh03.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_max7219.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_pcd8544_84x48.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_pcf8812.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_pcf8814_hx1230.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_s1d15300.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_s1d15721.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_s1d15e06.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sbn1661.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sed1330.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sh1106_64x32.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sh1106_72x40.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sh1107.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sh1108.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_sh1122.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1305.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_128x32.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_128x64_noname.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_2040x16.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_48x64.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_64x32.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_64x48.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_72x40.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_96x16.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1306_96x40.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1309.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1316.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1317.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1318.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1320.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1322.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1325.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1326.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1327.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1329.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1362.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1606_172x72.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_ssd1607_200x200.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7511.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st75160.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st75256.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7528.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st75320.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7565.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7567.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7571.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7586s_erc240160.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7586s_jlx384160.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7586s_s028hn118a.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7586s_ymc240160.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7588.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_st7920.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_t6963.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1601.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1604.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1608.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1609.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1610.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1611.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1617.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1638.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1701_dogs102.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_d_uc1701_mini12864.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_debounce.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_display.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_fonts.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_gpio.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_input_value.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_message.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_selection_list.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_setup.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_string.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_u16toa.c.o
Compiling .pio\build\generic\lib21c\U8g2\clib\u8x8_u8toa.c.o
Compiling .pio\build\generic\libe61\sunset\sunset.cpp.o
Compiling .pio\build\generic\lib72b\LittleFS\LittleFS.cpp.o
Compiling .pio\build\generic\lib4ec\TimeoutHelper\TimeoutHelper.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\Hoymiles.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\HoymilesRadio.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\ActivePowerControlCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\AlarmDataCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\CommandAbstract.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\DevControlCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\DevInfoAllCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\DevInfoSimpleCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\MultiDataCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\ParaSetCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\PowerControlCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\RealTimeRunDataCommand.cpp.o
Archiving .pio\build\generic\libe61\libsunset.a
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\RequestFrameCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\SingleDataCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\commands\SystemConfigParaCommand.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\crc.cpp.o
Archiving .pio\build\generic\lib21c\libU8g2.a
Compiling .pio\build\generic\lib4f3\Hoymiles\inverters\HM_1CH.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\inverters\HM_2CH.cpp.o
Archiving .pio\build\generic\lib72b\libLittleFS.a
Compiling .pio\build\generic\lib4f3\Hoymiles\inverters\HM_4CH.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\inverters\HM_Abstract.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\inverters\InverterAbstract.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\AlarmLogParser.cpp.o
Archiving .pio\build\generic\lib4ec\libTimeoutHelper.a
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\DevInfoParser.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\Parser.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\PowerCommandParser.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\StatisticsParser.cpp.o
Compiling .pio\build\generic\lib4f3\Hoymiles\parser\SystemConfigParaParser.cpp.o
Compiling .pio\build\generic\lib82e\Ethernet\ETH.cpp.o
Compiling .pio\build\generic\lib56e\Update\HttpsOTAUpdate.cpp.o
Compiling .pio\build\generic\lib56e\Update\Updater.cpp.o
Compiling .pio\build\generic\lib76c\ResetReason\ResetReason.cpp.o
Compiling .pio\build\generic\lib520\DNSServer\DNSServer.cpp.o
Compiling .pio\build\generic\libf55\MqttSubscribeParser\MqttSubscribeParser.cpp.o
Archiving .pio\build\generic\lib4f3\libHoymiles.a
Compiling .pio\build\generic\libd80\Ticker\Ticker.cpp.o
Compiling .pio\build\generic\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\generic\FrameworkArduino\FirmwareMSC.cpp.o
Compiling .pio\build\generic\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\generic\FrameworkArduino\HWCDC.cpp.o
Compiling .pio\build\generic\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\generic\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\generic\FrameworkArduino\IPv6Address.cpp.o
Compiling .pio\build\generic\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\generic\FrameworkArduino\Print.cpp.o
Archiving .pio\build\generic\lib76c\libResetReason.a
Archiving .pio\build\generic\libd80\libTicker.a
Archiving .pio\build\generic\lib56e\libUpdate.a
Archiving .pio\build\generic\lib82e\libEthernet.a
Compiling .pio\build\generic\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\generic\FrameworkArduino\StreamString.cpp.o
Compiling .pio\build\generic\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\generic\FrameworkArduino\USB.cpp.o
Compiling .pio\build\generic\FrameworkArduino\USBCDC.cpp.o
Compiling .pio\build\generic\FrameworkArduino\USBMSC.cpp.o
Compiling .pio\build\generic\FrameworkArduino\WMath.cpp.o
Archiving .pio\build\generic\lib520\libDNSServer.a
Compiling .pio\build\generic\FrameworkArduino\WString.cpp.o
Compiling .pio\build\generic\FrameworkArduino\base64.cpp.o
Compiling .pio\build\generic\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-adc.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-bt.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-cpu.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-dac.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-gpio.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-i2c-slave.c.o
Archiving .pio\build\generic\libf55\libMqttSubscribeParser.a
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-i2c.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-ledc.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-matrix.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-misc.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-psram.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-rgb-led.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-rmt.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-sigmadelta.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-spi.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-time.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-timer.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-tinyusb.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-touch.c.o
Compiling .pio\build\generic\FrameworkArduino\esp32-hal-uart.c.o
Compiling .pio\build\generic\FrameworkArduino\firmware_msc_fat.c.o
Compiling .pio\build\generic\FrameworkArduino\libb64\cdecode.c.o
Compiling .pio\build\generic\FrameworkArduino\libb64\cencode.c.o
Compiling .pio\build\generic\FrameworkArduino\main.cpp.o
Compiling .pio\build\generic\FrameworkArduino\stdlib_noniso.c.o
Compiling .pio\build\generic\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\generic\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\generic\libFrameworkArduino.a
Linking .pio\build\generic\firmware.elf
Retrieving maximum program size .pio\build\generic\firmware.elf
Checking size .pio\build\generic\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  17.4% (used 57160 bytes from 327680 bytes)
Error: The program size (1706737 bytes) is greater than maximum allowed (1572864 bytes)
Flash: [=====*** [checkprogsize] Explicit exit, status 1
=====]  108.5% (used 1706737 bytes from 1572864 bytes)
============================================ [FAILED] Took 39.90 seconds ============================================

Environment    Status    Duration
-------------  --------  ------------
generic        FAILED    00:00:39.903
======================================= 1 failed, 0 succeeded in 00:00:39.903 =======================================

*  Der Terminalprozess "C:\Users\mail\.platformio\penv\Scripts\platformio.exe 'debug'" wurde mit folgendem Exitcode beendet: 1.
 *  Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.


Das Ergebnis ist das Gleiche wie mit den Änderungen für das D1 Mini ESP32. Was ist da falsch?
Visual Studio Code ist nicht meine normale Entwicklungsumgebung. Ich benutze für meine Projekte das normale Visual Studio 2022.
Ich hoffe du kannst mir helfen warum der Code nicht in den Microcontroller passen soll. Eigentlich wäre ja genügend ROM verfügbar.

Gruß
Eckmar


Von: tbnobody ***@***.***>
Gesendet: Sonntag, 12. März 2023 18:05
An: tbnobody/OpenDTU ***@***.***>
Cc: Eckmar Schmitz ***@***.***>; Author ***@***.***>
Betreff: Re: [tbnobody/OpenDTU] Code size to large (Issue #686)


Maybe you have done some own modifications to the souce code. The original code compiles without any problems and also fits into the flash.

**Comment by tbnobody** [comment]
> *  Task wird ausgeführt: C:\Users\mail\.platformio\penv\Scripts\platformio.exe debug

You are building with debug symbols. This leads to a larger code size (also the timings are different). I don't know which button you are pressing to compile the source, but its the wrong one :-)

**Comment by helgeerbe** [comment]
@tbnobody I know this might be a breaking change. But is it possible to change `partitions_customs`and take 200kB from the file system? So can gain additional 100kB for the firmware? 

While writing I see, that debug build needs additional 130 kB. So this will not work. But to extend the firmware partition would help for further extensions.

**Comment by tbnobody** [comment]
> @tbnobody I know this might be a breaking change. But is it possible to change partitions_customsand take 200kB from the file system? So we can gain additional 100kB for the firmware?

Yes that will be needed in a nearby future. But as you said, it will be a very breaking change. All users have to re-flash everything using the USB port. This is why I would postpone this as long as possible. Also the further integration of HMS/HMT inverters will take some memory. But currently it still fits.

**Comment by helgeerbe** [comment]
Well my OpenDTU-onBattery has 22kB left for the sketch. I would vote for as soon as possible. ;)

**Comment by tbnobody** [comment]
I am going to close this issue as it referes only to the debug build
