### ISSUE TITLE
Feature Request - Langer Servername

### ISSUE THREAD

**Issue by juergen-dietz** [tbnobody/OpenDTU#71]
Hi,
euer Projekt läuft sehr gut mit meinem neuen HM-600, vielen Dank.

Könnt Ihr die länge des Servernamen ( MqTT Broker Parameter ) auf 64 Zeichen erweitern ?
Leider weiss ich nicht wie man den webapp Teil neu erzeugt.

**Comment by tbnobody** [comment]
Hallo,
der webapp Teil ist sogar der einfachere Teil. Ich muss gucken wie ich die config so umbauen kann, das sie für bestehende Benutzer kompatibel ist. (Normal kein Problem aber man darf nicht einfach die Länge dort ändern)
Bei der Gelegenheit würde ich die Länge vmtl. direkt auf 128 Zeichen erhöhen. 
Max DNS Name Länge ist 253 Zeichen aber das fände ich dann doch etwas übertrieben.

**Comment by juergen-dietz** [comment]
Hi,
super es klappt, vielen Dank. 
Ich kann bestätigen das jetzt die MQTT Verbindung zu HiveMQ-Cloudinstanzen funktioniert.
Zur Info, nach dem Firmwareupdate auf [217fddf] hatten sich beim Inverter die "Max Power" Werte verändert.
