### ISSUE TITLE
Model HM-800

### ISSUE THREAD

**Issue by tabacha** [tbnobody/OpenDTU#711]
### What happened?

The Software tells me to fill a bug and tell you that I use a HM-800

![image](https://user-images.githubusercontent.com/1101544/225987371-6fe6d944-ec76-4fa7-90c8-4b17dab00798.png)

### To Reproduce Bug

I Click on the Button: "Zeige Wechselrichter Informationen"

### Expected Behavior

No Message that i should fill a bug.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

4c3172f

**Comment by homeautomation2022** [comment]
Bitte nochmal DTU neustarten(bei Tag natürlich), dann klappt es vermutlich, anscheiennd wurden Daten falsch oder nicht geparst, da Teilenummer und Version eine 0 drin steht. Der Rest passt komischerweise, also das Packet mit den Daten kam an vom Wechselrichter.

**Comment by tabacha** [comment]
Okay, jetzt taucht die Meldung nicht mehr auf
