### ISSUE TITLE
Display SH1106 upside down OpenDTU Build #556

### ISSUE THREAD

**Issue by stupsi099** [tbnobody/OpenDTU#721]
### What happened?

sometimes after i flash my openDTU with a new build my display is upside down and only with an other version it works correct.

### To Reproduce Bug

OpenDTU Build #556  flashed 2 times.
Display SH1106

### Expected Behavior

with OpenDTU Build #555 display works correct.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

 bf05dc8    master

**Comment by tbnobody** [comment]
Just go to Settings --> Hardware --> Display and rotate it.

**Comment by stupsi099** [comment]
Thx  for the new feature
