### ISSUE TITLE
Display Icons missing after update

### ISSUE THREAD

**Issue by x2on** [tbnobody/OpenDTU#733]
### What happened?

After update to the newest version the icons on the display are missing.

### To Reproduce Bug

Update to newest version

### Expected Behavior

Icons on the display are still there.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

d508b41

**Comment by tbnobody** [comment]
Icons where removed because they don't bring any benefit and lead to burn in of the oled.

**Comment by x2on** [comment]
That's a pity. Now the display looks boring. It was really nice with the icons before.
