### ISSUE TITLE
limit_nonpersitent: negative Werte bzw. Limit

### ISSUE THREAD

**Issue by kpwg** [tbnobody/OpenDTU#736]
### What happened?

Bei Übergabe negativer Werte mit MQTT (beispielsweise -100) scheint es einen Überlauf zu geben. Der HM-1200 zeigt dann "Aktuelles Limit: 6.552 W | 546 %", was so nicht stimmen kann. Hier sollte bei Werten unter Null entsprechend 0W/0% gesetzt werden.

Weiterhin wäre es prima, wenn es eine einstellbare positive Begrenzung gibt, z.B. 400W für einen HM-600. Ich sehe darin eine zuverlässige "Absicherung" für alle Nacht-Einspeiser, um durch versehentlich zu hohe Leistungen dem Equipment (Batterie, Spannungsaufbereitung, etc.) nicht zu schaden.

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

bf05dc8

**Comment by tbnobody** [comment]
Das Thema mit < 0 werde ich einbauen. Werte < 0 werden dann ignoriert.
Ein maximales Limit macht an der Stelle meiner Meinung nach keinen Sinn. Es wird ggf. nur von wenigen Menschen benötigt und erzeugt unverhältnismäßig viel Verwaltungsaufwand mit Konfig Dialogen, speichern, anwenden usw....

Die Nachteinspeiser können müssen das Limit ja auch senden und berechnen. Ein kleines `min()` in deren Code sollte hier ja alle Probleme lösen. Vgl: `publish(min(400, value));`
