### ISSUE TITLE
Verwendung der Hoymiles.h als Library

### ISSUE THREAD

**Issue by sivar2311** [tbnobody/OpenDTU#74]
Hallo Thomas!

Eigentlich ist das kein Issue, sondern mehr eine Frage :)

Ich habe versucht die Hoymiles.h als Library in einem kleinen [Testsketch](https://github.com/sivar2311/HoymilesTest/blob/main/src/main.cpp) zu benutzen.
Allerdings bekomme ich keine Daten geliefert. 
Kannst du mir einen Tipp geben, was ich falsch mache?

(Ich verwende die gleichen Seriennummern wie im openDTU).

Gruß
Boris

**Comment by tbnobody** [comment]
Hi, 
ich vermute das du in der Konsole nicht mal TX Meldungen bekommst. Das liegt wohl daran das du keine Zeit setzt. Es muss die aktuelle Zeit hinterlegt sein da diese in jedem Paket mitgeschickt wird.

**Comment by sivar2311** [comment]
Ah, stimmt :) Da war ja was!
Danke für den Hinweis - Ich implementiere schnell mal NTP dazu.

**Comment by sivar2311** [comment]
Ja, das war des Rätsels Lösung!
Vielen Dank 👍
