### ISSUE TITLE
Negative or incorrect pos. values (Energy) when offset is used (during startup of the inverters

### ISSUE THREAD

**Issue by Dom1n1c** [tbnobody/OpenDTU#753]
### What happened?

I Specified a "Yield total offset" (Ertragsversatz) for my used HM400
![image](https://user-images.githubusercontent.com/8407566/228021164-22a69280-9e75-4dc4-a705-4cd8d32c3f6b.png)

When the device is offline, i will get a negative value
![image](https://user-images.githubusercontent.com/8407566/228020590-daf6d382-8067-4610-82fc-8c817dc87f48.png)

### To Reproduce Bug

Add an offset and powercycle OpenDTU

### Expected Behavior

From my understanding the offset should only be used when the Inverter is online. (Or has produced energy !=0)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

c47b7dd

**Comment by DPO99** [comment]
Kann es sein, dass dies immer dann passiert, wenn der Wechselrichter nach dem Neustart noch keine Daten übermittelt hat und dies auch erstmal nicht tut, da keine sonne und der Offset sozusagen auf den Gesamtertragswert von 0 angewendet wird? Was passiert denn, wenn der WR Online war/ist, dann das Offset korrekt greift und dann der WR aus geht, weil keine Leistung mehr kommt?

**Comment by Dom1n1c** [comment]
Ganz genau, das ist korrekt. Das passiert immer nur dann, wenn der WR noch keine Daten liefert.
