### ISSUE TITLE
Spelling error introduced with typo fix 8d8c7f8 "Successfully --> Successfuly" 

### ISSUE THREAD

**Issue by Neruk** [tbnobody/OpenDTU#757]
### What happened?

With the recent change to fix the typo  "Successfull --> Successful" 8d8c7f8 the word **Successfully** is now spelled **INCORRECT** **Successfuly**.

**Issue: Successfully --> Successfuly**
**Fix: Successfuly --> Successfully**

Typo 1: https://github.com/tbnobody/OpenDTU/blob/c47b7dd33502ee8dd9ea36d11da1c6886add7b8e/webapp/src/views/ConsoleInfoView.vue#L90

Typo 2:
https://github.com/tbnobody/OpenDTU/blob/c47b7dd33502ee8dd9ea36d11da1c6886add7b8e/webapp/src/views/HomeView.vue#L492

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

c47b7dd

### Anything else?

_Sorry if this is the wrong way to report the issue. I have never done anything like this ("bug report") before on GitHub._

**Comment by tbnobody** [comment]
Fixed in 89597953048e45baed1c1400ae80f21ca3e8c626
