### ISSUE TITLE
OpenDTU code won't build successfully without making changes in platformio.ini

### ISSUE THREAD

**Issue by juergen-weber** [tbnobody/OpenDTU#765]
### What happened?

Undercores missing:
platformio.ini contains the line [env:d1 mini esp32] which causes:
Error: Invalid environment name 'd1 mini esp32'. The name can contain alphanumeric, underscore, and hyphen characters (a-z, 0-9, -, _)

### To Reproduce Bug

Sinply starting the build process in platformio

### Expected Behavior

Happens every time when starting a build

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

using a pull from April 30th, 2023

**Comment by juergen-weber** [comment]
Thanks for your replay.
Don't put any efforts into this. For the time being, I can simply replace the spaces with underscores in [env:d1 mini esp32]. At least the [env:d1 mini esp32] looks inconsistent compared to the others. May be there's a hidden switch within PIO/VSCode to make the parser more picky. 

PS C:\Users\juerg\Meine Ablage\PlatformIO\Projects\OpenDTU> pio system info
--------------------------  ------------------------------------------------------
PlatformIO Core             6.1.7a4
Python                            3.8.10-final.0
System Type                   windows_amd64
Platform                         Windows-10
File System Encoding     utf-8
Locale Encoding             cp1252
PlatformIO Core Directory   C:\Users\juerg\.platformio
PlatformIO Core Executable  C:\Users\juerg\.platformio\penv\Scripts\platformio.exe
Python Executable           C:\Users\juerg\.platformio\penv\Scripts\python.exe
Global Libraries            0
Development Platforms       4
Tools & Toolchains          23
--------------------------  ------------------------------------------------------
PS C:\Users\juerg\Meine Ablage\PlatformIO\Projects\OpenDTU> pio check
Error: Invalid environment name 'd1 mini esp32'. The name can contain alphanumeric, underscore, and hyphen characters (a-z, 0-9, -, _)

**Comment by cocolino83** [comment]
ciao sto riscontrando questo errore, ma non riesco a risolvere. mi potreste dare un aiuto? vene saro grato.
![Screenshot 2023-10-13 235848](https://github.com/tbnobody/OpenDTU/assets/88486650/1ebd26cc-f01b-45c3-bea5-17490ed54793)
