### ISSUE TITLE
MQTT HomeAssistant Auto discovery do not work

### ISSUE THREAD

**Issue by DejanBukovec** [tbnobody/OpenDTU#766]
### What happened?

When enabling MQTT in OpenDTU it connect to broker but do not publishing a specially formatted JSON payload to Home Assistant...

In broker solar topic is visible and it refresh states:
![slika](https://user-images.githubusercontent.com/52787044/229054875-3b598d42-0a30-4f89-bf4d-0f12e1c5e309.png)

Settings looks ok:
![slika](https://user-images.githubusercontent.com/52787044/229056617-1d7e6e3f-a78e-40fe-9577-c8ea25cb0d25.png)

Other devices like shelly normally show in integration as new device...

### To Reproduce Bug

Im try enable/disable MQTT in OpenDTU but do not help.

### Expected Behavior

When MQTT is connected it publishing a specially formatted JSON payload to Home Assistant...

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

c47b7dd

**Comment by tbnobody** [comment]
Are you sure you've enabled the home assistant feature in opendtu?

**Comment by DejanBukovec** [comment]
Yes Im sure:
![slika](https://user-images.githubusercontent.com/52787044/229148937-bbaffd13-5f30-4c45-a351-a0a845577e65.png)

One question... I have inverters added to OpenDTU but they are not online(New installation and panels are not connected to inverters)... Can this be problem? That MQTT is send only if inverters are availible?

Live Data page also do not show anything:
![slika](https://user-images.githubusercontent.com/52787044/229149761-07fb6eff-985d-4748-a39d-f5d83cdcc036.png)

**Comment by tbnobody** [comment]
This might be the problem yes. The config is only published if the radio is idle: https://github.com/tbnobody/OpenDTU/blob/c47b7dd33502ee8dd9ea36d11da1c6886add7b8e/src/MqttHandleHass.cpp#L44

Problem hereby is, that if your poll interval is too low, the radio is never in idle mode because it has to wait for all the timeouts. On the other hand, the HASS config is only published when 
* Restart of DTU
* MQTT connection status changes
* MQTT settings where saved

**Comment by tbnobody** [comment]
Just saw your second screenshot. You should see the inverters in the live view!
Can you make a screenshot of the inverter config?

**Comment by DejanBukovec** [comment]
Im find problem... Typo in serial of test inverter... Now it show model on inverters list(Before model has been empty). Now it also show in main page:
![slika](https://user-images.githubusercontent.com/52787044/229152560-f4c630e8-5817-4cd3-98da-82525b3c91f0.png)

And is send to HA MQTT...

![slika](https://user-images.githubusercontent.com/52787044/229152943-21005d01-9170-4f38-a0bb-0a05d389bc72.png)

Bug report can be closed and marked as false...
