### ISSUE TITLE
[Request] Mail Notification

### ISSUE THREAD

**Issue by hchristo** [tbnobody/OpenDTU#770]
### Is your feature request related to a problem? Please describe.

Mail Notifikation Daily/Weekly for Total income Total, Total income Today and Total output

### Describe the solution you'd like

Mail Notifikation Daily/Weekly for Total income Total, Total income Today and Total output

**Comment by tbnobody** [comment]
Mail notification is something which you want on a home automation system or any other kind of device which reads the  mqtt values. This is nothing which will be implemented no a device which should act as a bridge.
