### ISSUE TITLE
Missing MQTT Topics

### ISSUE THREAD

**Issue by iukbox** [tbnobody/OpenDTU#782]
### What happened?

I installed the latest Version and it works.
After that i tried a MQTT Connection to iobroker. The Topics are created, but there are no CMD Topics, only
![opendtu_mqtt](https://user-images.githubusercontent.com/26631519/230644018-d1bb9e42-84f6-4dfe-a3b6-d8e6d5f74c9d.jpg)

### To Reproduce Bug

Normal Installation, activating MQTT 

### Expected Behavior

I thought that the Topics automaticly were created

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.4.6

### Relevant log/trace output

```Shell
Nothing
```

### Anything else?

![opendtu_mqtt](https://user-images.githubusercontent.com/26631519/230644567-93ed1a01-10db-424a-b067-e39bcebab4ce.jpg)

**Comment by tbnobody** [comment]
This is not a issue of OpenDTU. Thats the MQTT protocol by design.
Please see https://github.com/tbnobody/OpenDTU/issues/451 and the discussion. There several people already discussed how to send MQTT values to topics.
