### ISSUE TITLE
MQTT doppelte Werte bei /0/power

### ISSUE THREAD

**Issue by hismastersvoice** [tbnobody/OpenDTU#8]
Erst mal DANKE für die großartige Arbeit.
Nachdem ich mich mit PaltformIO länger beschäftig habe, habe ich es jetzt auch hin bekommen ;)

Beim übertragen der Werte für /topic/inverter-sn/0/power werden mit 2 Werten übertragen. (siehe Grafik)
Erst kommt ein etwas höherer Wert und ein paar Millisekunden später ein etwas niedrigerer Wert hinterher.
Das ist nur bei diesen Item so, alle andere werden nur mit einem Wert übertragen 

![01-07-2022_17-44-46](https://user-images.githubusercontent.com/7402918/176928434-05706ed7-06c9-4ee0-aa44-50289b259fa4.jpg)

Es ist egal ob ein oder mehrere Inverter eingebunden sind, mit oder ohne Retain-Flag etc,

Ist das ein Fehler von mir, oder kommt das von der Software?

**Comment by tbnobody** [comment]
Du hast recht, das ist ein Bug. Der höhere Wert ist der DC Wert, während der niedrigere der AC Wert ist. Diese werden nur dummerweise auf die gleiche Topic published. 

Sollte hiermit behoben sein. https://github.com/tbnobody/OpenDTU/commit/d5f32d83253e2397f77c03d631b66e9e5ca38986

**Comment by hismastersvoice** [comment]
Danke für die schnelle Antwort.

Schön wäre wenn du dann DC und AC separat ausgeben könntest.
Mir wäre AC sogar lieber, das ist ja die tatsächlich Leistung die ich verwenden kann.

Ich hätte noch ein paar Feature Requests... ;)
- reboot per URL zb http://ip/reboot (ggf. auch ins WebUI)
- Zeit der letzten Übertragung (epoch) so könnte man/ich prüfen lassen ob alles sauber läuft.
- json ausgabe, um den Umweg über MQTT zu sparen.

Wenn du also mal Zeit übrig hast und das auch sinnvoll findest freu ich mich.
Danke schon mal.

**Comment by hismastersvoice** [comment]
Habe es gerade eingespielt... Funktioniert perfekt... Danke.

**Comment by tbnobody** [comment]
> Schön wäre wenn du dann DC und AC separat ausgeben könntest.
der AC Wert kommt aktuell als 0/power und der DC wert als 0/powerdc

Beim Reboot bin ich etwas skeptisch. Weil eigentlich sollte der Qualitätsstandard schon so sein das es keine Reboots benötigt. (Was aktuell auch so der Fall ist, jegliche Einstellungen werden sofort übernommen) Und wenn etwas instabil wird, ist das ein Fehler und sollte so und so behoben werden.

Zeit der letzten Übertragung klingt in der Tat gut. Werde ich mir mal notieren.
Bzgl. Json meinst du einen Web-Endpoint würde ich annehmen? Also ein pollen der Werte statt das sie beim Update gepushed werden (an den MQTT Broker)?

**Comment by hismastersvoice** [comment]
json... 
Entweder aktiv pollen bei Anfrage, oder die Werte die alle x Sekunden abgeholt werden per json abrufbar anbieten.
Ich glaube das hat bei Ahoy einer vor kurzem implementiert.

reboot
Bin ich voll und ganz bei dir das es eigentlich so sein sollte.
Aber ich habe es heute diverse male geschafft das er sich immer wieder aufgehängt hat bzw. keine Live-Daten mehr angezeigt hat. Dann musste ich ihm vom Strom nehmen. 
Sicher mag es daran liegen das ich extrem viel gespielt habe... 

PS:
Aktualisiereng per F5 führt immer in einen 404 Fehler, man muss die Seiten immer per Menü auswählen.

**Comment by tbnobody** [comment]
> Aber ich habe es heute diverse male geschafft das er sich immer wieder aufgehängt hat bzw. keine Live-Daten mehr angezeigt hat.


Live Daten werden erst bei Aktualisierung der Daten (also wenn neue Daten vom WR gelesen werden) oder spät. nach 10Sek. angezeigt. Wenn zwischenzeitlich der ESP gebootet wird, findet nach 60Sek ein Reconnect des WebSockets zum ESP statt. 
Sollten andere $Dinge passiert sein muss man beobachten.

> Aktualisiereng per F5 führt immer in einen 404 Fehler, man muss die Seiten immer per Menü auswählen.

Habe ich gerade behoben. Hatte ich auch schon bemerkt, aber war noch Low Prio. Allerdings wird in dem Moment die WebApp neu geladen (also die ganzen ~300kb, das ist nicht sehr schön. Ggf. benötigt es auf den einzelnen Seiten noch einen Refresh Knopf der einfach die Ajax Requests erneut ausführt)

**Comment by hismastersvoice** [comment]
Bei mir hatte er dann >30Min, keine Daten mehr angezeigt, nach einem reboot lief es sofort wieder.
Ich werde es mal beobachten ob ich das ganze nachstellen kann.
Auf jeden Fall läuft es deutlich stabiler als alles was ich mit dem ESP8266 (ahoy) hinbekommen hatte. 
Danke nochmal für deine Arbeit.


Das mit dem laden der 300kb bei F5 refresh find ich tragbar, da würde ich jetzt keine Energie verschwenden das anders zu machen. Ich habe es gerade getestet und denke damit kann jeder leben. ;)

**Comment by ahinrichs** [comment]
> Ich hätte noch ein paar Feature Requests... ;)
> - json ausgabe, um den Umweg über MQTT zu sparen.

Hm. Das gibt es doch schon. Du kannst doch direkt auf den Websocket verbinden. Z. B. mit wscat oder eigenen Scripten und bekommst dann die Live Daten ohne MQTT. 

Höchstens noch ein eigener API Call, aber das würde bei jedem Pollen einen vollen Request auslösen. Ist also sicher weniger effizient.

**Comment by hismastersvoice** [comment]
Ja, das hast du recht.
Leider gibt es auch Geräte wie zB den Loxone MiniServer der das so nicht kann.
Um den Umweg über einen Raspi zu ersparen wäre eine reine Json die ich per http abrufen kann ideal.

**Comment by tbnobody** [comment]
@hismastersvoice fyi: Es gibt mit dem aktuellsten commit von heute einen API Endpunkt: `/api/livedata/status`
Der liefert ein json Objekt mit allen Daten die auch im Live View angezeigt werden.

**Comment by hismastersvoice** [comment]
Perfekt, werde es am WE testen.
DANKE!

**Comment by hismastersvoice** [comment]
@tbnobody 
Funktioniert perfekt... DANKE:
