### ISSUE TITLE
Unterschiedliche Consolen für die angeschlossenen Wechselrichter

### ISSUE THREAD

**Issue by tuvok81** [tbnobody/OpenDTU#829]
### Is your feature request related to a problem? Please describe.

Es ist besser wenn man die einzelnen Wechselrichter Abfragen in der Konsole einzeln sieht

### Describe the solution you'd like

Wenn man auf Konsole geht wäre es gut, wenn man den Wechselrichter den man eingetragen hat auswählen kann, für den man die gewünschte Ausgabe haben möchte

**Comment by tbnobody** [comment]
Das ist so nicht möglich, da die Console alle Debug Meldungen anzeigt und nicht nur Inverter Polls. Desweiteren kann man gewisse Log Meldungen auch nicht einfach einem Inverter zuordnen. Es ergibt sich einfach aus dem Kontext der Meldungen als Ganzes.
