### ISSUE TITLE
New MQTT topics ac/yieldday and ac/yieldtotal are swapped

### ISSUE THREAD

**Issue by Slummi** [tbnobody/OpenDTU#843]
### What happened?

With v23.4.24 new MQTT topics for total values have been introduced.
The values of the topics ac/yieldday and ac/yieldtotal are swapped. ac/yieldday has the value of ac/yieldtotal and vice versa.

### To Reproduce Bug

Update to v23.4.24 and compare the total power values of the new MQTT topics with the total power values of the single inverters.

### Expected Behavior

The MQTT topic ac/yieldday should provide the sum of the yieldday values of all connected inverters and not the sum of yieldtotal values.
The MQTT topic ac/yieldtotal should provide the sum of the yieldtotal values of all connected inverters and not the sum of yieldday values.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.4.24

**Comment by tbnobody** [comment]
Omg... You are right :-/

https://github.com/tbnobody/OpenDTU/blob/8a85aea543bafd43b3108220c737c02c48f29bb3/src/MqttHandleInverterTotal.cpp#L68-L69

Will fix it this evening
