### ISSUE TITLE
HM 600

### ISSUE THREAD

**Issue by Mike223311** [tbnobody/OpenDTU#863]
### Is your feature request related to a problem? Please describe.

Hallo,
👍👍👍
erst mal meinen Dank an das Team der Ahoy- als auch openDTU.
👍👍👍

Ich betreibe ein Balkonkraftwerk (zwei Platten a‘ 385 Watt) mit einem Hoymiles HM 600 mit Seriennummer 114xxxxxxxxx. (Baujahr 2022)
Habe mir die Ahoy- als auch die openDTU gem. Anleitung zusammen gestellt.
Die Ahoy mit ESP8266 und NRF24L01+
Die open mit ESP32 und NRF24L01+
Beide mit der aktuellen Software geflasht.
Beide funktionieren bei mir einwandfrei, keine Probleme.

Problem:
Beide DTU‘s habe ich nun bei einem Freund ausprobiert, der auch einen Hoymiles HM600, allerdings ein älteres Model mit Seriennummer 104xxxxxxxxx betreibt.
Die AhoyDTU erkennt diesen WR und ich kann die Leistungsdaten auslesen, allerdings ist kein Powermanagement möglich.
Die openDTU erkennt den WR nicht, kein Auslesen, kein Powermanagement möglich.

Wäre super wenn die Profis beider Team‘s eine Lösung finden würden.

Grüsse 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by DPO99** [comment]
Hast Du mit der Opendtu schon Mal einen Wechselrichter auslesen können? Sprich funktioniert die ganze Kiste überhaupt?

Zu ahoy wirst du hier nicht fündig da gibt's ne eigenen GitHub.

**Comment by Mike223311** [comment]
Hallo,ja, wie geschrieben funktionieren beide in der angegebenen Konfiguration bei mir einwandfrei. Habe bei beiden DTU‘s alles Daten zum Auslesen und bei beiden auch ein Powerlimit setzen.Ich hab diesen Thread bei Open und Ahoy rein gesetzt.GrüsseAm 30.04.23 um 18:13 schrieb DPO99
                
            
            
                
                    Von: "DPO99" ***@***.***>Datum: 30. April 2023An: "tbnobody/OpenDTU" ***@***.***>Cc: "Mike223311" ***@***.***>,"Author" ***@***.***>Betreff: Re: [tbnobody/OpenDTU] HM 600 (Issue #863)
                
                
Hast Du mit der Opendtu schon Mal einen Wechselrichter auslesen können? Sprich funktioniert die ganze Kiste überhaupt?
Zu ahoy wirst du hier nicht fündig da gibt's ne eigenen GitHub.

**Comment by tbnobody** [comment]
> der auch einen Hoymiles HM600, allerdings ein älteres Model mit Seriennummer 104xxxxxxxxx betreibt.

Das ist dann kein HM600 sondern ein MI-600... dieser verwendet ein anderes Protokoll welches aktuell von OpenDTU nicht unterstützt wird. Siehe #509

**Comment by Mike223311** [comment]
Danke, ich bin neu hier und konnte noch nicht alles lesen :-(GrüsseAm 30.04.23 um 18:24 schrieb tbnobody
                
            
            
                
                    Von: "tbnobody" ***@***.***>Datum: 30. April 2023An: "tbnobody/OpenDTU" ***@***.***>Cc: "Author" ***@***.***>,"Mike223311" ***@***.***>Betreff: Re: [tbnobody/OpenDTU] HM 600 (Issue #863)
                
                

der auch einen Hoymiles HM600, allerdings ein älteres Model mit Seriennummer 104xxxxxxxxx betreibt.

Das ist dann kein HM600 sondern ein MI-600... dieser verwendet ein anderes Protokoll welches aktuell von OpenDTU nicht unterstützt wird. Siehe #509
