### ISSUE TITLE
Neustart nach nicht funktionierendem Update (OnBattery)

### ISSUE THREAD

**Issue by IngoEF** [tbnobody/OpenDTU#870]
### What happened?

neueste Firmware in PlatformIO (VS) kompiliert und OTA versucht.
Blieb wieder bei 35% hängen und es passierte nichts weiter.
Neustart per UI angeschubst und den Hinweis auf Bugreport gelesen.
Deshalb nun dieser Bericht.
Das Verhalten ist nun das zweite Mal dasselbe und persistiert.
Auch Holen der neuesten "opendtu-onbattery-generic.bin" und Einspielen via OTA bleibt an derselben Stelle hängen.
Mir bleibt nichts anderes übrig, als den ESP32 komplett zu löschen und per VS neu zu flashen.

### To Reproduce Bug

Try to flash new version via OTA stucks at 35%.

### Expected Behavior

successfull flashin a new firmware

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

83b42a3

### Relevant log/trace output

```Shell
doesn't show anything
```

**Comment by Solarteur** [comment]
Ist das nicht eher ein Issue für 
https://github.com/helgeerbe/OpenDTU-OnBattery
?

**Comment by homeautomation2022** [comment]
Habe dieses Problem auch manchmal, bleibt dann immer an der gleichen Stelle hängen udn es leigt nciht an der Bin.
Das Problem lässt sich aber (zumindets bei mir) anscheinend beheben, wenn man den ESP Rebootet und dann das ganze nochmal versucht. Hatte es aber glaube auch schon einmal, da ging es dann nur noch per USB über VSC zu flashen, nicht mehr per OTA.
Ursache dafür ist noch unbekannt.

**Comment by IngoEF** [comment]
Solarteur wrote: seems to be the wrong branch
