### ISSUE TITLE
[Request] Update firmware via URL

### ISSUE THREAD

**Issue by MichaelKunze** [tbnobody/OpenDTU#880]
### Is your feature request related to a problem? Please describe.

Using github release is a very nice improvement. What i do now is to watch the release page, download the opendtu-generic.bin and feed it to the firware update dialog. But...

### Describe the solution you'd like

What if i could provide an URL (example: https://github.com/tbnobody/OpenDTU/releases/download/v23.5.3/opendtu-generic.bin) instead of the file itself.

Or easier: https://github.com/tbnobody/OpenDTU/releases/latest/download/opendtu-generic.bin
The webform could simply always use that url to update to latest by clicking a button (maybe show the changelog prior that)

**Comment by b-a-9-0** [comment]
This would be a very handy feature!
