### ISSUE TITLE
[DynDNS]

### ISSUE THREAD

**Issue by glucosum** [tbnobody/OpenDTU#898]
### Is your feature request related to a problem? Please describe.

I miss such a function.

### Describe the solution you'd like

I suggest including the "DynDNS" function in your project.
I suggest using the ready code on GitHub.

### Describe alternatives you've considered

You can add to OpenDTU yourself, but I have not reached the appropriate level of VSO support.
You can use another ESP32 for DynDNS to work.

### Additional context

Theoretically, the function seems redundant. But during tests, trying different solutions, it starts to make sense. Not only do we know what the current IP address of our home network is. By redirecting the ports on your home router, you can log into OpenDTU.
The feature could be disabled by default. Only those interested could turn it on.

**Comment by tbnobody** [comment]
This is something which belongs to a router or dialup device and not to a small piece of hardware which is meant to be a bridge between a solar inverter and wifi (mqtt/http)

There are also a lot of dyndns providers. which one should be implemented? all of them? As mentioned above, a device like router or raspberry has a lot of memory and resources. It is better kept there.
