### ISSUE TITLE
Unbekanntes Modell HMS-1600 + Limit Absolut in Watt wird nicht übernommen

### ISSUE THREAD

**Issue by mattespiratos** [tbnobody/OpenDTU#905]
### What happened?

Hallo,

Open DTU hatte mir mitgeteilt das ich das Unbekannte Modell melden soll.

![Screenshot 2023-05-09 113740](https://user-images.githubusercontent.com/128760487/237057594-faebf1b4-a471-4867-9e73-33b01bad466e.jpg)

Des Weiteren wird der Wert: limit_absolute nicht gesetzt und verbleibt auf "-1" wenn ich einen Absoluten Wert z.b. 1500 Watt eingebe wird dies übernommen aber nur als relativer % Wert.

VG
Matthias

### To Reproduce Bug

Bei jedem Limit setzen.

### Expected Behavior

Falls möglich den Bug mit dem Limit setzen beheben.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.5.3

### Relevant log/trace output

```Shell
"name":"HMS 1600 Garten (600)","data_age":4,"poll_enabled":true,"reachable":true,"producing":true,"limit_relative":87.5,"limit_absolute":-1,"AC":{"0":{"Power":{"v":749.7999878
```

### Anything else?

-

**Comment by tbnobody** [comment]
Ist mit 7be5dd865aee1b4755552e653ac0d63be510adb7 erledigt...
