### ISSUE TITLE
Eventlog Fehler

### ISSUE THREAD

**Issue by itn3rd77** [tbnobody/OpenDTU#91]
Hallo Thomas,

habe heute neben zwei Hoymiles HM-400 noch einen HM-1200 in Betrieb genommen. Hier ist mir erstmals ein komischer Eintrag im Eventlog aufgefallen. Anbei ein Screenshot:

![grafik](https://user-images.githubusercontent.com/2655169/185607517-294ed602-ba72-4dce-a029-26406d0b752c.png)

Beste Grüße
Ingo

**Comment by tbnobody** [comment]
Sollte so etwas nochmals auftreten wäre der Output von `http://<OpenDTU IP>/api/eventlog/status` hilfreich

**Comment by tbnobody** [comment]
Sollte hiermit auch behoben sein: 9674e32c0c381a8b1db90fae39f7bc6a4d30f1cf
