### ISSUE TITLE
MQTT sendet Nachts ac/yieldtotal und /ac/yieldday mit Null Wert bei deaktivierung "Daten auch nachts abrufen"

### ISSUE THREAD

**Issue by Skusi** [tbnobody/OpenDTU#913]
### What happened?

Bei Einstellung der Wechselrichter auf "Daten auch nachts abrufen" aus, werden die Mqtt Werte für ac/yieldtotal und /ac/yieldday auf Null gesetzt.
Das bring Probleme bei der Statistischen Auswertung der Werte mit sich.

### To Reproduce Bug

Nach Sonnenuntergang die Topics prüfen.

### Expected Behavior

Auch in der Nacht sollten die kumulierten Werte weiter beibehalten Werden und per MQTT abrufbar sein. 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

9e6b885

**Comment by tbnobody** [comment]
This is similar or duplicate to #887
