### ISSUE TITLE
MQTT auto reconnect

### ISSUE THREAD

**Issue by SiByte** [tbnobody/OpenDTU#919]
### What happened?

Sometimes OpenDTU and Homeassistant lost MQTT connection. Can OpenDTU try automatically reconnect after few seconds or minutes? When my lost connection I need to restart my ESP32.

### To Reproduce Bug

Restart MQTT server on Home Assistant.

### Expected Behavior

Auto reconnect.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.5.9

**Comment by tbnobody** [comment]
Just double checked it multiple times... auto reconnect works perfectly....

**Comment by SiByte** [comment]
This happend to me last week once and today.
