### ISSUE TITLE
HMS-2000 Blindleistung/Leistungsfaktor falsch

### ISSUE THREAD

**Issue by D3R-ST3FAN** [tbnobody/OpenDTU#926]
### What happened?

Der HMS-2000 zeigt im letzten aktuelle build
eine Blindleistung von

Blindleistung  6.553,5  var an.

Sieht für mich nach einer Art Überlauf aus.
<img width="281" alt="blindleistung" src="https://github.com/tbnobody/OpenDTU/assets/30196271/23ed62b8-c40f-486c-8d25-bbceb32ea213">

Der Leistungsfaktor macht auch keinen Sinn, hier scheint auch etwas falsch zu sein. 
Liegt sicher an der Berechnung wegen der falschen Blindleistung.

### To Reproduce Bug

Wert wird sofort angezeigt.

### Expected Behavior

Richtiger Wert wird angezeigt.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.5.9

**Comment by tbnobody** [comment]
Könntest du ggf. einen Auszug aus der Konsole (Info --> Konsole) posten? Interessant wären hier die RX Zeilen nach einem RealTimeRunData Befehl.

**Comment by homeautomation2022** [comment]
Bei HMS-2000 mit Firmware 1.0.14 ist das ein mehrfach bestätigter bekannter Bug:
Leistungsfaktor(PF) sowie die damit verbundene Blindleistung(Q) sind da falsch und können nicht auf den realen Wert zurückgerechnet werden. Man müsste bei dieser Kombination eigentlich die beiden Werte verbergen, da nie richtig.

Der Hinweis sollte als bekannter Bug vielleicht irgendwo mit in die Readme aufgenommen werden.

Die haben da intern einen Berechnungsfehler drin:
Q scheint falsch zu skalieren / falsch berechnet zu werden und läuft mit zunehmender Leistung beim Sonnenaufgang von 0 bis 0xFFFF hoch und verbleibt da, das kann man bei langsammen Sonnenaufgang und auch wieder Untergang beobachten (nur im ganz niedrigen Watt Bereich).
Da nun der PF aus P und Q berechnet wird und Q irrsinnig hoch ist, resultiert daraus ein PF von nahezu 0.

**Comment by D3R-ST3FAN** [comment]
Kann ich bestätigen Firmware-Version ist 1.0.14.

Ist denn eigentlich bei den HMS WRs die FW via DTU-Pro Updatebar?

**Comment by homeautomation2022** [comment]
Ja, das macht/kann die original DTU. Es gibt auch schon min. eine neuere FW für den, die auch wieder richtige PF und Q Werte bringt. Die 1.0.12 davor hatte den Fehler übrigens nicht, nur die 1.0.14.

**Comment by tbnobody** [comment]
Aufgrund der Tatsache das man an der Stelle eigentlich nicht mehr machen kann, habe ich das Verhalten hier dokumentiert https://github.com/tbnobody/OpenDTU/wiki/FAQ und würde das Issue schließen.
