### ISSUE TITLE
[Request] Inverterdaten als JPG/PNG / Inverterdata as JPG/PNG

### ISSUE THREAD

**Issue by jwerda** [tbnobody/OpenDTU#939]
### Describe the solution you'd like

Hallo. 
Habe eine Idee, die vielleicht für den ein oder anderen mit AVM Telefon oder ähnlichem Gerätschaft von Interesse ist.

Wäre es möglich die Daten, die man auch auf einem Display anzeigen kann, als JPG oder PNG bereitzustellen?
Die Bilddatei dann alle x Minuten aktualisieren oder erst wenn die entsprechende URL aufgerufen wird.
z.B. Aufruf per API / URL
<ip-der-opendtu>/api/livedata/status/info.jpg

Hintergrund: AVM Telefone können Bilder darstellen, z.B. von Webcams siehe "Live-Bild einrichten" unter
[https://avm.de/service/wissensdatenbank/dok/FRITZ-Box-7490/1602_Live-Bild-von-IP-Kamera-fur-FRITZ-Fon-einrichten/](url)

Werte könnte man sich dann auch einfach am Telefon oder anderem Geräte anschauen, die JPG über eine URL anzeigen können.

Nur ne Idee...

**Comment by tbnobody** [comment]
Nein, Dafür müsste man die JPGs bzw. PNGs auf einem Gerät rendern das gerade mal 300kb RAM hat. Sehe ich da leider wenig erfolgversprechend.
