### ISSUE TITLE
Renamed inverter not reflected in live data view

### ISSUE THREAD

**Issue by thomasleitner** [tbnobody/OpenDTU#95]
I have changed the name of my inverter in the inverter settings. However the "live data" view still has the old name.

**Comment by itn3rd77** [comment]
Can confirm this. The old name is although still send over MQTT

**Comment by thomasleitner** [comment]
Renamed inverter is shown OK when ESP32 is rebooted ... so the bottom line is: After renaming an inverter, you need to reboot the ESP32.

**Comment by madmartin** [comment]
Another situation where #67 and  #81 would be useful.

**Comment by tbnobody** [comment]
> so the bottom line is: After renaming an inverter, you need to reboot the ESP32.
No, the bottom line is, that this is a bug which has to be fixed and I will do it if I have time available.
