### ISSUE TITLE
TSOL M-800 is only recognized as HM-600

### ISSUE THREAD

**Issue by fol83** [tbnobody/OpenDTU#994]
### What happened?

When setting up the inverter via the serial number, the TSOL M-800 is only recognized as HM-600. 
In the inverter settings, it is displayed as HM-600, HM-700, HM-800, but under the inverter information as HM-600. As a result, the limit settings cannot be changed. 

### To Reproduce Bug

OpenDTU was reset and everything was set up and integrated again -> Same problem

### Expected Behavior

That the TSOL M-800 is recognized correctly. 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.1

### Relevant log/trace output

```Shell
-
```

### Anything else?

-

**Comment by tbnobody** [comment]
This is a expected behavior as the TSOL inverters are just re-labled Homyiles ones. The hardware and software are 100% identical. So there is no  possibility to distinct between them.
